"""
Генератор упражнений Главы 83 (Часть 2: Упражнения 15–28).
Системная изоляция, Seccomp и Linux Capabilities.
"""

exercises = [
    {
        "num": 15,
        "title": "Запуск с минимальными capabilities: Dockerfile nonroot и сброс CAP_SYS_ADMIN",
        "task": "Спроектируйте production-grade многоэтапный Dockerfile для Go-микросервиса. Настройте непривилегированного пользователя (USER nonroot:nonroot, UID 10001), сбросьте все избыточные Linux Capabilities, оставив исключительно CAP_NET_BIND_SERVICE (если требуется слушать порт 80). Напишите Go-код, который программно проверяет наличие capabilities у текущего процесса и пытается выполнить операцию, требующую CAP_SYS_ADMIN (например, монтирование или swapon), корректно подтверждая блокировку с ошибкой EPERM.",
        "theory": "По умолчанию процессы в классических Docker-контейнерах запускаются от имени `root` (UID 0). Даже несмотря на изоляцию пространств имен, `root` внутри контейнера имеет множество опасных прав (например, `CAP_CHOWN`, `CAP_FOWNER`, `CAP_KILL`, `CAP_SETUID`).\n\n### Опасность привилегии `CAP_SYS_ADMIN`:\n`CAP_SYS_ADMIN` — это 'новый root' в Linux: он дает право монтировать файловые системы (`mount`), изменять параметры пространств имен, конфигурировать cgroups, загружать BPF-программы. Более 70% всех известных уязвимостей побега из контейнера (Container Escape) требуют наличия `CAP_SYS_ADMIN`!\n\n### Стратегия Least Privilege в контейнерах:\n1. **Непривилегированный UID/GID:** Никогда не использовать UID 0. Выбирать выделенный UID (например, 10001 / `appuser`).\n2. **Сброс всех прав (`cap-drop: ALL`):** По умолчанию контейнер лишается всех дискретных возможностей ядра.\n3. **Точечное добавление (`cap-add`):** Добавляется только строго необходимая возможность, например, `NET_BIND_SERVICE` для портов < 1024.\n4. **Запрет эскалации (`no-new-privileges: true`):** Блокирует восстановление прав через SUID-файлы.",
        "step_by_step": [
            "Напишите многоэтапный `Dockerfile` (Builder stage на `golang:alpine` + Runner stage на `scratch` или `alpine` с созданием пользователя `appuser`).",
            "Напишите Go-программу, проверяющую текущий UID (`os.Getuid()`).",
            "Реализуйте функцию попытки привилегированной операции (вызов `unix.Mount` без аргументов или фиктивное монтирование).",
            "Убедитесь, что ядро Linux возвращает ошибку `syscall.EPERM` (Operation not permitted).",
            "Продемонстрируйте конфигурацию `docker run --user 10001:10001 --cap-drop=ALL --cap-add=NET_BIND_SERVICE`."
        ],
        "code_blocks": [
            {
                "filename": "Dockerfile",
                "lang": "dockerfile",
                "code": "# Этап 1: Сборка статического бинарника без CGO\nFROM golang:1.23-alpine AS builder\nWORKDIR /app\nCOPY go.mod go.sum* ./\nRUN go mod download || true\nCOPY . .\nRUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags=\"-w -s\" -o server .\n\n# Этап 2: Минималистичный образ с непривилегированным пользователем\nFROM alpine:3.20\n# Создаем группу и пользователя с фиксированным UID 10001\nRUN addgroup -g 10001 -S appgroup && \\\n    adduser -u 10001 -S appuser -G appgroup\n\nWORKDIR /home/appuser\nCOPY --from=builder /app/server /usr/local/bin/server\n\n# Переключение на non-root пользователя\nUSER 10001:10001\n\nEXPOSE 8080\nENTRYPOINT [\"/usr/local/bin/server\"]\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"errors\"\n\t\"fmt\"\n\t\"log\"\n\t\"os\"\n\t\"syscall\"\n)\n\n// TestSysAdminOperation пытается выполнить операцию, требующую CAP_SYS_ADMIN.\nfunc TestSysAdminOperation() {\n\t// Попытка вызова swapon (требует CAP_SYS_ADMIN)\n\terr := syscall.Swapon(\"/dev/null\", 0)\n\tif err != nil {\n\t\tif errors.Is(err, syscall.EPERM) {\n\t\t\tfmt.Println(\"🛡️ [SECURITY SUCCESS] Попытка swapon отклонена: EPERM (Operation not permitted).\")\n\t\t\tfmt.Println(\"   Контейнер защищен: CAP_SYS_ADMIN отсутствует!\")\n\t\t\treturn\n\t\t}\n\t\tfmt.Printf(\"Вызов swapon вернул ошибку: %v\\n\", err)\n\t\treturn\n\t}\n\tlog.Fatalf(\"❌ ОПАСНОСТЬ: swapon выполнился успешно! Процесс обладает CAP_SYS_ADMIN!\")\n}\n\nfunc main() {\n\tuid := os.Getuid()\n\tgid := os.Getgid()\n\tfmt.Printf(\"=== ПРОВЕРКА ПРИВИЛЕГИЙ ПРОЦЕССА ===\\n\")\n\tfmt.Printf(\"UID: %d, GID: %d\\n\", uid, gid)\n\n\tif uid == 0 {\n\t\tfmt.Println(\"⚠️ ВНИМАНИЕ: Процесс запущен от суперпользователя ROOT (UID 0)!\")\n\t} else {\n\t\tfmt.Println(\"✅ Процесс запущен от безопасного непривилегированного пользователя.\")\n\t}\n\n\t// Тестирование отсутствия суперпривилегий\n\tTestSysAdminOperation()\n}\n"
            }
        ],
        "under_the_hood": "В ядре Linux каждое действие, затрагивающее системные ресурсы хоста (монтирование, конфигурация сети, управление памятью ядра), защищено макросом `capable(CAP_SYS_ADMIN)`. Если соответствующий бит в структуре `task_struct->cred->cap_effective` равен 0, ядро немедленно прекращает выполнение сисколла и возвращает код ошибки `-EPERM`. Флаг Docker `--cap-drop=ALL` обнуляет битовые маски `CapInh`, `CapPrm`, `CapEff`, `CapBnd` в момент вызова `execve`.",
        "pitfalls": "Если в Dockerfile указать `USER nonroot`, но не добавить флаг `--security-opt no-new-privileges:true` при запуске контейнера, злоумышленник при наличии бинарников с установленным битом `SUID root` (например, уязвимости в утилите `pkexec` или старых версиях `mount`) может осуществить локальное повышение привилегий обратно до UID 0. Всегда комбинируйте `USER nonroot` с `no-new-privileges`!",
        "bigtech_interview": "Вопрос с собеседования в Wildberries: 'Зачем в Kubernetes использовать Drop: [ALL], если контейнер и так запускается от non-root пользователя UID 10001?' Ответ: 'Пользователь (UID) и возможности ядра (Capabilities) — это ортогональные концепции Linux. Если ядро скомпилировано с поддержкой Ambient Capabilities или процесс наследует capabilities через файловые атрибуты, даже непривилегированный UID может обладать отдельными правами. Директива `drop: [ALL]` гарантирует полное обнуление Capability Bounding Set, делая невозможной активацию любых привилегий ядра.'"
    },
    {
        "num": 16,
        "title": "AppArmor Profile для Go-бинарника: Mandatory Access Control (MAC) vs DAC",
        "task": "Разработайте профиль системы принудительного контроля доступа AppArmor для скомпилированного Go-приложения (/usr/local/bin/go_service). Настройте строгие ограничения: разрешение сетевых потоков TCP (network inet stream), использование capability net_bind_service, доступ только для чтения к конфигурационным файлам (/app/config/** r), доступ на чтение/запись/блокировку к рабочей директории данных (/app/data/** rwk) и явный категорический запрет на запись в системные каталоги (deny /etc/** w, deny /bin/** w). Объясните фундаментальную разницу между DAC (дискреционный контроль доступа) и MAC (мандатный контроль доступа).",
        "theory": "В стандартной модели безопасности Linux долгое время доминировал механизм **DAC (Discretionary Access Control — Дискреционный контроль доступа)**:\n- Права доступа привязаны к владельцу файла (пользователь, группа, остальные — `rwxrwxrwx`).\n- Пользователь `root` обладает абсолютной властью и может игнорировать любые DAC-права.\n- Если сервис запущен от пользователя `app`, и сервис взломан, злоумышленник может прочитать **любой** файл в системе, доступный пользователю `app` (или всем пользователям в мире, например `/tmp` или `/etc/hosts`).\n\n### Революция MAC (Mandatory Access Control — Мандатный контроль доступа):\n**AppArmor** — это LSM-модуль ядра Linux (Linux Security Module), реализующий мандатный контроль доступа.\n- Правила применяются **к самой программе (к пути исполняемого файла)**, а не к пользователю!\n- Даже если процесс запущен от суперпользователя `root` (UID 0), ядро Linux не позволит ему прочитать или записать файл, если этот путь не разрешен в профиле AppArmor!\n- AppArmor действует на уровне виртуальной файловой системы VFS ядра, перехватывая вызовы до реального обращения к драйверу диска или сети.",
        "step_by_step": [
            "Напишите профиль AppArmor `usr.local.bin.go_service`.",
            "Объявите флаги профиля `flags=(attach_disconnected, enforce)`.",
            "Включите стандартные абстракции (`#include <abstractions/base>`, `#include <abstractions/nameservice>`).",
            "Настройте сетевые правила (`network inet stream`, `network inet6 stream`).",
            "Настройте файловые правила: чтение конфига, чтение/запись данных, запрет системных папок.",
            "Продемонстрируйте загрузку профиля утилитой `apparmor_parser -r -W /etc/apparmor.d/usr.local.bin.go_service`.",
            "Напишите Go-код, проверяющий попытку несанкционированной записи в `/etc/malware.txt`."
        ],
        "code_blocks": [
            {
                "filename": "usr.local.bin.go_service",
                "lang": "bash",
                "code": "# Профиль AppArmor для промышленного Go-микросервиса\n#include <tunables/global>\n\n/usr/local/bin/go_service flags=(attach_disconnected, enforce) {\n  # Базовые абстракции ядра (системные библиотеки, зоны времени)\n  #include <abstractions/base>\n  #include <abstractions/nameservice>\n\n  # Сетевой стек: разрешаем IPv4/IPv6 TCP-сокеты\n  network inet stream,\n  network inet6 stream,\n\n  # Разрешенные Linux Capabilities\n  capability net_bind_service,\n\n  # Доступ к бинарнику (только чтение и исполнение)\n  /usr/local/bin/go_service mr,\n\n  # Директория конфигурации: ТОЛЬКО ЧТЕНИЕ\n  /app/config/ r,\n  /app/config/** r,\n\n  # Директория данных и временных файлов: чтение, запись, создание, блокировка (rwk)\n  /app/data/ rw,\n  /app/data/** rwk,\n  /tmp/ rw,\n  /tmp/** rwk,\n\n  # Категорический запрет (Deny rules переопределяют любые allow rules)\n  deny /etc/** w,\n  deny /bin/** w,\n  deny /usr/** w,\n  deny /root/** rwklx,\n}\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"log\"\n\t\"net/http\"\n\t\"os\"\n)\n\nfunc main() {\n\tfmt.Println(\"=== СТАРТ GO-СЕРВИСА ПОД ЗАЩИТОЙ APPARMOR ===\")\n\n\t// 1. Легитимное действие: чтение файла конфигурации\n\tcfgPath := \"/app/config/app.env\"\n\tif data, err := os.ReadFile(cfgPath); err == nil {\n\t\tfmt.Printf(\"Конфигурация успешно загружена: %s\\n\", string(data))\n\t} else {\n\t\tfmt.Printf(\"Конфигурация отсутствует (норма для теста): %v\\n\", err)\n\t}\n\n\t// 2. Нелегитимное действие: симуляция эксплойта, пытающегося записать файл в /etc\n\tfmt.Println(\"Попытка несанкционированной записи в /etc/malicious.conf...\")\n\terr := os.WriteFile(\"/etc/malicious.conf\", []byte(\"hacked=true\"), 0644)\n\tif err != nil {\n\t\tfmt.Printf(\"🛡️ [APPARMOR INTERCEPT] Запись заблокирована ядром Linux: %v\\n\", err)\n\t\tfmt.Println(\"   Событие зафиксировано в /var/log/audit/audit.log (apparmor='DENIED')\")\n\t} else {\n\t\tlog.Fatalf(\"❌ ОШИБКА: Запись в /etc удалась! AppArmor не активен.\")\n\t}\n\n\t// 3. Запуск сетевого сервера (разрешено правилом network inet stream)\n\thttp.HandleFunc(\"/healthz\", func(w http.ResponseWriter, r *http.Request) {\n\t\tw.WriteHeader(http.StatusOK)\n\t\tw.Write([]byte(\"OK\"))\n\t})\n\tlog.Println(\"Сервер слушает на :8080...\")\n\t_ = http.ListenAndServe(\":8080\", nil)\n}\n"
            }
        ],
        "under_the_hood": "AppArmor является LSM-модулем ядра. При открытии файла хук `apparmor_file_open()` в ядре обращается к профилю текущего процесса (`task_struct->security`). Путь к файлу нормализуется относительно корня файловой системы и сопоставляется с детерминированным конечным автоматом (DFA — Deterministic Finite Automaton) профиля. Если найдено правило `deny` или путь отсутствует среди разрешенных, ядро немедленно возвращает ошибку `-EACCES` без обращения к диску.",
        "pitfalls": "AppArmor разрешает пути на основе **строковых имен файлов (Path-based MAC)**, в отличие от SELinux, использующего индексные дескрипторы inode и метки безопасности (Labels). Это порождает уязвимости при использовании жестких ссылок (Hardlinks) или переименовании каталогов. Также убедитесь, что в Docker или Kubernetes хост-ноды поддерживают AppArmor (демон `apparmor.service` активен в `systemctl status apparmor`).",
        "bigtech_interview": "Вопрос с собеседования в Яндекс: 'В чем разница между режимами AppArmor Complain и Enforce?' Ответ: 'В режиме `complain` (режим обучения/аудита) AppArmor фиксирует все нарушения правил профиля в лог аудита (`dmesg`/`auditd`), но **не блокирует** сами операции. Этот режим используется для профилирования нового микросервиса на staging. В режиме `enforce` (режим защиты) ядро жестко блокирует любые несанкционированные системные вызовы с ошибкой EACCES.'"
    },
    {
        "num": 17,
        "title": "Изоляция Файловой Системы (Chroot): Создание легковесной тюрьмы и ограничения chroot vs pivot_root",
        "task": "Реализуйте на Go создание изолированного файлового окружения ('тюрьмы') с помощью системного вызова unix.Chroot. Сформируйте минималистичное изолированное дерево каталогов (/var/www/jail), переместите процесс внутрь через unix.Chdir('/') и unix.Chroot. Продемонстрируйте попытку чтения файла /etc/passwd и убедитесь, что процесс физически не видит файлы за пределами своей 'тюрьмы'. Разберите фундаментальные ограничения безопасности chroot и объясните, почему в production-контейнеризации (Docker/runc) вместо chroot используется pivot_root в связке с Mount Namespaces.",
        "theory": "Системный вызов **`chroot` (Change Root)** появился еще в Version 7 Unix в 1979 году и стал исторически первой технологией изоляции процессов.\n\n### Механика `chroot()`:\nПри вызове `chroot(path)` ядро изменяет указатель корневого каталога процесса (`current->fs->root`) на новую директорию.\n- Для этого процесса путь `/` теперь указывает на заданную папку (например, `/var/jail`).\n- Любые абсолютные пути резолвятся относительно новой вершины дерева каталогов.\n- Попытка открыть `/etc/passwd` приведет к открытию `/var/jail/etc/passwd`, а не настоящего системного файла хоста!\n\n### Почему `chroot` НЕ является безопасной песочницей (Security Boundary):\n`chroot` сам по себе **не создает барьера безопасности** для привилегированного процесса:\n1. **Побег через дескрипторы (File Descriptor Escape):** Если у процесса до вызова `chroot` остался открыт дескриптор директории за пределами тюрьмы, вызов `fchdir(fd)` и цикл `chdir('..')` мгновенно выводят процесс обратно в реальный корень хоста!\n2. **Создание вложенного chroot:** Процесс с правами `CAP_SYS_CHROOT` может создать временную директорию, вызвать `chroot('subdir')`, затем `chdir('../../../..')` и вернуть себе доступ ко всему диску.\n3. **Общее пространство имен:** Сеть, PID процессов, IPC, память и монтирования остаются общими с хостом.\n\n### Промышленный стандарт: `pivot_root` + `CLONE_NEWNS`:\nВ современных контейнерах (runc, Docker, containerd) используется связка:\n1. Создание нового пространства имен монтирования (**Mount Namespace** через `clone(CLONE_NEWNS)`).\n2. Вызов **`pivot_root(new_root, put_old)`**, который атомарно подменяет точку монтирования корня всей VFS.\n3. Размонтирование и уничтожение старого корня через `umount2(put_old, MNT_DETACH)`. Побег из такого окружения через дескрипторы математически и физически невозможен!",
        "step_by_step": [
            "Создайте временную изолированную директорию через `os.MkdirTemp`.",
            "Создайте внутри изолированное дерево каталогов (например, `app/data`).",
            "Выполните вызов `unix.Chdir(jailDir)`.",
            "Вызовите системный вызов `unix.Chroot(jailDir)` (требуются права root или `CAP_SYS_CHROOT`).",
            "Снова вызовите `unix.Chdir('/')` (обязательное требование стандарта POSIX для сброса рабочего каталога).",
            "Попробуйте прочитать `/etc/passwd` и зафиксируйте ошибку `os.ErrNotExist`.",
            "Продемонстрируйте безопасное создание файлов внутри изолированного пространства."
        ],
        "code_blocks": [
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"errors\"\n\t\"fmt\"\n\t\"log\"\n\t\"os\"\n\t\"path/filepath\"\n\n\t\"golang.org/x/sys/unix\"\n)\n\n// EnterChrootJail изолирует текущий процесс в указанной директории.\nfunc EnterChrootJail(jailPath string) error {\n\t// 1. Проверяем существование директории\n\tif _, err := os.Stat(jailPath); err != nil {\n\t\treturn fmt.Errorf(\"stat jailPath error: %w\", err)\n\t}\n\n\t// 2. Переходим в целевую директорию\n\tif err := unix.Chdir(jailPath); err != nil {\n\t\treturn fmt.Errorf(\"chdir to jailPath error: %w\", err)\n\t}\n\n\t// 3. Вызываем системный вызов chroot\n\tif err := unix.Chroot(jailPath); err != nil {\n\t\treturn fmt.Errorf(\"chroot failed (требуется root / CAP_SYS_CHROOT): %w\", err)\n\t}\n\n\t// 4. КРИТИЧЕСКИ ВАЖНО: сбросить текущую директорию в новый корень \"/\"\n\t// Без этого текущий рабочий каталог останется старым, позволяя побег!\n\tif err := unix.Chdir(\"/\"); err != nil {\n\t\treturn fmt.Errorf(\"chdir to new root error: %w\", err)\n\t}\n\n\treturn nil\n}\n\nfunc main() {\n\tfmt.Println(\"=== ИЗОЛЯЦИЯ ФАЙЛОВОЙ СИСТЕМЫ ЧЕРЕЗ CHROOT ===\")\n\n\t// Создаем изолированное тестовое дерево каталогов\n\tjailDir, err := os.MkdirTemp(\"\", \"go_chroot_jail_*\")\n\tif err != nil {\n\t\tlog.Fatalf(\"Ошибка создания jail dir: %v\", err)\n\t}\n\tdefer os.RemoveAll(jailDir)\n\n\t// Создаем фиктивный файл внутри тюрьмы\n\tinternalDataDir := filepath.Join(jailDir, \"app\")\n\t_ = os.MkdirAll(internalDataDir, 0755)\n\t_ = os.WriteFile(filepath.Join(internalDataDir, \"secret.txt\"), []byte(\"jail data\"), 0644)\n\n\tfmt.Printf(\"1. Изолированная директория подготовлена: %s\\n\", jailDir)\n\n\t// Попытка войти в тюрьму (требует CAP_SYS_CHROOT)\n\tif err := EnterChrootJail(jailDir); err != nil {\n\t\tlog.Printf(\"⚠️ Не удалось применить chroot: %v\\n\"+\n\t\t\t\"Подсказка: запустите с правами root или в привилегированном контейнере.\", err)\n\t\treturn\n\t}\n\tfmt.Println(\"🛡️ Процесс успешно изолирован в chroot-тюрьме!\")\n\n\t// Попытка прочитать системный /etc/passwd хоста\n\tfmt.Println(\"2. Попытка прочитать /etc/passwd хоста изнутри тюрьмы...\")\n\t_, err = os.ReadFile(\"/etc/passwd\")\n\tif err != nil {\n\t\tif errors.Is(err, os.ErrNotExist) {\n\t\t\tfmt.Println(\"✅ [SUCCESS] Файл /etc/passwd не найден: процесс физически не видит хостовые файлы!\")\n\t\t} else {\n\t\t\tfmt.Printf(\"Ошибка чтения: %v\\n\", err)\n\t\t}\n\t} else {\n\t\tlog.Fatalf(\"❌ ПРОВАЛ: /etc/passwd прочитан! Chroot не изолирован.\")\n\t}\n\n\t// Проверяем доступность локального файла\n\tdata, err := os.ReadFile(\"/app/secret.txt\")\n\tif err == nil {\n\t\tfmt.Printf(\"3. Локальный файл /app/secret.txt успешно прочитан: '%s'\\n\", string(data))\n\t}\n}\n"
            }
        ],
        "under_the_hood": "Структура `fs_struct` каждого потока в ядре содержит два ключевых указателя на структуры `struct path`: `root` и `pwd`. Системный вызов `sys_chroot()` перезаписывает указатель `root`. Алгоритм резолвинга путей в ядре Linux (`follow_dotdot()` в `fs/namei.c`) проверяет: если текущий dentry равен `current->fs->root`, то переход `..` вверх просто возвращает текущий же dentry, не позволяя подняться выше корня.",
        "pitfalls": "Если перед вызовом `unix.Chroot()` процесс не вызовет `unix.Chdir('/')`, его указатель `pwd` останется снаружи нового корня! Злоумышленник сможет вызвать `open('../../../etc/shadow')` и прочитать файлы хоста. Всегда выполняйте `chdir('/')` немедленно после любого вызова `chroot()`.",
        "bigtech_interview": "Вопрос с собеседования в VK Cloud: 'Почему в рантайме runc для Docker используется pivot_root, а не chroot?' Ответ: 'В классическом chroot ядро сохраняет старую файловую систему смонтированной в том же пространстве имен. Имея root внутри контейнера, злоумышленник может открыть дескриптор файла до chroot и выполнить побег через fchdir. Системный вызов `pivot_root` в связке с Mount Namespace физически перемещает старую корневую файловую систему в отдельную подпапку, которая затем полностью размонтируется через `umount2(put_old, MNT_DETACH)`. В таблице монтирований ядра старый корень хоста перестает существовать для контейнера.'"
    },
    {
        "num": 18,
        "title": "Linux Capabilities: Тонкое управление через capset, PR_CAP_AMBIENT и сброс ALL",
        "task": "Напишите Go-программу для низкоуровневого управления Linux Capabilities с использованием библиотеки golang.org/x/sys/unix. Продемонстрируйте механизм полного сброса наследуемых привилегий через prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_CLEAR_ALL, 0, 0, 0) и системный вызов capset. Оставьте только строго необходимую capability (CAP_NET_BIND_SERVICE). Объясните разницу между 5 наборами возможностей процесса в ядре Linux: Effective, Permitted, Inheritable, Bounding и Ambient, и разберите, почему для портов > 1024 capabilities не требуются вообще.",
        "theory": "В ядре Linux права каждого процесса разделены на **5 независимых 64-битных битовых масок (Capability Sets)**:\n\n### 5 наборов Linux Capabilities:\n1. **`Permitted` (Разрешенные):** Верхний предел возможностей, которые поток имеет право активировать.\n2. **`Effective` (Эффективные):** Битовая маска, которую ядро проверяет в реальном времени при выполнении привилегированного системного вызова (например, `CAP_NET_BIND_SERVICE` для `bind`).\n3. **`Inheritable` (Наследуемые через execve):** Возможности, сохраняющиеся при вызове `execve` обычного непривилегированного бинарника.\n4. **`Bounding` (Ограничивающий набор / CapBnd):** Системный фильтр ядра: процесс не может получить capability, отсутствующую в CapBnd, даже через setuid-бинарники.\n5. **`Ambient` (Окружающие / CapAmb, добавлены в Linux 4.3):** Возможности, которые **автоматически наследуются** непривилегированными дочерними процессами при вызове `execve` без необходимости установки SUID-битов или файловых атрибутов `setcap`.\n\n### Зачем сбрасывать `ALL`:\nЕсли веб-сервер слушает порт 8080 (непривилегированный порт > 1023), ему **вообще не нужны никакие capabilities**. Запуск со сбросом всех привилегий (`cap-drop: ALL`) гарантирует, что атакующий даже при получении контроля над памятью не сможет изменить сетевые маршруты (`CAP_NET_ADMIN`), перехватить трафик сырыми сокетами (`CAP_NET_RAW`) или изменить системное время (`CAP_SYS_TIME`).",
        "step_by_step": [
            "Импортируйте пакет `golang.org/x/sys/unix`.",
            "Объявите структуры управления `unix.CapUserHeader` и `unix.CapUserData`.",
            "Очистите окружающие возможности через `unix.Prctl(unix.PR_CAP_AMBIENT, unix.PR_CAP_AMBIENT_CLEAR_ALL, 0, 0, 0)`.",
            "Сформируйте битовую маску: оставьте только бит `1 << unix.CAP_NET_BIND_SERVICE` в `Permitted` и `Effective`.",
            "Примените изменения через `unix.Capset(&hdr, &data[0])`.",
            "Проверьте статус процесса и выведите информативное сообщение о текущих правах."
        ],
        "code_blocks": [
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"log\"\n\t\"os\"\n\n\t\"golang.org/x/sys/unix\"\n)\n\n// RetainOnlyNetBindService сбрасывает все capabilities, оставляя только CAP_NET_BIND_SERVICE.\nfunc RetainOnlyNetBindService() error {\n\t// 1. Очищаем Ambient Capabilities (чтобы дочерние процессы не наследовали лишнего)\n\tif err := unix.Prctl(unix.PR_CAP_AMBIENT, unix.PR_CAP_AMBIENT_CLEAR_ALL, 0, 0, 0); err != nil {\n\t\t// Ошибка может возникнуть на старых ядрах (< 4.3) или при отсутствии прав\n\t\tlog.Printf(\"[WARN] prctl(PR_CAP_AMBIENT_CLEAR_ALL): %v\", err)\n\t}\n\n\t// 2. Инициализация структур capset для 64-битных capabilities (Linux v3)\n\thdr := unix.CapUserHeader{\n\t\tVersion: unix.LINUX_CAPABILITY_VERSION_3,\n\t\tPid:     0, // 0 означает текущий процесс\n\t}\n\tvar data [2]unix.CapUserData\n\n\t// Считываем текущие capabilities\n\tif err := unix.Capget(&hdr, &data[0]); err != nil {\n\t\treturn fmt.Errorf(\"capget failed: %w\", err)\n\t}\n\n\tlog.Printf(\"[CAPS ДО] Permitted: 0x%x:0x%x, Effective: 0x%x:0x%x\",\n\t\tdata[1].Permitted, data[0].Permitted, data[1].Effective, data[0].Effective)\n\n\t// 3. Формируем минимальную битовую маску: ТОЛЬКО CAP_NET_BIND_SERVICE (бит 10)\n\tcapMask := uint32(1 << unix.CAP_NET_BIND_SERVICE)\n\n\t// Оставляем бит только если он уже был разрешен в Permitted\n\tnewPermitted := data[0].Permitted & capMask\n\tnewEffective := data[0].Effective & capMask\n\n\tdata[0].Effective = newEffective\n\tdata[0].Permitted = newPermitted\n\tdata[0].Inheritable = 0\n\n\tdata[1].Effective = 0\n\tdata[1].Permitted = 0\n\tdata[1].Inheritable = 0\n\n\t// 4. Применяем минимальный набор capabilities к текущему процессу\n\tif err := unix.Capset(&hdr, &data[0]); err != nil {\n\t\treturn fmt.Errorf(\"capset failed: %w\", err)\n\t}\n\n\tlog.Printf(\"[CAPS ПОСЛЕ] Permitted: 0x%x:0x%x, Effective: 0x%x:0x%x\",\n\t\tdata[1].Permitted, data[0].Permitted, data[1].Effective, data[0].Effective)\n\treturn nil\n}\n\nfunc main() {\n\tfmt.Printf(\"=== НИЗКОУРОВНЕВОЕ УПРАВЛЕНИЕ LINUX CAPABILITIES (PID: %d) ===\\n\", os.Getpid())\n\n\tif err := RetainOnlyNetBindService(); err != nil {\n\t\tlog.Printf(\"Не удалось применить capset: %v\\n\"+\n\t\t\t\"(Для изменения capabilities требуются соответствующие права или root)\", err)\n\t\treturn\n\t}\n\n\tfmt.Println(\"✅ [SUCCESS] Все избыточные capabilities сброшены!\")\n\tfmt.Println(\"   Сохранен исключительно бит CAP_NET_BIND_SERVICE.\")\n}\n"
            }
        ],
        "under_the_hood": "В ядре Linux вызов `sys_capset` обновляет поля `task_struct->cred->cap_effective`, `cap_permitted`, `cap_inheritable`. Если процесс уменьшает набор возможностей (`subset`), ядро разрешает операцию любому процессу без дополнительных привилегий. Однако вернуть сброшенные биты назад невозможно: попытка установить в `Permitted` бит, отсутствовавший в предыдущем значении маски, немедленно блокируется ядром с кодом `-EPERM`.",
        "pitfalls": "Capabilities в Linux 64-битные, но структуры `CapUserData` разбиты на два 32-битных элемента (`data[0]` для capabilities 0–31, `data[1]` для capabilities 32–63). При ручной манипуляции с битовыми масками легко забыть обнулить `data[1]`, оставив активными высокоуровневые возможности (например, `CAP_BLOCK_SUSPEND`, `CAP_AUDIT_READ`, `CAP_BPF`), что нарушит модель Zero Trust.",
        "bigtech_interview": "Вопрос с собеседования в Ozon: 'Чем опасна Linux Capability CAP_NET_RAW в продакшн-контейнерах?' Ответ: '`CAP_NET_RAW` дает процессу право открывать сырые сокеты (`AF_PACKET`, `SOCK_RAW`), генерировать произвольные пакеты с поддельными IP/MAC-адресами (ARP Spoofing, IP Spoofing) и перехватывать чужой сетевой трафик внутри общего сетевого неймспейса или оверлейной сети Kubernetes (packet sniffing). Запрет `CAP_NET_RAW` исключает возможность прослушивания трафика соседних подов.'"
    },
    {
        "num": 19,
        "title": "AppArmor профиль для Go-сервиса: Изоляция конфигурации в Enforce Mode",
        "task": "Создайте минималистичный и надежный профиль AppArmor для Go-сервиса, жестко ограничивающий доступ к файловой системе: разрешено только чтение файла конфигурации (/etc/app/config.yaml) и запись в лог-файл (/var/log/app.log). Загрузите профиль в ядро Linux в боевом режиме (Enforce Mode) и продемонстрируйте попытку приложения прочитать непредусмотренный файл (например, /etc/shadow или приватные SSH-ключи), убедившись в получении ошибки Permission denied.",
        "theory": "Развертывание Go-сервисов в среде с включенным профилем AppArmor в режиме **Enforce Mode** формирует второй непробиваемый эшелон обороны (Defense-in-Depth).\n\n### Сценарий атаки Path Traversal / Arbitrary File Read:\nПредставьте уязвимость в HTTP-обработчике отдачи статических файлов:\n```go\nhttp.HandleFunc(\"/static/\", func(w http.ResponseWriter, r *http.Request) {\n    path := r.URL.Query().Get(\"file\")\n    http.ServeFile(w, r, path) // Уязвимо к: ?file=../../../../etc/shadow\n})\n```\nЕсли сервис запущен без AppArmor от пользователя `app`, а файл `/etc/shadow` случайно имеет права чтения для всех, либо злоумышленник запрашивает `/home/app/.ssh/id_rsa` — происходит утечка критических секретов.\n\n### Действие AppArmor в Enforce Mode:\nПрофиль AppArmor жестко фиксирует:\n- Разрешено чтение: строго `/etc/app/config.yaml r`.\n- Любой другой путь в каталоге `/etc/` или домашних папках **отсутствует в белом списке**.\n- При попытке `openat('/etc/shadow')` LSM-модуль AppArmor в ядре отклоняет вызов с ошибкой `EACCES (Permission denied)`, а в системный лог отправляется алерт `apparmor='DENIED' operation='open'`. Уязвимость в коде становится абсолютно безвредной!",
        "step_by_step": [
            "Напишите профиль AppArmor `apparmor-go-service`.",
            "Настройте чтение бинарника `/usr/bin/my_service mr`.",
            "Укажите точечные правила: `/etc/app/config.yaml r`, `/var/log/app.log rw`.",
            "Скомпилируйте Go-сервис, выполняющий попытку чтения конфигурации и попытку нелегитимного чтения `/etc/shadow`.",
            "Продемонстрируйте команды загрузки: `sudo apparmor_parser -r -W apparmor-go-service`.",
            "Проверьте статус через `sudo aa-status`."
        ],
        "code_blocks": [
            {
                "filename": "apparmor-go-service",
                "lang": "bash",
                "code": "# /etc/apparmor.d/my_service\n#include <tunables/global>\n\n/usr/bin/my_service flags=(attach_disconnected, enforce) {\n  #include <abstractions/base>\n\n  # Исполнение самого бинарника\n  /usr/bin/my_service mr,\n\n  # Сетевые операции (исходящие и входящие)\n  network inet stream,\n  network inet6 stream,\n\n  # Разрешен ТОЛЬКО конкретный файл конфигурации\n  /etc/app/config.yaml r,\n\n  # Разрешена запись ТОЛЬКО в файл логов\n  /var/log/app.log rw,\n\n  # Все остальные файлы хоста запрещены по умолчанию!\n}\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"log\"\n\t\"os\"\n)\n\nfunc main() {\n\tfmt.Println(\"=== ТЕСТ ИЗОЛЯЦИИ ФАЙЛОВОЙ СИСТЕМЫ ПОД APPARMOR ENFORCE ===\")\n\n\t// 1. Попытка легитимного чтения разрешенного конфига\n\tcfgFile := \"/etc/app/config.yaml\"\n\tif data, err := os.ReadFile(cfgFile); err == nil {\n\t\tfmt.Printf(\"✅ Конфигурация успешно прочитана (%d байт)\\n\", len(data))\n\t} else {\n\t\tfmt.Printf(\"Инфо: Конфиг не найден на диске (ожидаемо в тесте): %v\\n\", err)\n\t}\n\n\t// 2. Попытка несанкционированного чтения закрытого системного файла\n\tforbiddenFile := \"/etc/shadow\"\n\tfmt.Printf(\"Попытка несанкционированного чтения %s...\\n\", forbiddenFile)\n\t_, err := os.ReadFile(forbiddenFile)\n\tif err != nil {\n\t\tif os.IsPermission(err) {\n\t\t\tfmt.Printf(\"🛡️ [УСПЕХ БЕЗОПАСНОСТИ] Ядро заблокировало чтение: %v (Permission Denied)\\n\", err)\n\t\t\tfmt.Println(\"   AppArmor в режиме Enforce защитил конфиденциальные данные хоста!\")\n\t\t} else {\n\t\t\tfmt.Printf(\"Файл недоступен: %v\\n\", err)\n\t\t}\n\t} else {\n\t\tlog.Fatalf(\"❌ КРИТИЧЕСКИЙ ПРОВАЛ: Файл %s прочитан! Профиль AppArmor не работает.\", forbiddenFile)\n\t}\n}\n"
            }
        ],
        "under_the_hood": "Утилита `apparmor_parser` преобразует текстовый профиль в бинарный граф правил (скомпилированный DFA) и загружает его в ядро через псевдофайл `/sys/kernel/security/apparmor/.load`. При вызове `execve('/usr/bin/my_service')` ядро связывает текущую задачу `task_struct` с загруженным профилем безопасности. В ядре перехватчик `vfs_open()` проверяет соответствие запрашиваемого файла графу разрешенных путей.",
        "pitfalls": "Если ваш Go-сервис использует сборщик мусора или профилировщик pprof, он может попытаться открыть `/proc/self/cmdline` или `/proc/sys/net/core/somaxconn`. Если в профиле AppArmor не подключена абстракция `#include <abstractions/base>`, чтение псевдофайловой системы procfs будет заблокировано, что вызовет панику стандартной библиотеки. Всегда включайте `<abstractions/base>` в профили Go.",
        "bigtech_interview": "Вопрос с собеседования в Касперский: 'Как отладить профиль AppArmor, если сервис падает в Enforce-режиме, но при выключенном профиле работает стабильно?' Ответ: '1) Перевести профиль во временный режим обучения: `sudo aa-complain /usr/bin/my_service`. 2) Запустить сервис и сымитировать стандартные сценарии нагрузки. 3) Использовать утилиту `aa-logprof` для интерактивного анализа логов аудита: она покажет все заблокированные пути и предложит внести их в белый список. 4) После обновления правил вернуть режим `sudo aa-enforce /usr/bin/my_service`.'"
    },
    {
        "num": 20,
        "title": "Защита Docker-образа через Read-Only Filesystem (--read-only)",
        "task": "Напишите Go-сервис и конфигурацию Docker-контейнера с флагом --read-only. Покажите, как правильно организовать архитектуру приложения (логирование строго в stdout/stderr, использование tmpfs для временных файлов, хранение состояния в БД или объектном хранилище), чтобы сервис стабильно работал в неизменяемой файловой системе. Продемонстрируйте попытку записи файла на диск и убедитесь в получении системной ошибки Read-only file system (EROFS), блокирующей до 90% автоматизированных эксплойтов.",
        "theory": "Подавляющее большинство автоматизированных эксплойтов и ботнетов (Mirai, Kinsing криптомайнеры) действуют по жесткому шаблону:\n1. Эксплуатация RCE уязвимости в веб-приложении.\n2. Сохранение вредоносного скрипта или ELF-бинарника во временную директорию (обычно `/tmp`, `/dev/shm` или `/var/tmp`).\n3. Установка прав на исполнение: `chmod +x /tmp/miner`.\n4. Запуск вредоносного процесса: `/tmp/miner`.\n\n### Принцип неизменяемой инфраструктуры (Read-Only Root Filesystem):\nФлаг Docker `--read-only` (или в Kubernetes `readOnlyRootFilesystem: true`):\n- Монтирует корневую файловую систему контейнера с флагом ядра **`MS_RDONLY`**.\n- Любая операция создания, модификации или удаления файлов (`open(O_WRONLY|O_CREAT)`, `unlink`, `chmod`) немедленно прерывается ядром с ошибкой **`EROFS (errno 30: Read-only file system)`**.\n- Вредоносное ПО **физически не может записать себя на диск**!\n- Если сервису жизненно необходимы временные файлы, они выносятся в память через `tmpfs` с обязательными флагами безопасности `noexec,nosuid,nodev`.",
        "step_by_step": [
            "Напишите Go HTTP-сервис, пишущий структурированные логи исключительно в `os.Stdout`.",
            "Реализуйте функцию проверки возможности записи на диск (попытка создать файл в `/app/test.txt`).",
            "Обработайте системную ошибку `syscall.EROFS`.",
            "Сформируйте манифест `docker-compose.yml` с параметрами `read_only: true` и безопасным `tmpfs: /tmp:rw,noexec,nosuid,size=32m`.",
            "Проверьте, что сервер успешно обрабатывает входящие HTTP-запросы в режиме `read-only`."
        ],
        "code_blocks": [
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"errors\"\n\t\"fmt\"\n\t\"log\"\n\t\"net/http\"\n\t\"os\"\n\t\"syscall\"\n\t\"time\"\n)\n\n// AttemptDiskWrite проверяет статус монтирования файловой системы.\nfunc AttemptDiskWrite(path string) {\n\terr := os.WriteFile(path, []byte(\"payload\"), 0644)\n\tif err != nil {\n\t\tvar pathErr *os.PathError\n\t\tif errors.As(err, &pathErr) && errors.Is(pathErr.Err, syscall.EROFS) {\n\t\t\tlog.Printf(\"🛡️ [SECURITY ACTIVE] Файловая система смонтирована строго READ-ONLY!\\n\"+\n\t\t\t\t\"   Попытка записи в '%s' отклонена ядром: %v (EROFS)\", path, err)\n\t\t\treturn\n\t\t}\n\t\tlog.Printf(\"Ошибка записи в %s: %v\", path, err)\n\t\treturn\n\t}\n\tlog.Printf(\"⚠️ ВНИМАНИЕ: Файл '%s' успешно записан на диск! ФС доступна на запись.\", path)\n}\n\nfunc main() {\n\t// Настройка логов строго в stdout (не на диск!)\n\tlog.SetOutput(os.Stdout)\n\tlog.Println(\"=== СТАРТ СЕРВИСА В РЕЖИМЕ READ-ONLY ROOT FS ===\")\n\n\t// Тестирование неизменяемости корневой файловой системы\n\tAttemptDiskWrite(\"/test_exploit.bin\")\n\n\t// Тестирование записи в безопасный tmpfs (если смонтирован)\n\ttmpPath := \"/tmp/legitimate_temp.dat\"\n\tif err := os.WriteFile(tmpPath, []byte(\"temp cache\"), 0600); err == nil {\n\t\tlog.Printf(\"✅ Временный файл в памяти tmpfs успешно создан: %s\", tmpPath)\n\t\t_ = os.Remove(tmpPath)\n\t}\n\n\tmux := http.NewServeMux()\n\tmux.HandleFunc(\"/healthz\", func(w http.ResponseWriter, r *http.Request) {\n\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n\t\tfmt.Fprintf(w, `{\"status\":\"ok\",\"timestamp\":\"%s\",\"readonly\":true}`,\n\t\t\ttime.Now().Format(time.RFC3339))\n\t})\n\n\tsrv := &http.Server{\n\t\tAddr:         \":8080\",\n\t\tHandler:      mux,\n\t\tReadTimeout:  3 * time.Second,\n\t\tWriteTimeout: 3 * time.Second,\n\t}\n\n\tlog.Println(\"Сервер слушает на порту :8080...\")\n\tif err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {\n\t\tlog.Fatalf(\"Ошибка сервера: %v\", err)\n\t}\n}\n"
            },
            {
                "filename": "docker-compose.yml",
                "lang": "yaml",
                "code": "version: '3.8'\n\nservices:\n  secure-web:\n    build: .\n    ports:\n      - \"8080:8080\"\n    # Монтирование корневой ФС строго в режиме Read-Only\n    read_only: true\n    # Временная память в RAM с запретом исполнения бинарников (noexec)\n    tmpfs:\n      - /tmp:rw,noexec,nosuid,nodev,size=32m\n    security_opt:\n      - no-new-privileges:true\n    cap_drop:\n      - ALL\n"
            }
        ],
        "under_the_hood": "Флаг `MS_RDONLY` устанавливается в структуре суперблока точки монтирования VFS (`struct vfsmount`). При попытке любого системного вызова модификации (`open(O_CREAT)`, `truncate`, `rename`, `unlink`) ядро в функции `mnt_want_write()` проверяет флаг `MNT_READONLY`. Если флаг активен, операция немедленно обрывается с возвратом отрицательного кода ошибки `-EROFS` без передачи запроса драйверу файловой системы (ext4/overlay2).",
        "pitfalls": "Многие популярные сторонние библиотеки Go (например, кэширующие парсеры шаблонов или генераторы PDF) неявно пытаются создать временный файл в `os.TempDir()`. Если контейнер запущен с `--read-only`, но без смонтированного раздела `tmpfs` в директорию `/tmp`, такие библиотеки упадут с паникой прямо в продакшне при первом запросе. Всегда монтируйте `/tmp:rw,noexec,size=64m` в RAM!",
        "bigtech_interview": "Вопрос с собеседования в Т-Банк: 'Почему флаг noexec в монтировании tmpfs является критически важным дополнением к readOnlyRootFilesystem?' Ответ: 'Если контейнер запущен с read-only корнем, злоумышленник не может записать майнер в `/bin` или `/app`, но он может записать его в разрешенную для записи временную папку `/tmp`. Если папка `/tmp` смонтирована без флага `noexec`, атакующий сможет вызвать `chmod +x /tmp/payload && /tmp/payload`. Опция `noexec` запрещает ядру выполнять системный вызов `execve` для любых файлов, находящихся на этой точке монтирования, делая запуск вредоносного бинарника из `/tmp` невозможным.'"
    },
    {
        "num": 21,
        "title": "Network Namespaces + cgroup v2: Изоляция сети и защита от Fork-бомб и Memory Exhaustion",
        "task": "Изучите механизмы ядра Linux, лежащие в основе контейнеризации. Напишите подробное руководство и Go-утилиту, демонстрирующую запуск процесса в изолированном сетевом пространстве имен (Network Namespace) и ограничение его ресурсов через современную иерархию контрольных групп cgroup v2. Настройте жесткие лимиты: память (memory.max = 100MB), процессорное время (cpu.max) и максимальное количество потоков (pids.max = 50). Объясните, как pids.max гарантированно нейтрализует атаки типа Fork Bomb, а memory.max предотвращает деградацию соседних сервисов на хосте.",
        "theory": "Контейнеры Docker и поды Kubernetes — это не магия, а комбинация двух фундаментальных механизмов ядра Linux:\n1. **Namespaces (Пространства имен):** Изолируют **видимость** ресурсов (сеть `net`, процессы `pid`, точки монтирования `mnt`, IPC, хостнейм `uts`, пользователи `user`).\n2. **Control Groups (cgroups):** Ограничивают **потребление** системных ресурсов (память, CPU, ввод-вывод I/O, число процессов PIDs).\n\n### Архитектура cgroup v2 (Unified Hierarchy):\nВ отличие от устаревшей cgroup v1 с раздельными деревьями, в **cgroup v2** (ядро Linux 4.5+, дефолт в современных ОС) используется единая древовидная иерархия в каталоге `/sys/fs/cgroup/`:\n- **`memory.max`:** Жесткий потолок оперативной памяти. При превышении ядро запускает OOM Killer строго внутри контрольной группы, не задевая остальную систему.\n- **`cpu.max`:** Лимит CFS-планировщика (Completely Fair Scheduler) в формате `quota period` (например, `50000 100000` = 50% одного ядра CPU).\n- **`pids.max`:** Ограничение на максимальное количество процессов/потоков (threads/tasks).\n\n### Парирование атаки Fork Bomb:\nКлассическая fork-бомба (`:(){ :|:& };:`) циклически порождает дочерние процессы, исчерпывая системную таблицу процессов `pid_max` ядра Linux и вызывая полный крах всего сервера. При наличии контроллера cgroup `pids.max = 50`:\n- Как только сумма потоков рантайма Go и процессов достигает 50, системный вызов `clone()` возвращает ошибку `EAGAIN (Resource temporarily unavailable)`.\n- Ядро хоста остается стабильным, соседние сервисы продолжают работу без малейших задержек!",
        "step_by_step": [
            "Создайте изолированный сетевой неймспейс: `sudo ip netns add app_ns`.",
            "Создайте виртуальную пару интерфейсов veth и свяжите неймспейс с хостом.",
            "Создайте контрольную группу в cgroup v2: `sudo mkdir /sys/fs/cgroup/go_isolated_app`.",
            "Задайте лимит памяти: `echo 104857600 | sudo tee /sys/fs/cgroup/go_isolated_app/memory.max` (100MB).",
            "Задайте защиту от fork-бомб: `echo 50 | sudo tee /sys/fs/cgroup/go_isolated_app/pids.max`.",
            "Напишите Go-код, определяющий текущую cgroup процесса через `/proc/self/cgroup` и считывающий реальные лимиты памяти из `/sys/fs/cgroup/memory.max`."
        ],
        "code_blocks": [
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"log\"\n\t\"os\"\n\t\"strconv\"\n\t\"strings\"\n)\n\n// ReadCgroupV2MemoryMax считывает лимит памяти cgroup v2 для текущего процесса.\nfunc ReadCgroupV2MemoryMax() (int64, error) {\n\t// В cgroup v2 файл memory.max находится в директории cgroup процесса\n\t// Сначала читаем относительный путь из /proc/self/cgroup\n\tdata, err := os.ReadFile(\"/proc/self/cgroup\")\n\tif err != nil {\n\t\treturn 0, fmt.Errorf(\"read /proc/self/cgroup error: %w\", err)\n\t}\n\n\t// В cgroup v2 формат: \"0::/user.slice/user-1000.slice/...\"\n\tlines := strings.Split(strings.TrimSpace(string(data)), \"\\n\")\n\tif len(lines) == 0 {\n\t\treturn 0, fmt.Errorf(\"empty cgroup file\")\n\t}\n\n\tparts := strings.SplitN(lines[0], \"::\", 2)\n\tif len(parts) != 2 {\n\t\treturn 0, fmt.Errorf(\"invalid cgroup v2 format: %s\", lines[0])\n\t}\n\tcgroupPath := parts[1]\n\n\tfullPath := \"/sys/fs/cgroup\" + cgroupPath + \"/memory.max\"\n\t// Если путь не найден, проверяем корневой лимит\n\tif _, err := os.Stat(fullPath); os.IsNotExist(err) {\n\t\tfullPath = \"/sys/fs/cgroup/memory.max\"\n\t}\n\n\tvalBytes, err := os.ReadFile(fullPath)\n\tif err != nil {\n\t\treturn 0, fmt.Errorf(\"read %s error: %w\", fullPath, err)\n\t}\n\n\tvalStr := strings.TrimSpace(string(valBytes))\n\tif valStr == \"max\" {\n\t\treturn -1, nil // Без ограничений\n\t}\n\n\tlimit, err := strconv.ParseInt(valStr, 10, 64)\n\tif err != nil {\n\t\treturn 0, fmt.Errorf(\"parse limit '%s' error: %w\", valStr, err)\n\t}\n\treturn limit, nil\n}\n\nfunc main() {\n\tfmt.Printf(\"=== ДИАГНОСТИКА СИСТЕМНОЙ ИЗОЛЯЦИИ CGROUP V2 (PID: %d) ===\\n\", os.Getpid())\n\n\tlimit, err := ReadCgroupV2MemoryMax()\n\tif err != nil {\n\t\tlog.Printf(\"Инфо: cgroup v2 не обнаружен или недоступен: %v\", err)\n\t} else {\n\t\tif limit == -1 {\n\t\t\tfmt.Println(\"Лимит памяти cgroup v2: БЕЗ ОГРАНИЧЕНИЙ (max)\")\n\t\t} else {\n\t\t\tfmt.Printf(\"✅ Активен лимит памяти cgroup v2 (memory.max): %d МБ (%d байт)\\n\",\n\t\t\t\tlimit/(1024*1024), limit)\n\t\t}\n\t}\n\n\tfmt.Println(\"Изоляция ресурсов защищает хост от Fork-бомб и взаимного влияния сервисов (Noisy Neighbors).\")\n}\n"
            },
            {
                "filename": "setup_cgroup.sh",
                "lang": "bash",
                "code": "#!/bin/bash\nset -e\n\nCGROUP_DIR=\"/sys/fs/cgroup/my_go_service\"\n\necho \"=== Создание контрольной группы cgroup v2 ===\"\nsudo mkdir -p $CGROUP_DIR\n\n# 1. Ограничение памяти: 100 Мегабайт\necho 104857600 | sudo tee $CGROUP_DIR/memory.max\n\n# 2. Ограничение CPU: максимум 50% одного ядра (50000 мкс из 100000 мкс)\necho \"50000 100000\" | sudo tee $CGROUP_DIR/cpu.max\n\n# 3. Защита от Fork-бомб: не более 50 потоков/процессов\necho 50 | sudo tee $CGROUP_DIR/pids.max\n\necho \"Контрольная группа $CGROUP_DIR успешно настроена!\"\n# Для запуска процесса в cgroup:\n# echo $PID | sudo tee $CGROUP_DIR/cgroup.procs\n"
            }
        ],
        "under_the_hood": "Контроллер `pids` в ядре инкрементирует счетчик `pids_cgroup->pids_counter` при каждом вызове `copy_process()` внутри системного вызова `clone`/`fork`. Если счетчик превышает `pids.max`, ядро прерывает создание потока и возвращает `-EAGAIN`. Контроллер `memory` отслеживает аллокации страниц в `page_counter`. При достижении `memory.max` ядро сначала пытается освободить страничный кэш (page cache reclaim), а в случае неудачи вызывает `mem_cgroup_out_of_memory()`, уничтожающий самый прожорливый процесс внутри группы.",
        "pitfalls": "В многопоточном рантайме Go каждый системный тред (`M` в планировщике GMP) считается ядром Linux за отдельный PID/TID в контроллере `pids`. Если выставить чересчур низкий лимит `pids.max` (например, 5–10), то при росте сетевой нагрузки или выполнении блокирующих системных вызовов Go не сможет выделить новый тред `M`, что приведет к фатальной панике рантайма `runtime: failed to create new OS thread`.",
        "bigtech_interview": "Вопрос с собеседования в Wildberries: 'Как в Kubernetes связан параметр resources.limits.memory с файлами в /sys/fs/cgroup?' Ответ: 'При указании в манифесте `resources.limits.memory: 512Mi` контейнерный рантайм (containerd/CRI-O) переводит это значение в байты (536870912) и записывает в файл `memory.max` (в cgroup v2) или `memory.limit_in_bytes` (в cgroup v1) соответствующей контрольной группы пода в иерархии `/sys/fs/cgroup/kubepods.slice/`.'"
    },
    {
        "num": 22,
        "title": "Понижение привилегий в Kubernetes (SecurityContext): Запуск во враждебной среде Zero Trust",
        "task": "Спроектируйте отказоустойчивое Go-приложение и Kubernetes Deployment манифест с предельно жестким PodSecurityContext. Активируйте: runAsNonRoot: true, runAsUser: 10001, allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, и сбросьте абсолютно все возможности ядра capabilities: { drop: ['ALL'] }. Напишите Go-код, который успешно стартует и безупречно функционирует в такой максимально ограниченной среде, корректно выделяя временную память через emptyDir (tmpfs) и отдавая метрики работоспособности.",
        "theory": "В современном Kubernetes стандарты безопасности подов (**Pod Security Standards, PSS**) делятся на три уровня: `Privileged`, `Baseline` и **`Restricted`**.\n\n### Профиль Restricted — эталон DevSecOps:\nВ профиле `Restricted` от пода требуется:\n1. **`runAsNonRoot: true` и `runAsUser: 10001`:** Запрет запуска от UID 0. Kubelet откажется запускать контейнер, если в Dockerfile не указан non-root пользователь.\n2. **`allowPrivilegeEscalation: false`:** Устанавливает системный флаг ядра `PR_SET_NO_NEW_PRIVS = 1`. Исключает повышение привилегий через SUID-бинарники.\n3. **`readOnlyRootFilesystem: true`:** Корень контейнера монтируется в режиме Read-Only. Эксплойты не могут изменить бинарники или записать скрипты на диск.\n4. **`capabilities.drop: ['ALL']`:** Очистка всех дискретных возможностей суперпользователя.\n\n### Как Go-приложению выжить в такой среде:\n- Слушать непривилегированный порт (> 1023, например, `:8080`).\n- Писать логи исключительно в `stdout`/`stderr` (собираются fluentbit/promtail).\n- Не пытаться читать файлы хоста за пределами смонтированных томов.\n- Для временных файлов монтировать том типа `emptyDir` с параметром `medium: Memory` (RAM-диск tmpfs).",
        "step_by_step": [
            "Напишите Go HTTP-сервис с эндпоинтами `/healthz` и `/ready`.",
            "Реализуйте безопасную работу с временными файлами через каталог `/tmp` (смонтированный как emptyDir).",
            "Сформируйте production-манифест Kubernetes `deployment.yaml` с полным блоком `securityContext` уровня `Restricted`.",
            "Настройте том `emptyDir: medium: Memory` с лимитом размера `sizeLimit: 64Mi`.",
            "Проверьте код приложения на отсутствие скрытых зависимостей от root-прав."
        ],
        "code_blocks": [
            {
                "filename": "deployment.yaml",
                "lang": "yaml",
                "code": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: zero-trust-go-service\n  labels:\n    app: secure-backend\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: secure-backend\n  template:\n    metadata:\n      labels:\n        app: secure-backend\n    spec:\n      # Безопасность на уровне Pod\n      securityContext:\n        runAsNonRoot: true\n        runAsUser: 10001\n        runAsGroup: 10001\n        fsGroup: 10001\n        seccompProfile:\n          type: RuntimeDefault\n      containers:\n      - name: go-app\n        image: registry.example.com/secure-go-service:1.0.0\n        imagePullPolicy: IfNotPresent\n        # Безопасность на уровне Container (Restricted PSS)\n        securityContext:\n          allowPrivilegeEscalation: false\n          readOnlyRootFilesystem: true\n          capabilities:\n            drop:\n            - ALL\n        ports:\n        - containerPort: 8080\n          name: http\n        resources:\n          limits:\n            cpu: \"500m\"\n            memory: \"128Mi\"\n          requests:\n            cpu: \"100m\"\n            memory: \"64Mi\"\n        volumeMounts:\n        - name: tmp-volume\n          mountPath: /tmp\n      volumes:\n      - name: tmp-volume\n        emptyDir:\n          medium: Memory\n          sizeLimit: 64Mi\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"log\"\n\t\"net/http\"\n\t\"os\"\n\t\"path/filepath\"\n\t\"time\"\n)\n\nfunc main() {\n\tlog.SetOutput(os.Stdout)\n\tlog.Printf(\"[INIT] Старт сервиса в защищенном K8s Pod (UID=%d, GID=%d)...\",\n\t\tos.Getuid(), os.Getgid())\n\n\t// Проверяем возможность записи во временный RAM-диск /tmp\n\ttestTmpFile := filepath.Join(os.TempDir(), \"k8s_health.tmp\")\n\tif err := os.WriteFile(testTmpFile, []byte(\"ready\"), 0600); err != nil {\n\t\tlog.Fatalf(\"❌ Критическая ошибка: каталог /tmp недоступен для записи (emptyDir не смонтирован?): %v\", err)\n\t}\n\t_ = os.Remove(testTmpFile)\n\tlog.Println(\"✅ [STORAGE] Каталог /tmp (emptyDir/RAM) доступен для безопасных временных данных.\")\n\n\tmux := http.NewServeMux()\n\tmux.HandleFunc(\"/healthz\", func(w http.ResponseWriter, r *http.Request) {\n\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n\t\t_ = json.NewEncoder(w).Encode(map[string]interface{}{\n\t\t\t\"status\":    \"healthy\",\n\t\t\t\"uid\":       os.Getuid(),\n\t\t\t\"timestamp\": time.Now().Unix(),\n\t\t})\n\t})\n\n\tsrv := &http.Server{\n\t\tAddr:         \":8080\",\n\t\tHandler:      mux,\n\t\tReadTimeout:  5 * time.Second,\n\t\tWriteTimeout: 5 * time.Second,\n\t}\n\n\tlog.Println(\"🚀 Сервер успешно запущен на порту :8080 в режиме максимальной системной изоляции.\")\n\tif err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {\n\t\tlog.Fatalf(\"Ошибка сервера: %v\", err)\n\t}\n}\n"
            }
        ],
        "under_the_hood": "При создании пода с флагом `allowPrivilegeEscalation: false` контейнерный рантайм `containerd` вызывает системный вызов `prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0)`. Этот флаг на уровне ядра делает невозможным получение новых привилегий: даже если внутри образа случайно оказался бинарник с битом SUID (например, `/bin/su`), ядро проигнорирует бит владельца и выполнит процесс с текущим непривилегированным UID 10001.",
        "pitfalls": "Если в Kubernetes включен `readOnlyRootFilesystem: true`, а разработчик попытается использовать стороннюю библиотеку, которая в фоновом режиме инициализирует лог-файл по относительному пути `./app.log` (в рабочей директории образа, которая доступна только для чтения), под упадет в состояние `CrashLoopBackOff` с ошибкой `open ./app.log: read-only file system`.",
        "bigtech_interview": "Вопрос с собеседования в Яндекс: 'Что произойдет, если в Kubernetes поде с emptyDir medium: Memory процесс выделит больше данных, чем указано в sizeLimit?' Ответ: 'Директива `medium: Memory` монтирует Linux `tmpfs`. Если процесс превышает установленный `sizeLimit` (например, 64Mi), фоновый процесс Kubelet (node eviction manager) обнаружит превышение квоты использования тома и выполнит принудительное уничтожение (Eviction) пода со статусом `The node was low on resource: ephemeral-storage`.'"
    },
    {
        "num": 23,
        "title": "eBPF для Runtime Security: Мониторинг системных вызовов в стиле Falco",
        "task": "Изучите архитектуру современных агентов обнаружения угроз в реальном времени (Runtime Security, аналог Falco и Cilium Tetragon). Напишите Go-программу с использованием пакета github.com/cilium/ebpf, которая загружает в ядро Linux программу трассировки точки входа системного вызова connect (tracepoint/syscalls/sys_enter_connect). Продемонстрируйте перехват сетевых подключений процесса, парсинг IP-адресов назначения и отправку мгновенных алертов о несанкционированной сетевой активности (Security Anomaly Alert) в userspace через ring buffer.",
        "theory": "Традиционные методы безопасности (Seccomp, Capabilities) являются **статическими**: они либо запрещают сисколл полностью, либо разрешают его. Но что делать, если веб-сервису разрешено вызывать `connect()`, однако легитимными являются подключения только к внутренней базе данных PostgreSQL (10.0.1.5), а попытка подключения к внешнему неизвестному IP является явным признаком утечки данных (Data Exfiltration)?\n\n### Революция eBPF (Extended Berkeley Packet Filter):\n**eBPF** превратил ядро Linux в полностью программируемую платформу:\n- Программы на Си компилируются в байткод eBPF через `clang/LLVM`.\n- Ядро валидирует безопасность кода с помощью встроенного **eBPF Verifier** (проверка отсутствия бесконечных циклов, выхода за границы памяти и разыменования нулевых указателей).\n- Программа аттачится к **Kprobes**, **Tracepoints** или **LSM-хукам** ядра.\n- При вызове `connect()` программа eBPF выполняется в кольце 0 ядра Linux за считанные наносекунды, извлекает сетевой адрес и через кольцевой буфер (**BPF Ring Buffer**) передает структурированное событие агенту безопасности на Go в userspace.\n\n### Архитектура в стиле Falco / Tetragon:\nАгент на Go считывает события без Stop-The-World задержек:\n1. Фильтрация по PID процесса.\n2. Проверка IP по белому списку разрешенных сервисов.\n3. Мгновенная генерация SIEM-алерта при попытке подключения к подозрительному хосту.",
        "step_by_step": [
            "Опишите Си-код eBPF-программы для tracepoint `syscalls/sys_enter_connect`.",
            "Объявите BPF Ring Buffer для передачи событий в пространство пользователя.",
            "Напишите Go-код загрузки eBPF через пакет `github.com/cilium/ebpf`.",
            "Создайте слушатель кольцевого буфера `ringbuf.NewReader`.",
            "Реализуйте декодирование структуры сетевого адреса (`sockaddr_in`) и конвертацию в понятный IP:Port.",
            "Продемонстрируйте детекцию сетевого соединения."
        ],
        "code_blocks": [
            {
                "filename": "bpf_program.c",
                "lang": "c",
                "code": "// +build ignore\n\n#include <linux/bpf.h>\n#include <linux/in.h>\n#include <bpf/bpf_helpers.h>\n\n// Структура события, передаваемого в Go userspace\nstruct event_t {\n    __u32 pid;\n    __u32 daddr; // IPv4 назначения\n    __u16 dport; // Порт назначения\n};\n\n// Ring Buffer для передачи событий агенту безопасности\nstruct {\n    __uint(type, BPF_MAP_TYPE_RINGBUF);\n    __uint(max_entries, 256 * 1024);\n} events SEC(\".maps\");\n\nSEC(\"tracepoint/syscalls/sys_enter_connect\")\nint trace_connect(struct trace_event_raw_sys_enter *ctx) {\n    __u64 pid_tgid = bpf_get_current_pid_tgid();\n    __u32 pid = pid_tgid >> 32;\n\n    // Резервируем память в ring buffer\n    struct event_t *event = bpf_ringbuf_reserve(&events, sizeof(struct event_t), 0);\n    if (!event) {\n        return 0;\n    }\n\n    event->pid = pid;\n    event->daddr = 0x08080808; // 8.8.8.8 в качестве примера\n    event->dport = 53;\n\n    bpf_ringbuf_submit(event, 0);\n    return 0;\n}\n\nchar LICENSE[] SEC(\"license\") = \"GPL\";\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"encoding/binary\"\n\t\"fmt\"\n\t\"log\"\n\t\"net\"\n\t\"os\"\n)\n\n// Event описывает событие, полученное из ядра Linux через eBPF ring buffer.\ntype Event struct {\n\tPID   uint32\n\tDAddr uint32\n\tDPort uint16\n}\n\n// ParseIPv4 конвертирует сетевой порядок байт в стандартный net.IP.\nfunc ParseIPv4(ipUint uint32) net.IP {\n\tipBytes := make([]byte, 4)\n\tbinary.BigEndian.PutUint32(ipBytes, ipUint)\n\treturn net.IP(ipBytes)\n}\n\n// SecurityAuditHandler обрабатывает сетевые события от eBPF ядра.\nfunc SecurityAuditHandler(ev Event) {\n\tdestIP := ParseIPv4(ev.DAddr)\n\n\t// Белый список разрешенных IP для микросервиса (например, внутренняя сеть)\n\tisAuthorized := destIP.Equal(net.ParseIP(\"10.0.1.5\")) || destIP.Equal(net.ParseIP(\"127.0.0.1\"))\n\n\tif !isAuthorized {\n\t\tlog.Printf(\"🚨 [SECURITY ALERT] Подозрительное исходящее соединение!\\n\"+\n\t\t\t\"   PID: %d попытался связаться с неизвестным хостом %s:%d\\n\"+\n\t\t\t\"   Возможная атака: Data Exfiltration / C&C Connection!\",\n\t\t\tev.PID, destIP.String(), ev.DPort)\n\t} else {\n\t\tlog.Printf(\"✅ [AUDIT OK] Легитимный коннект: PID %d -> %s:%d\",\n\t\t\tev.PID, destIP.String(), ev.DPort)\n\t}\n}\n\nfunc main() {\n\tfmt.Printf(\"=== eBPF RUNTIME SECURITY MONITOR (PID: %d) ===\\n\", os.Getpid())\n\tfmt.Println(\"Архитектура анализа аномалий в ядре Linux (Falco / Tetragon style).\")\n\n\t// Эмуляция получения события из eBPF кольцевого буфера\n\tsampleEvent := Event{\n\t\tPID:   uint32(os.Getpid()),\n\t\tDAddr: binary.BigEndian.Uint32(net.ParseIP(\"198.51.100.42\").To4()),\n\t\tDPort: 4444,\n\t}\n\n\tfmt.Println(\"Обработка перехваченного системного вызова connect()...\")\n\tSecurityAuditHandler(sampleEvent)\n}\n"
            }
        ],
        "under_the_hood": "Программы eBPF выполняются в ядре с использованием JIT-компилятора (Just-In-Time), транслирующего байткод eBPF в машинные инструкции x86_64. Хелпер `bpf_ringbuf_reserve()` атомарно выделяет память в кольцевом буфере ядра с использованием алгоритма без блокировок (Lock-free memory allocation). Функция `bpf_ringbuf_submit()` обновляет указатель заголовка буфера и инициирует событие пробуждения epoll для агента в userspace.",
        "pitfalls": "Загрузка eBPF-программ в ядро требует привилегий `CAP_BPF` (или `CAP_SYS_ADMIN` на старых ядрах) и `CAP_NET_ADMIN`. Если в Kubernetes контейнер агента запущен без этих capabilities, системный вызов `bpf(BPF_PROG_LOAD)` завершится ошибкой `EPERM`. В современных версиях Linux (5.8+) рекомендуется выделять именно специализированную `CAP_BPF` вместо всемогущей `CAP_SYS_ADMIN`.",
        "bigtech_interview": "Вопрос с собеседования в Wildberries: 'Чем мониторинг рантайм-безопасности через eBPF превосходит парсинг логов auditd?' Ответ: '1) Производительность: eBPF фильтрует события прямо в ядре, не копируя ненужный контекст в userspace, что снижает нагрузку на CPU на порядки. 2) Устойчивость: аудит-лог `auditd` при высокой нагрузке переполняет буфер и начинает терять события (audit buffer overflow), в то время как eBPF использует масштабируемые постраничные Ring Buffers. 3) Возможность активного противодействия: с помощью хуков `LSM BPF` или возврата ошибок eBPF может не только логировать, но и превентивно блокировать опасные системные вызовы в реальном времени.'"
    },
    {
        "num": 24,
        "title": "Воспроизводимые сборки (Reproducible Builds): Детерминизм бинарников и защита цепочки поставок",
        "task": "Изучите концепцию воспроизводимых сборок (Reproducible / Deterministic Builds) в компиляторе Go. Продемонстрируйте, как флаги сборки -trimpath и -ldflags='-buildid=' устраняют влияние абсолютных путей к файловой системе разработчика и случайных временных меток сборщика. Напишите проверочный bash/Go-скрипт, который собирает бинарный файл в двух совершенно разных временных директориях и доказывает их 100% побайтовое совпадение через сравнение контрольных сумм SHA-256.",
        "theory": "В рамках безопасности цепочки поставок ПО (**Supply Chain Security**) критически важным свойством является **воспроизводимость сборки (Reproducibility)**:\n*Любой независимый аудитор, взяв один и тот же исходный код и ту же версию компилятора Go, обязан получить **побайтово идентичный исполняемый файл**!*\n\n### Почему стандартный `go build` недетерминирован:\nЕсли собрать один и тот же код стандартной командой `go build main.go`:\n1. **Абсолютные пути в отладочной информации DWARF:** Компилятор вшивает полные пути файлов исходного кода (например, `/home/alice/go-workout/main.go`). На машине CI-сервера путь будет `/builds/runner/main.go`, что приведет к разным контрольным суммам бинарников!\n2. **Уникальный Build ID:** Go генерирует уникальный криптографический идентификатор сборки (`buildid`), зависящий от временных меток и промежуточных хэшей действий.\n\n### Золотой стандарт флагов воспроизводимой сборки:\n```bash\nCGO_ENABLED=0 go build -trimpath -ldflags=\"-buildid=\" -o app main.go\n```\n- **`-trimpath`:** Удаляет все абсолютные префиксы путей к файлам из бинарника, заменяя их относительными путями модуля.\n- **`-ldflags=\"-buildid=\"`:** Обнуляет уникальный идентификатор сборки, делая выходной ELF-бинарник полностью детерминированным.\n- **`CGO_ENABLED=0`:** Исключает влияние различий во внешних динамических библиотеках glibc хост-системы.",
        "step_by_step": [
            "Создайте демонстрационную Go-программу.",
            "Сформируйте скрипт, создающий две изолированные временные папки `/tmp/dir_A` и `/tmp/dir_B`.",
            "Скопируйте исходный код в обе папки.",
            "Соберите бинарник в первой папке с флагами `-trimpath -ldflags='-buildid='`.",
            "Соберите бинарник во второй папке с теми же флагами.",
            "Вычислите хэши `sha256sum /tmp/dir_A/app` и `sha256sum /tmp/dir_B/app`.",
            "Убедитесь, что SHA-256 хэши побайтово совпадают, подтверждая 100% детерминизм."
        ],
        "code_blocks": [
            {
                "filename": "verify_reproducible.sh",
                "lang": "bash",
                "code": "#!/bin/bash\nset -e\n\nDIR_A=$(mktemp -d /tmp/build_a_XXXXXX)\nDIR_B=$(mktemp -d /tmp/build_b_XXXXXX)\n\ntrap \"rm -rf $DIR_A $DIR_B\" EXIT\n\necho \"=== ТЕСТИРОВАНИЕ ВОСПРОИЗВОДИМЫХ СБОРОК (REPRODUCIBLE BUILDS) ===\"\necho \"Папка A: $DIR_A\"\necho \"Папка B: $DIR_B\"\n\n# Копируем исходный код\ncp main.go $DIR_A/\ncp main.go $DIR_B/\n\n# Сборка в директории A\ncd $DIR_A\nCGO_ENABLED=0 go build -trimpath -ldflags=\"-w -s -buildid=\" -o binary_a main.go\nHASH_A=$(sha256sum binary_a | awk '{print $1}')\n\n# Сборка в директории B\ncd $DIR_B\nCGO_ENABLED=0 go build -trimpath -ldflags=\"-w -s -buildid=\" -o binary_b main.go\nHASH_B=$(sha256sum binary_b | awk '{print $1}')\n\necho \"--------------------------------------------------\"\necho \"SHA256 Сборки A: $HASH_A\"\necho \"SHA256 Сборки B: $HASH_B\"\necho \"--------------------------------------------------\"\n\nif [ \"$HASH_A\" == \"$HASH_B\" ]; then\n    echo \"✅ ИДЕАЛЬНО: Сборки на 100% побайтово идентичны! Детерминизм доказан.\"\nelse\n    echo \"❌ ОШИБКА: Хэши не совпадают! Присутствует недетерминированность.\"\n    exit 1\nfi\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"crypto/sha256\"\n\t\"fmt\"\n\t\"io\"\n\t\"log\"\n\t\"os\"\n)\n\n// PrintBinarySelfHash вычисляет SHA256 собственного исполняемого файла.\nfunc PrintBinarySelfHash() {\n\texecPath, err := os.Executable()\n\tif err != nil {\n\t\tlog.Printf(\"Не удалось получить путь к бинарнику: %v\", err)\n\t\treturn\n\t}\n\n\tf, err := os.Open(execPath)\n\tif err != nil {\n\t\tlog.Printf(\"Не удалось открыть бинарник: %v\", err)\n\t\treturn\n\t}\n\tdefer f.Close()\n\n\th := sha256.New()\n\tif _, err := io.Copy(h, f); err != nil {\n\t\tlog.Printf(\"Ошибка вычисления хэша: %v\", err)\n\t\treturn\n\t}\n\n\tfmt.Printf(\"[REPRODUCIBLE BINARY] SHA256: %x (Path: %s)\\n\", h.Sum(nil), execPath)\n}\n\nfunc main() {\n\tfmt.Println(\"=== ТЕСТ ДЕТЕРМИНИРОВАННОЙ СБОРКИ GO ===\")\n\tPrintBinarySelfHash()\n}\n"
            }
        ],
        "under_the_hood": "Компилятор Go при сборке генерирует секцию ELF `.note.go.buildid`. По умолчанию значение `buildid` представляет собой составную строку, включающую хэш входных параметров и хэш сгенерированного кода пакета. Флаг `-ldflags='-buildid='` принудительно заменяет `buildid` пустой строкой. Флаг `-trimpath` заменяет абсолютные пути в таблицах имен файлов PCLNTAB (`runtime.pclntab`) относительными путями модулей, устраняя любые следы директорий файловой системы сборочного хоста.",
        "pitfalls": "Если в коде используются переменные, внедряемые во время сборки через `-ldflags='-X main.buildDate=...'` или `-X main.gitCommit=...`, это автоматически разрушает воспроизводимость сборки: два последовательных запуска сборки будут иметь разные временные метки. Для сохранения воспроизводимости используйте стандарт `SOURCE_DATE_EPOCH` (дата последнего коммита из Git) вместо текущего времени `time.Now()`.",
        "bigtech_interview": "Вопрос с собеседования в Касперский: 'Зачем независимые аудиторы требуют воспроизводимости сборок при проверке безопасности open-source проектов?' Ответ: 'Воспроизводимая сборка позволяет гарантировать, что опубликованный в релизах скомпилированный бинарный файл был собран **строго из опубликованного исходного кода** без внедрения скрытых закладок (бэкдоров), троянов или вредоносных модулей на стадии сборочного пайплайна (защита от атак компрометации CI/CD в стиле SolarWinds).'"
    },
    {
        "num": 25,
        "title": "AppArmor / SELinux (Интеграция): Жесткое ограничение сетевого egress к IP базы данных",
        "task": "Спроектируйте профиль системы принудительного контроля доступа AppArmor / SELinux, реализующий бескомпромиссный сетевой эшелон защиты (Network Egress Control): разрешите исходящие сетевые подключения Go-микросервиса исключительно к заранее определенному IP-адресу и порту сервера баз данных (PostgreSQL, 192.168.1.100:5432) и запретите ЛЮБЫЕ другие исходящие подключения в глобальный интернет. Разберите применение профиля в контейнере Docker и проверьте реакцию ядра на попытку несанкционированного коннекта.",
        "theory": "Одной из главных целей злоумышленника при успешной атаке на микросервис является организация исходящего канала связи (**Egress Traffic**):\n1. Загрузка вредоносного бинарника из командного центра (`C&C Server`).\n2. Утечка конфиденциальных данных клиентов на внешний сервер атакующего (Data Exfiltration).\n3. Сканирование внутренней подсети Kubernetes для горизонтального перемещения (Lateral Movement).\n\n### Ограничение исходящей сети через профили безопасности:\nХотя стандартный AppArmor оперирует на уровне семейств сокетов (`network inet stream`), в современных версиях AppArmor 3.0+ и SELinux возможна точечная фильтрация исходящих сетевых направлений в связке с политиками ядра.\nВ сочетании с сетевыми политиками ядра (Network Policies / iptables `cgroup` matching):\n- Процессу с конкретной меткой безопасности (Security Label / AppArmor Profile) разрешается передача пакетов **только к IP целевой базы данных**.\n- Любая попытка вызова `connect()` к внешнему публичному IP или соседнему поду блокируется ядром на уровне сетевого стека с возвратом `ECONNREFUSED` или `EPERM`.",
        "step_by_step": [
            "Напишите конфигурационный профиль AppArmor `docker-postgres-egress-only`.",
            "Настройте базовые разрешения контейнера (`#include <abstractions/base>`).",
            "Настройте ограничение сокетов и сетевого доступа.",
            "Напишите Go-клиент, выполняющий легитимный коннект к локальной БД и попытку несанкционированного коннекта к стороннему IP (например, `1.1.1.1:80`).",
            "Продемонстрируйте запуск контейнера с флагом `--security-opt apparmor=docker-postgres-egress-only`.",
            "Убедитесь в обработке ошибки отказа в соединении."
        ],
        "code_blocks": [
            {
                "filename": "docker-postgres-egress-only",
                "lang": "bash",
                "code": "# /etc/apparmor.d/docker-postgres-egress-only\n#include <tunables/global>\n\nprofile docker-postgres-egress-only flags=(attach_disconnected, enforce) {\n  #include <abstractions/base>\n\n  # Разрешаем запуск бинарника внутри контейнера\n  /app/server mr,\n\n  # Разрешаем TCP-сокеты (IPv4)\n  network inet stream,\n\n  # Файловая система: только чтение рабочей папки\n  /app/** r,\n  /tmp/ rw,\n\n  # Запрет низкоуровневых и опасных сетевых операций\n  deny network raw,\n  deny network packet,\n\n  # Примечание: Для побайтовой фильтрации IP-адресов в Linux\n  # AppArmor комбинируется с iptables cgroup rule или eBPF cgroup/sock_addr!\n}\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"context\"\n\t\"fmt\"\n\t\"log\"\n\t\"net\"\n\t\"os\"\n\t\"time\"\n)\n\n// AllowedDatabaseIP эмулирует единственный разрешенный целевой сервер (PostgreSQL)\nconst AllowedDatabaseIP = \"127.0.0.1:5432\"\n\n// TestConnection выполняет сетевое подключение с таймаутом\nfunc TestConnection(ctx context.Context, targetAddr string) error {\n\tvar d net.Dialer\n\tconn, err := d.DialContext(ctx, \"tcp\", targetAddr)\n\tif err != nil {\n\t\treturn err\n\t}\n\tdefer conn.Close()\n\treturn nil\n}\n\nfunc main() {\n\tfmt.Printf(\"=== ПРОВЕРКА ОГРАНИЧЕНИЙ СЕТЕВОГО EGRESS (PID: %d) ===\\n\", os.Getpid())\n\n\tctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)\n\tdefer cancel()\n\n\t// 1. Попытка легитимного подключения к базе данных\n\tfmt.Printf(\"1. Попытка подключения к доверенной БД (%s)...\\n\", AllowedDatabaseIP)\n\terr := TestConnection(ctx, AllowedDatabaseIP)\n\tif err != nil {\n\t\t// В тестовой среде порт 5432 может быть закрыт — это норма\n\t\tfmt.Printf(\"   Результат: соединение инициировано (error=%v)\\n\", err)\n\t} else {\n\t\tfmt.Println(\"   ✅ Успешное соединение с базой данных!\")\n\t}\n\n\t// 2. Симуляция несанкционированной попытки утечки данных на внешний сервер\n\tunauthorizedTarget := \"198.51.100.1:443\"\n\tfmt.Printf(\"2. Попытка несанкционированного коннекта на внешний IP (%s)...\\n\", unauthorizedTarget)\n\n\terr = TestConnection(ctx, unauthorizedTarget)\n\tif err != nil {\n\t\tfmt.Printf(\"🛡️ [EGRESS BLOCKED] Соединение отклонено или оборвано по таймауту: %v\\n\"+\n\t\t\t\"   Политика безопасности хоста предотвратила нелегитимный сетевой трафик!\\n\", err)\n\t} else {\n\t\tlog.Fatalf(\"❌ ОШИБКА: Соединение с внешним хостом %s успешно установлено!\", unauthorizedTarget)\n\t}\n}\n"
            }
        ],
        "under_the_hood": "В ядре Linux для тонкой фильтрации исходящих сетевых адресов (Egress Control) по процессам применяется программа `eBPF` типа `BPF_PROG_TYPE_CGROUP_SOCK_ADDR` с хуком `connect4`. Когда Go-программа вызывает `connect()`, ядро до отправки TCP SYN-пакета передает структуру `bpf_sock_addr` в фильтр eBPF. Если целевой `user_ip` не равен IP-адресу базы данных, eBPF возвращает 0, и ядро мгновенно возвращает системную ошибку `-EPERM` вызывающему потоку без генерации трафика в сетевой стек.",
        "pitfalls": "Если микросервис использует доменные имена (например, `db.internal.company.com`), ему жизненно необходим доступ к DNS-серверу (UDP-порт 53). Если заблокировать абсолютно весь egress-трафик, сервис не сможет выполнить DNS-резолвинг имени базы данных и упадет при старте с ошибкой `dial tcp: lookup db.internal: no such host`. В белый список egress всегда должны включаться DNS-серверы кластера.",
        "bigtech_interview": "Вопрос с собеседования в Wildberries: 'Как в Kubernetes гарантировать, что скомпрометированный под не сможет отправить данные во внешнюю сеть?' Ответ: 'С помощью ресурса `NetworkPolicy` с селектором `egress`. В правиле `egress` указываются только CIDR-блоки внутренних сервисов (базы данных, кэши) и порт UDP 53 для `kube-dns`. Любой трафик в сторону 0.0.0.0/0 по умолчанию блокируется сетевым плагином (Cilium/Calico) на уровне правил iptables/eBPF ядра ноды.'"
    },
    {
        "num": 26,
        "title": "eBPF (Взгляд в будущее): Трассировка sys_enter_connect через bpf2go и cilium/ebpf",
        "task": "Изучите современный промышленный стек разработки eBPF на Go с помощью утилиты bpf2go и библиотеки github.com/cilium/ebpf. Напишите eBPF-программу на Си, перехватывающую системный вызов connect (sys_enter_connect) на уровне всей операционной системы. Скомпилируйте ее в Go-пакет через bpf2go и напишите Go-приложение, которое загружает эту eBPF-программу в ядро, считывает события новых TCP-подключений и выводит IP-адреса и PID процессов в режиме реального времени.",
        "theory": "Интеграция Go и eBPF стала индустриальным стандартом для создания высокопроизводительных систем наблюдаемости (**Observability**) и безопасности (**Cloud-Native Security**), таких как Datadog Agent, Pixie, Cilium и Coroot.\n\n### Технология `bpf2go`:\nУтилита `bpf2go` (из проекта `cilium/ebpf`) автоматизирует компиляцию Си-кода и генерацию оберток на Go:\n1. Вызывает компилятор `clang` с целевой архитектурой `bpf`.\n2. Извлекает метаданные BTF (BPF Type Format).\n3. Генерирует типобезопасные Go-структуры (`bpfObjects`, `bpfPrograms`, `bpfMaps`), полностью устраняя необходимость ручной работы с памятью и вызовов CGO!\n\n### Архитектура перехвата `sys_enter_connect`:\nТочка трассировки `tracepoint/syscalls/sys_enter_connect` активируется ядром Linux каждый раз, когда **любой процесс в операционной системе** выполняет системный вызов `connect()`.\n- eBPF считывает аргументы системного вызова из контекста ядра (`args[1]` = указатель на `struct sockaddr`).\n- С помощью хелпера ядра `bpf_probe_read_user()` данные адреса безопасно копируются в память eBPF.\n- Событие передается Go-приложению через кольцевой буфер `BPF_MAP_TYPE_RINGBUF` с микросекундной задержкой.",
        "step_by_step": [
            "Создайте Си-файл `connect_tracer.c` с хелперами `bpf_probe_read_user` и картой `ringbuf`.",
            "Настройте директиву генерации кода: `//go:generate go run github.com/cilium/ebpf/cmd/bpf2go bpf connect_tracer.c`.",
            "Опишите структуру передачи данных события в Go.",
            "Напишите Go-код инициализации: загрузка объектов eBPF через `loadBpfObjects`.",
            "Привяжите программу к точке трассировки через `link.Tracepoint`.",
            "Запустите цикл чтения событий из `ringbuf.NewReader` с выводом PID и сетевых адресов."
        ],
        "code_blocks": [
            {
                "filename": "connect_tracer.c",
                "lang": "c",
                "code": "// +build ignore\n\n#include <linux/bpf.h>\n#include <linux/in.h>\n#include <bpf/bpf_helpers.h>\n#include <bpf/bpf_tracing.h>\n\nstruct event {\n    __u32 pid;\n    __u32 daddr;\n    __u16 dport;\n};\n\n// eBPF Ring Buffer для потоковой передачи событий агенту на Go\nstruct {\n    __uint(type, BPF_MAP_TYPE_RINGBUF);\n    __uint(max_entries, 1 << 20); // 1 MB\n} events SEC(\".maps\");\n\nSEC(\"tracepoint/syscalls/sys_enter_connect\")\nint trace_sys_enter_connect(struct trace_event_raw_sys_enter *ctx) {\n    __u64 id = bpf_get_current_pid_tgid();\n    __u32 pid = id >> 32;\n\n    struct sockaddr_in sa;\n    // Аргумент 1 системного вызова connect(fd, &uservaddr, addrlen)\n    void *sockaddr_ptr = (void *)ctx->args[1];\n\n    if (!sockaddr_ptr) {\n        return 0;\n    }\n\n    // Безопасное чтение памяти пользователя из ядра\n    if (bpf_probe_read_user(&sa, sizeof(sa), sockaddr_ptr) < 0) {\n        return 0;\n    }\n\n    // Фильтруем только семейство адресов IPv4 (AF_INET = 2)\n    if (sa.sin_family != 2) {\n        return 0;\n    }\n\n    struct event *ev = bpf_ringbuf_reserve(&events, sizeof(struct event), 0);\n    if (!ev) {\n        return 0;\n    }\n\n    ev->pid = pid;\n    ev->daddr = sa.sin_addr.s_addr;\n    ev->dport = bpf_ntohs(sa.sin_port);\n\n    bpf_ringbuf_submit(ev, 0);\n    return 0;\n}\n\nchar LICENSE[] SEC(\"license\") = \"Dual BSD/GPL\";\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"encoding/binary\"\n\t\"fmt\"\n\t\"net\"\n\t\"os\"\n)\n\n// Event описывает данные события перехваченного сисколла connect\ntype Event struct {\n\tPID   uint32\n\tDAddr uint32\n\tDPort uint16\n}\n\nfunc formatIP(addr uint32) string {\n\tipBytes := make([]byte, 4)\n\tbinary.LittleEndian.PutUint32(ipBytes, addr)\n\treturn net.IP(ipBytes).String()\n}\n\nfunc main() {\n\tfmt.Println(\"=== eBPF СИСТЕМНЫЙ ТРАССИРОВЩИК CONNECT (bpf2go) ===\")\n\tfmt.Printf(\"[PID %d] Готов к приему телеметрии ядра Linux...\\n\", os.Getpid())\n\n\t// Демонстрация логики декодирования события из ring buffer ядра\n\tmockEvent := Event{\n\t\tPID:   uint32(os.Getpid()),\n\t\tDAddr: binary.LittleEndian.Uint32(net.ParseIP(\"93.184.216.34\").To4()), // example.com\n\t\tDPort: 443,\n\t}\n\n\tdestIP := formatIP(mockEvent.DAddr)\n\tfmt.Printf(\"🔍 [KERNEL EVENT] Перехвачен connect(): PID=%d соединяется с %s:%d\\n\",\n\t\tmockEvent.PID, destIP, mockEvent.DPort)\n\n\tfmt.Println(\"Технология bpf2go обеспечивает 100% автономность: чистый Go без CGO в рантайме!\")\n}\n"
            }
        ],
        "under_the_hood": "Утилита `bpf2go` компилирует исходный Си-код с флагом `-target bpf -g` для генерации отладочной информации BTF (BPF Type Format). Полученный ELF-объект упаковывается прямо внутрь сгенерированного Go-файла в виде сжатого байтового массива (`var _BpfBytes = [...]byte{...}`). В момент запуска рантайм `cilium/ebpf` загружает байты через системный вызов `bpf(BPF_PROG_LOAD)` без необходимости сохранения временных файлов на диске.",
        "pitfalls": "При чтении сетевых структур из userspace (`sockaddr_in`) поле порта `sin_port` записано в сетевом порядке байт (Big-Endian / Network Byte Order). На архитектурах x86_64 (Little-Endian) вызов без конвертации макросом `bpf_ntohs()` приведет к искажению номера порта (например, порт 80 отобразится как 20480). Всегда используйте `bpf_ntohs()`!",
        "bigtech_interview": "Вопрос с собеседования в Яндекс: 'Что такое CO-RE (Compile Once – Run Everywhere) в eBPF и как оно решает проблему совместимости с разными версиями ядер Linux?' Ответ: 'В классическом BPF программа зависела от точного расположения полей в структурах ядра (структура `task_struct` меняется от версии к версии ядра Linux), что требовало наличия сборочных заголовков `kernel-headers` на каждой хост-машине. Технология CO-RE опирается на метаданные BTF и встроенный рантайм-релокатор `libbpf`/`cilium/ebpf`: компилятор генерирует абстрактные обращения к полям, а библиотека в момент загрузки на целевой ноде на лету корректирует байткод под структуру текущего работающего ядра!'"
    },
    {
        "num": 27,
        "title": "Изоляция ядра с помощью gVisor: Архитектурное сравнение runc vs runsc и защита от Container Escape",
        "task": "Напишите глубокое инженерно-аналитическое исследование и архитектурное сравнение стандартного рантайма Docker (runc) и песочницы gVisor (рантайм runsc от Google). Разберите, как gVisor перехватывает системные вызовы гостевого приложения и обрабатывает их в изолированном пользовательском пространстве на Go (ядро Sentry), формируя непробиваемую границу доверия между контейнером и реальным ядром хост-системы. Объясните, почему gVisor нейтрализует 100% атак класса Container Escape и как запустить Go-микросервис под управлением runsc в Docker/Kubernetes.",
        "theory": "В стандартных контейнерах Docker/Kubernetes используется OCI-рантайм **`runc`**:\n- Контейнер разделяет **одно общее ядро хоста**.\n- Если злоумышленник обнаружит уязвимость в реализации системного вызова ядра Linux (например, Use-After-Free в подсистеме io_uring, eBPF verifier flaw, Dirty Pipe CVE-2022-0847), он получает доступ к кольцу 0 (Ring 0) хоста и захватывает управление всей физической нодой!\n\n### Революция `gVisor` (Google runsc):\n**gVisor** — это открытая песочница виртуализации уровня приложений, написанная инженерами Google на языке **Go**.\ngVisor выступает в роли **пользовательского ядра-посредника (Application Kernel)** между приложением и настоящим ядром хоста:\n\n1. **Архитектура Sentry (Ядро на Go):**\n   - Все системные вызовы процесса-жертвы (например, `open`, `read`, `socket`, `fork`) **перехватываются** механизмом виртуализации (через KVM или ptrace).\n   - Вызовы **НЕ передаются в ядро хоста**! Вместо этого они эмулируются кодом `Sentry`, написанным на безопасном языке Go с защитой памяти (Memory Safety).\n   - В ядре Sentry реализовано более **300 системных вызовов Linux** и полноценный сетевой стек **Netstack** (также написанный на чистом Go).\n\n2. **Процесс Gofer (Файловый посредник):**\n   - Файловые операции изолируются отдельным процессом `Gofer`, общающимся с `Sentry` через протокол 9P/LHP.\n\n3. **Непробиваемая защита от Container Escape:**\n   - Даже если хакер использует эксплойт против ядра Linux, эксплойт попадает в песочницу Sentry на Go, которая не содержит Си-ошибок работы с памятью и не дает доступа к реальному хостовому ядру!",
        "step_by_step": [
            "Установите gVisor runtime (`runsc`) на хостовую систему.",
            "Настройте Docker daemon (`/etc/docker/daemon.json`) для поддержки рантайма `runsc`.",
            "Напишите Go-программу, инспектирующую свое окружение (считывание `/proc/version` и сравнение характеристик).",
            "Запустите контейнер в стандартном режиме: `docker run --rm alpine uname -a`.",
            "Запустите контейнер под управлением gVisor: `docker run --runtime=runsc --rm alpine uname -a`.",
            "Зафиксируйте кардинальную разницу в выводе версии ядра (gVisor эмулирует Linux-совместимую среду)."
        ],
        "code_blocks": [
            {
                "filename": "daemon.json",
                "lang": "json",
                "code": "{\n  \"runtimes\": {\n    \"runsc\": {\n      \"path\": \"/usr/local/bin/runsc\",\n      \"runtimeArgs\": [\n        \"--platform=kvm\",\n        \"--network=sandbox\"\n      ]\n    }\n  }\n}\n"
            },
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"log\"\n\t\"os\"\n\t\"strings\"\n)\n\n// DetectRuntimeEnvironment определяет, работает ли приложение под защитой gVisor.\nfunc DetectRuntimeEnvironment() {\n\tdata, err := os.ReadFile(\"/proc/version\")\n\tif err != nil {\n\t\tlog.Printf(\"Не удалось прочитать /proc/version: %v\", err)\n\t\treturn\n\t}\n\n\tversionStr := string(data)\n\tfmt.Println(\"=== АНАЛИЗ ОКРУЖЕНИЯ ЯДРА ОПЕРАЦИОННОЙ СИСТЕМЫ ===\")\n\tfmt.Printf(\"Вывод /proc/version:\\n%s\\n\", strings.TrimSpace(versionStr))\n\n\tif strings.Contains(strings.ToLower(versionStr), \"gvisor\") {\n\t\tfmt.Println(\"🛡️ [GVISOR DETECTED] Приложение изолировано в песочнице Google gVisor (runsc)!\")\n\t\tfmt.Println(\"   Все системные вызовы эмулируются ядром Sentry на языке Go.\")\n\t\tfmt.Println(\"   Побег из контейнера (Container Escape) на хост-ноду математически блокирован.\")\n\t} else {\n\t\tfmt.Println(\"⚠️ [STANDARD RUNTIME] Приложение запущено под стандартным runc.\")\n\t\tfmt.Println(\"   Ядро Linux разделяется с хост-системой.\")\n\t}\n}\n\nfunc main() {\n\tDetectRuntimeEnvironment()\n}\n"
            },
            {
                "filename": "k8s-gvisor-runtimeclass.yaml",
                "lang": "yaml",
                "code": "# Настройка gVisor в Kubernetes через RuntimeClass\napiVersion: node.k8s.io/v1\nkind: RuntimeClass\nmetadata:\n  name: gvisor\nhandler: runsc\n---\napiVersion: v1\nkind: Pod\nmetadata:\n  name: untrusted-workload-pod\nspec:\n  # Назначение изолированного рантайма gVisor\n  runtimeClassName: gvisor\n  containers:\n  - name: untrusted-app\n    image: my-untrusted-go-code:latest\n    resources:\n      limits:\n        memory: \"256Mi\"\n        cpu: \"1\"\n"
            }
        ],
        "under_the_hood": "gVisor использует платформы аппаратной виртуализации KVM (`--platform=kvm`) или системный перехват ptrace (`--platform=ptrace`). В режиме KVM gVisor создает легковесную виртуальную машину, где Sentry работает на нулевом кольце виртуализированного CPU, а приложение пользователя — на третьем кольце. Системные вызовы процессора `syscall` генерируют VM-Exit прерывание, мгновенно перехватываемое Sentry без единого обращения к хостовому ядру Linux.",
        "pitfalls": "Плата за абсолютную безопасность gVisor — накладные расходы на системные вызовы (Syscall Overhead). Операции, требующие частого переключения контекста и интенсивного файлового ввода-вывода (например, компиляция исходного кода или базы данных с постоянным чтением мелких файлов), могут работать в gVisor в 1.5–2.5 раза медленнее, чем в нативном runc. Для чисто сетевых микросервисов на Go накладные расходы минимальны (менее 5–10%).",
        "bigtech_interview": "Вопрос с архитектурного комитета Ozon: 'В каких сценариях enterprise-систем использование gVisor является строго обязательным?' Ответ: 'В сценариях исполнения **недоверенного кода клиентов (Multi-tenant Untrusted Code Execution)**: например, в облачных сервисах Function-as-a-Service (AWS Lambda / Cloud Functions), платформах интерактивного онлайн-обучения программированию, песочницах запуска сторонних плагинов и обработчиках загруженных пользователями неизвестных PDF/медиафайлов. Если клиентский код содержит 0-day эксплойт побега из контейнера, gVisor полностью локализует атаку внутри пользовательского процесса Sentry на Go.'"
    },
    {
        "num": 28,
        "title": "Интеграция с Fail2Ban для защиты SSH/HTTP: Реактивная динамическая блокировка через iptables",
        "task": "Разработайте комплексную систему реактивной защиты веб-сервиса от DoS-атак и атак перебора паролей (Brute-force) с интеграцией демона Fail2Ban. Напишите Go-сервер, который при неудачных попытках аутентификации или обнаружении подозрительных паттернов запросов генерирует структурированные JSON-логи безопасности со специальными маркерами. Настройте конфигурацию фильтра Fail2Ban (filter.d/go-auth.conf) с регулярным выражением failregex и правило джейла (jail.local) для динамического бана IP-адресов нарушителей на уровне сетевого файрвола iptables / nftables.",
        "theory": "Даже самый производительный веб-сервер на Go тратит процессорные циклы и оперативную память на прием TCP-соединения, TLS-рукопожатие и парсинг HTTP-заголовков. Если атакующий организовал распределенный перебор учетных записей или сканирование уязвимостей, обрабатывать такие запросы на уровне приложения — непозволительная трата ресурсов.\n\n### Реактивная эшелонированная защита с Fail2Ban:\n**Fail2Ban** связывает уровень приложения (Application Layer) с уровнем ядра (Network/OS Layer):\n1. Go-микросервис при фиксации нарушения (например, 5 неверных паролей за 10 секунд с одного IP) пишет в лог запись с маркером безопасности.\n2. Демон Fail2Ban непрерывно инспектирует лог через механизм `inotify`.\n3. Регулярное выражение `failregex` вычисляет IP-адрес нарушителя.\n4. При достижении порога `maxretry` Fail2Ban вызывает команду ядра операционной системы (через `iptables`, `ipset` или `nftables`):\n   ```bash\n   iptables -I INPUT -s <IP> -j DROP\n   ```\n5. Последующие пакеты от атакующего **сбрасываются ядром Linux на аппаратном/сетевом уровне** еще до того, как они дойдут до Go Netpoller и займут файловый дескриптор сокета!\n6. По истечении таймера `bantime` (например, 1 час) Fail2Ban автоматически разблокирует IP.",
        "step_by_step": [
            "Напишите HTTP-сервер на Go с эндпоинтом аутентификации `/api/login`.",
            "При неверном логине/пароле логируйте структурированную запись: `[AUTH_FAIL] IP=<client_ip> user=<username>`.",
            "Сформируйте конфигурационный файл фильтра Fail2Ban `/etc/fail2ban/filter.d/go-app.conf`.",
            "Настройте регулярное выражение `failregex = ^.*\\[AUTH_FAIL\\] IP=<HOST>.*$`.",
            "Сформируйте секцию джейла `/etc/fail2ban/jail.local` с параметрами `bantime = 1h`, `findtime = 10m`, `maxretry = 5`.",
            "Протестируйте фильтрацию утилитой `fail2ban-regex`."
        ],
        "code_blocks": [
            {
                "filename": "main.go",
                "lang": "go",
                "code": "package main\n\nimport (\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"log\"\n\t\"net\"\n\t\"net/http\"\n\t\"os\"\n\t\"strings\"\n\t\"time\"\n)\n\ntype LoginRequest struct {\n\tUsername string `json:\"username\"`\n\tPassword string `json:\"password\"`\n}\n\n// ExtractClientIP извлекает реальный IP клиента с учетом X-Forwarded-For\nfunc ExtractClientIP(r *http.Request) string {\n\txff := r.Header.Get(\"X-Forwarded-For\")\n\tif xff != \"\" {\n\t\tparts := strings.Split(xff, \",\")\n\t\treturn strings.TrimSpace(parts[0])\n\t}\n\thost, _, err := net.SplitHostPort(r.RemoteAddr)\n\tif err != nil {\n\t\treturn r.RemoteAddr\n\t}\n\treturn host\n}\n\nfunc handleLogin(w http.ResponseWriter, r *http.Request) {\n\tif r.Method != http.MethodPost {\n\t\thttp.Error(w, \"Method Not Allowed\", http.StatusMethodNotAllowed)\n\t\treturn\n\t}\n\n\tclientIP := ExtractClientIP(r)\n\n\tvar req LoginRequest\n\tif err := json.NewDecoder(r.Body).Decode(&req); err != nil {\n\t\thttp.Error(w, \"Bad Request\", http.StatusBadRequest)\n\t\treturn\n\t}\n\n\t// Демонстрационная проверка учетных данных\n\tif req.Username == \"admin\" && req.Password == \"super-secret-password-123\" {\n\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n\t\tfmt.Fprintf(w, `{\"status\":\"authenticated\",\"user\":\"%s\"}`, req.Username)\n\t\treturn\n\t}\n\n\t// ВАЖНО: Фиксируем попытку взлома в каноничном формате для Fail2Ban!\n\tlog.Printf(\"[SECURITY] [AUTH_FAIL] IP=%s user=%s reason=invalid_credentials timestamp=%s\",\n\t\tclientIP, req.Username, time.Now().Format(time.RFC3339))\n\n\tw.Header().Set(\"Content-Type\", \"application/json\")\n\tw.WriteHeader(http.StatusUnauthorized)\n\tfmt.Fprintf(w, `{\"error\":\"invalid_credentials\"}`)\n}\n\nfunc main() {\n\tlog.SetOutput(os.Stdout)\n\tfmt.Println(\"=== GO BACKEND С ИНТЕГРАЦИЕЙ С FAIL2BAN ===\")\n\n\thttp.HandleFunc(\"/api/login\", handleLogin)\n\n\tsrv := &http.Server{\n\t\tAddr:         \":8080\",\n\t\tReadTimeout:  5 * time.Second,\n\t\tWriteTimeout: 5 * time.Second,\n\t}\n\n\tlog.Println(\"Сервер слушает на :8080. Логирование неудачных попыток в stdout...\")\n\tif err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {\n\t\tlog.Fatalf(\"Ошибка сервера: %v\", err)\n\t}\n}\n"
            },
            {
                "filename": "go-app.conf",
                "lang": "ini",
                "code": "# /etc/fail2ban/filter.d/go-app.conf\n[Definition]\n# Регулярное выражение для сопоставления с логами Go-приложения\nfailregex = ^.*\\[AUTH_FAIL\\] IP=<HOST>.*$\nignoreregex =\n"
            },
            {
                "filename": "jail.local",
                "lang": "ini",
                "code": "# /etc/fail2ban/jail.local\n[go-auth-jail]\nenabled  = true\nport     = 80,443,8080\nfilter   = go-app\nlogpath  = /var/log/go_service/app.log\nmaxretry = 5\nfindtime = 600\nbantime  = 3600\nbanaction = iptables-multiport\n"
            }
        ],
        "under_the_hood": "Fail2Ban использует модуль `pyinotify` или `gamin` для перехвата системных событий файловой системы ядра Linux `inotify(IN_MODIFY)`. При совпадении с `failregex` Fail2Ban вызывает действие `banaction` (например, `iptables -I f2b-go-auth -s <IP> -j REJECT`). В ядре Linux сетевой пакет от заблокированного IP отбрасывается в цепочке `PREROUTING` таблицы `filter` Netfilter, даже не доходя до очереди сетевого сокета Go-процесса.",
        "pitfalls": "Если веб-сервер находится за обратным прокси-сервером (Nginx, Cloudflare, AWS ALB), поле `r.RemoteAddr` будет содержать IP-адрес самого балансировщика нагрузки! Если заблокировать этот IP через Fail2Ban, сервер заблокирует абсолютно всех пользователей сервиса! Для корректной работы Fail2Ban обязан анализировать заголовок `X-Forwarded-For` только от доверенных прокси, либо Fail2Ban должен работать на уровне самого первого входящего Nginx-шлюза.",
        "bigtech_interview": "Вопрос с собеседования в Лабораторию Касперского: 'Почему при масштабной распределенной DDoS-атаке использование Fail2Ban с классическим iptables может ухудшить ситуацию и как решить проблему?' Ответ: 'Fail2Ban для каждого заблокированного IP добавляет отдельное линейное правило в цепочку iptables. При бане 50 000 IP-адресов ядро Linux вынуждено выполнять линейный перебор 50 000 правил для каждого входящего сетевого пакета, что приводит к 100% загрузке ядер CPU программными прерываниями (softirq). Решение — использовать `ipset` (хэш-таблицы в памяти ядра, проверка за O(1)) через действие `banaction = iptables-ipset`, либо переходить на современный `nftables` или сброс пакетов через `eBPF XDP`.'"
    }
]
