# -*- coding: utf-8 -*-
exercises = [
  {
    "num": 1,
    "title": "Анализ машинного кода и хот-спотов через go tool objdump",
    "task": "Напишите функцию суммирования элементов среза `SumSlice([]int64) int64`. Изучите сгенерированный ассемблерный код с помощью флагов компилятора `go build -gcflags=\"-S\"` и утилиты `go tool objdump`. Выявите инструкции цикла, проверки границ (bounds checks) и накладные расходы пролога/эпилога функции.",
    "theory": "При оптимизации критических путей выполнения (Hot Paths) в высоконагруженных Go-сервисах инженер обязан понимать, в какой именно машинный код компилятор транслирует конструкции языка.\n\n**Инструменты исследования ассемблерного кода Go:**\n1. **Флаги компилятора `go build -gcflags=\"-S\"`**:\n   Выводит промежуточное ассемблерное представление Plan 9, используемое внутренним генератором кода Go. Показывает псевдорегистры (`SB`, `FP`, `SP`), директивы фрейма (`TEXT`, `FUNCDATA`, `PCDATA`) и вызовы вспомогательных функций рантайма.\n2. **Утилита `go tool objdump`**:\n   Дизассемблирует уже готовый скомпилированный бинарный файл ELF/Mach-O/PE. Показывает реальные физические инструкции процессора (x86_64: `ADDQ`, `MOVQ`, `JNE`, `CMPQ`) с шестнадцатеричными смещениями и привязкой к строкам исходного Go-кода:\n   ```bash\n   go tool objdump -s \"main\\.SumSlice\" ./mybinary\n   ```\n3. **Флаги SSA (Static Single Assignment) `-gcflags=\"-d=ssa/prove/debug=1\"`**:\n   Позволяют наблюдать все 40+ фаз оптимизации компилятора: от абстрактного синтаксического дерева (AST) до финального распределения физических регистров.",
    "step_by_step": "1. Напишите функцию `SumSlice(data []int64) int64`.\n2. Реализуйте симулятор анализа ассемблерного листинга в `main.go`.\n3. Разберите структуру сгенерированного машинного кода цикла: инициализацию аккумулятора в регистре `AX`, загрузку адреса базового массива среза в регистр `DX`, проверку длины и условный переход `JNE`.\n4. Объясните назначение инструкций `PCDATA` и `FUNCDATA` для сборщика мусора (GC Safepoints).\n5. Запустите программу и проанализируйте вывод ассемблерного сопоставления.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\n// SumSlice суммирует 64-битные целые числа в срезе.\n//\n//go:noinline\nfunc SumSlice(data []int64) int64 {\n\tvar sum int64\n\tfor i := 0; i < len(data); i++ {\n\t\tsum += data[i]\n\t}\n\treturn sum\n}\n\n// DisassemblyOverview демонстрирует структуру ассемблера,\n// генерируемого компилятором Go для SumSlice на архитектуре AMD64:\n//\n// \"\".SumSlice STEXT nosplit size=46 args=0x18 locals=0x0 funcid=0x0\n//   0x0000 00000 (main.go:12)  XORL    AX, AX           // sum = 0 (AX - регистр возвращаемого значения)\n//   0x0002 00002 (main.go:12)  XORL    CX, CX           // i = 0 (CX - регистр счетчика цикла)\n//   0x0004 00004 (main.go:12)  JMP     0x0016           // переход к проверке i < len(data)\n//   0x0006 00006 (main.go:13)  ADDQ    (DX)(CX*8), AX   // sum += data[i] (база в DX, смещение CX*8)\n//   0x000a 00010 (main.go:12)  INCQ    CX               // i++\n//   0x000d 00013 (main.go:12)  CMPQ    CX, BX           // сравнение i с len(data) (длина в BX)\n//   0x0010 00016 (main.go:12)  JLT     0x0006           // если i < len, переход на тело цикла\n//   0x0012 00018 (main.go:15)  RET                      // возврат (результат в AX)\n\nfunc main() {\n\tdata := make([]int64, 100000)\n\tfor i := range data {\n\t\tdata[i] = int64(i + 1)\n\t}\n\n\tstart := time.Now()\n\ttotal := SumSlice(data)\n\tdur := time.Since(start)\n\n\tfmt.Println(\"=== Go Tool Objdump & Assembly Analysis ===\")\n\tfmt.Printf(\"Elements: %d | Sum: %d | Time: %v\\n\", len(data), total, dur)\n\tfmt.Println(\"1. Register ABI: data.ptr in DX, data.len in BX, data.cap in CX\")\n\tfmt.Println(\"2. Inner Loop: single ADDQ (DX)(CX*8), AX instruction without stack spills\")\n\tfmt.Println(\"3. Bounds check eliminated by compiler due to standard for i < len loop pattern\")\n}\n",
        "note": "Анализ машинного кода цикла суммирования среза и регистрового соглашения Go."
      }
    ],
    "under_the_hood": "В современных версиях Go (начиная с 1.17) действует **Register-based Calling Convention (ABIInternal)**. Аргумент среза `[]int64` передается не через стек, а сразу в трех регистрах: `DX` (указатель на массив), `BX` (длина `len`) и `DI` (емкость `cap`). Результат возвращается в `AX`. В теле цикла компилятор полностью устраняет обращения к памяти стека, сохраняя счетчик `i` и аккумулятор `sum` в регистрах процессора.",
    "pitfalls": "1. Отсутствие директивы `//go:noinline`: при профилировании коротких функций компилятор может встроить (inline) их в точку вызова, из-за чего в `objdump` не удастся найти отдельный символ функции.\n2. Проверки границ (Bounds Checks): если цикл написан нестандартно (например, `for i := 0; i <= len(s)-1; i++`), компилятор может вставить инструкцию `CMPQ` с вызовом `runtime.panicIndex`, что замедлит hot path на 30–50%.",
    "bigtech_interview": "В Yandex Infrastructure и VK Core часто спрашивают: «Как с помощью утилит командной строки быстро найти самую горячую ассемблерную инструкцию в Go-сервисе под нагрузкой?». Ответ: снять профиль CPU через `perf record -g ./service`, затем открыть интерактивный ассемблерный анализатор `perf annotate <symbol>`, где рядом с каждой машинной инструкцией отображается точный процент тактов процессора (Samples %)."
  },
  {
    "num": 2,
    "title": "Соглашения о вызовах в Go: Стек ABI0 против Регистров ABIInternal",
    "task": "Изучите эволюцию соглашений о вызовах (Calling Conventions) в рантайме Go: переход от стекового соглашения ABI0 к регистровому ABIInternal. Объясните, как передаются аргументы и возвращаются значения, и почему рукописный ассемблер требует адаптеров или директивы pragma.",
    "theory": "Исторически Go использовал архитектуру компилятора Plan 9 со **стековым соглашением о вызовах (Stack-based ABI0)**:\n- Все аргументы функции и возвращаемые значения помещались в оперативную память стека текущей горутины (`SP + offset`).\n- Плюсы: максимальная простота кодогенерации и интроспекции рантайма (сборка мусора видит все указатели в стеке через stack maps).\n- Минусы: каждая операция вызова функции требовала серий инструкций записи в память `MOVQ AX, 0(SP)` и чтения из памяти `MOVQ 8(SP), BX`, что приводило к колоссальному оверхеду даже при наличии L1-кэша.\n\n**Революция Go 1.17+: Регистровое соглашение (ABIInternal)**\nКомпилятор перешел на передачу аргументов через регистры процессора общего назначения и регистры XMM:\n- Целочисленные аргументы и указатели: последовательно в регистрах `RAX`, `RBX`, `RCX`, `RDI`, `RSI`, `R8`, `R9`, `R10`, `R11` (до 9 регистров).\n- Числа с плавающей точкой (`float32`, `float64`): в векторных регистрах `X0`–`X14` (до 15 регистров).\n- Если параметров больше, чем свободных регистров, остаток передается через стек.\n- **Прирост производительности**: автоматическое ускорение всех Go-программ на 5–15% без изменения кода!\n\n**Проблема рукописного ассемблера (.s)**:\nВсе рукописные функции на ассемблере Plan 9 по умолчанию линкуются как **ABI0** (ожидают аргументы на стеке). Чтобы вызвать Go-функцию (ABIInternal) из ассемблера или наоборот, линкер компилятора Go генерирует специальный переходник — **ABI Wrapper (Thunk)**, копирующий регистры в стек и обратно.",
    "step_by_step": "1. Создайте структуру демонстрации смещений аргументов в стеке ABI0.\n2. Проиллюстрируйте, как в ABI0 аргументы `a, b int64` располагаются по смещениям `0(FP)` и `8(FP)`, а возвращаемое значение — по `16(FP)`.\n3. Проиллюстрируйте эквивалентную схему ABIInternal, где `a` передается в `AX`, `b` в `BX`, а результат возвращается в `AX`.\n4. Объясните назначение линкерных символов `·MyFunc(SB)` и псевдорегистра `FP` (Frame Pointer).\n5. Напишите тесты и выведите подробную карту раскладки регистров.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n)\n\n// ABIDemonstrator иллюстрирует разницу между ABI0 и ABIInternal\ntype ABIDemonstrator struct{}\n\n// Пример сигнатуры: func Add(a, b int64) int64\n//\n// В стековом ABI0 (устаревший / рукописный .s по умолчанию):\n//   Память стека вызывающего:\n//   SP + 0x00: аргумент 'a' (8 байт)  -> в asm: a+0(FP)\n//   SP + 0x08: аргумент 'b' (8 байт)  -> в asm: b+8(FP)\n//   SP + 0x10: возврат 'ret' (8 байт) -> в asm: ret+16(FP)\n//   Фрейм функции: $0-24 (0 байт локальных переменных, 24 байта аргументов)\n//\n// В регистровом ABIInternal (Go 1.17+):\n//   Регистр RAX: аргумент 'a'\n//   Регистр RBX: аргумент 'b'\n//   Регистр RAX: возвращаемое значение (перезаписывается при выходе)\n//   Стек: НЕ ИСПОЛЬЗУЕТСЯ (zero memory traffic!)\n\n//go:noinline\nfunc EmulatedABIInternalAdd(a, b int64) int64 {\n\t// В скомпилированном виде на AMD64:\n\t// ADDQ RBX, RAX\n\t// RET\n\treturn a + b\n}\n\nfunc main() {\n\tfmt.Println(\"=== Go Calling Conventions: ABI0 vs ABIInternal ===\")\n\tfmt.Println(\"Architecture: AMD64 (x86-64)\")\n\tfmt.Println(\"-------------------------------------------------------\")\n\tfmt.Println(\"Parameter Register Mapping (ABIInternal):\")\n\tfmt.Println(\"  GPR Integer/Pointer: RAX, RBX, RCX, RDI, RSI, R8, R9, R10, R11\")\n\tfmt.Println(\"  FPR Floating Point:  X0 - X14\")\n\tfmt.Println(\"-------------------------------------------------------\")\n\n\tres := EmulatedABIInternalAdd(42, 58)\n\tfmt.Printf(\"Result: %d\\n\", res)\n\tfmt.Println(\"ABI Wrapper: Linker automatically synthesizes ABI wrappers\")\n\tfmt.Println(\"when Go code calls assembly functions defined without ABIInternal pragmas.\")\n}\n",
        "note": "Сравнение схемы размещения параметров в стеке ABI0 и регистрах ABIInternal."
      }
    ],
    "under_the_hood": "Внутренний линкер Go (`cmd/link`) при обнаружении вызова между кодом с разными ABI вставляет синтетические функции `abi0 -> abiInternal` и `abiInternal -> abi0`. В ассемблерных файлах Go 1.18+ можно явно декларировать ABI через директиву pragma `//go:registerparams` или ассемблерный тег `<ABIInternal>`, что исключает накладные расходы на адаптер.",
    "pitfalls": "1. Ошибочные смещения псевдорегистра `FP`: в Plan 9 `FP` (Frame Pointer) виртуален. Если не указать имя аргумента `arg+0(FP)`, компилятор выдаст ошибку `unknown variable`.\n2. Повреждение callee-save регистров: в ABIInternal большинство регистров являются caller-save (уничтожаются вызовом функции), но регистр `g` (указатель на текущую горутину) фиксирован в `R14` и его модификация приведет к мгновенному краху рантайма!",
    "bigtech_interview": "«Почему регистр R14 на архитектуре amd64 зарезервирован в Go?». Ответ: в Go регистр `R14` постоянно хранит указатель на структуру текущей горутины (`*g`). Это позволяет любой функции мгновенно обращаться к полям горутины (стек, планировщик, m) без выполнения медленного системного вызова получения Thread-Local Storage (TLS) через сегментные регистры `FS`/`GS`."
  },
  {
    "num": 3,
    "title": "Устранение проверок границ слайсов (Bounds Check Elimination — BCE)",
    "task": "Изучите механизм проверки границ срезов и строк в Go. Напишите программу, демонстрирующую оптимизацию Bounds Check Elimination (BCE) с помощью отладочного флага компилятора `-gcflags=\"-d=ssa/check_bce/debug=1\"`, и докажите устранение инструкций `runtime.panicIndex`.",
    "theory": "Язык Go гарантирует типобезопасность и безопасность памяти: любое обращение к элементу среза по индексу `s[i]` проверяется на этапе выполнения. Если $i \\ge \\text{len}(s)$ или $i < 0$, рантайм вызывает панику `runtime.panicIndex`.\n\nНа уровне ассемблера каждое непроверенное обращение превращается в:\n```asm\nCMPQ CX, BX        // сравнить i с len\nJAE  panic_index   // если i >= len, перейти на панику\nMOVQ (DX)(CX*8), AX\n```\nВнутри вложенных матричных циклов или алгоритмов шифрования постоянные проверки `CMPQ + JAE` раздувают размер кода, забивают таблицу предсказания переходов (Branch Target Buffer) и мешают аппаратной векторизации конвейера CPU.\n\n**Bounds Check Elimination (BCE)** — фаза SSA-компилятора Go (`prove`), которая математически доказывает безопасность обращений и удаляет лишние проверки:\n1. **Идиоматичный цикл**: в `for i := 0; i < len(s); i++` компилятор доказывает, что `i` строго меньше `len(s)`, и проверки внутри тела цикла полностью устраняются.\n2. **Ранний намек компилятору (Early Bounds Hint)**:\n   Если функции требуется доступ к `s[0]`, `s[1]`, `s[2]`, достаточно в начале функции один раз обратиться к самому дальнему индексу:\n   ```go\n   _ = s[2] // компилятор делает 1 проверку\n   a := s[0] // проверка устранена (BCE)!\n   b := s[1] // проверка устранена (BCE)!\n   c := s[2] // проверка устранена (BCE)!\n   ```\n   Вместо трех проверок в цикле генерируется ровно одна!",
    "step_by_step": "1. Напишите функцию `NaiveSum(s []byte) uint32` с повторными проверками.\n2. Напишите оптимизированную функцию `OptimizedBceSum(s []byte) uint32` с идиоматичной фиксацией длины `_ = s[3]`.\n3. Создайте алгоритм парсинга 4-байтного заголовка сетевого пакета (Big-Endian uint32).\n4. Проведите бенчмарк обеих функций на 10 000 000 итераций.\n5. Продемонстрируйте вывод флага `-d=ssa/check_bce/debug=1`.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\n// ReadUint32Naive выполняет 4 проверки границ при чтении 4 байт\n//\n//go:noinline\nfunc ReadUint32Naive(b []byte) uint32 {\n\t// Компилятор вставит проверку границ для каждого индекса:\n\treturn uint32(b[0])<<24 |\n\t\tuint32(b[1])<<16 |\n\t\tuint32(b[2])<<8 |\n\t\tuint32(b[3])\n}\n\n// ReadUint32Optimized устраняет 3 из 4 проверок границ благодаря BCE\n//\n//go:noinline\nfunc ReadUint32Optimized(b []byte) uint32 {\n\t// Доказываем компилятору, что срез имеет длину не менее 4 байт:\n\t_ = b[3] // 1 проверка границ здесь!\n\n\t// Следующие чтения гарантированно безопасны, проверки BCE удалены:\n\treturn uint32(b[0])<<24 |\n\t\tuint32(b[1])<<16 |\n\t\tuint32(b[2])<<8 |\n\t\tuint32(b[3])\n}\n\nfunc main() {\n\tpacket := []byte{0x00, 0x01, 0xE2, 0x40} // 123456 в hex\n\n\tconst iterations = 50000000\n\n\t// 1. Naive benchmark\n\tstart1 := time.Now()\n\tvar sum1 uint32\n\tfor i := 0; i < iterations; i++ {\n\t\tsum1 += ReadUint32Naive(packet)\n\t}\n\tdur1 := time.Since(start1)\n\n\t// 2. Optimized BCE benchmark\n\tstart2 := time.Now()\n\tvar sum2 uint32\n\tfor i := 0; i < iterations; i++ {\n\t\tsum2 += ReadUint32Optimized(packet)\n\t}\n\tdur2 := time.Since(start2)\n\n\tfmt.Println(\"=== Bounds Check Elimination (BCE) Evaluation ===\")\n\tfmt.Printf(\"Naive Time:     %v (%.2f ns/op)\\n\", dur1, float64(dur1.Nanoseconds())/iterations)\n\tfmt.Printf(\"Optimized Time: %v (%.2f ns/op)\\n\", dur2, float64(dur2.Nanoseconds())/iterations)\n\tif dur1 > dur2 {\n\t\tfmt.Printf(\"BCE Speedup:    %.2fx faster\\n\", float64(dur1)/float64(dur2))\n\t}\n\tfmt.Println(\"\\nTo inspect BCE proofs run: go build -gcflags=\\\"-d=ssa/check_bce/debug=1\\\" main.go\")\n\n\tif sum1 != sum2 {\n\t\tpanic(\"integrity error\")\n\t}\n}\n",
        "note": "Техника ранней проверки границ (_ = b[3]) для устранения промежуточных bounds checks."
      }
    ],
    "under_the_hood": "В компиляторе Go фаза `prove` строит решетку неравенств (Domain-bounds lattice). Когда компилятор встречает выражение `_ = b[3]`, он сохраняет доказанный факт: `len(b) > 3`. При анализе следующих инструкций `b[0]`, `b[1]`, `b[2]` компилятор видит, что константные индексы $0, 1, 2 \\le 3 < \\text{len}(b)$, поэтому машинные инструкции `CMPQ` и вызовы `panicIndex` просто не генерируются.",
    "pitfalls": "1. Оптимизация без проверки профилировщиком: хаотичное добавление `_ = s[N]` усложняет чтение кода и не дает эффекта вне ультра-горячих циклов.\n2. Пропуск граничного случая `len < 4`: если в оптимизированную функцию передать срез длиной 2 байта, паника произойдет на строке `_ = b[3]`, что является ожидаемым поведением.",
    "bigtech_interview": "«Как в стандартном пакете encoding/binary реализована функция binary.BigEndian.Uint32(b)?». Ответ: ровно через паттерн `_ = b[3]` с последующим битовым сдвигом `b[0]<<24 | b[1]<<16 | b[2]<<8 | b[3]`. Это позволяет компилятору соптимизировать всю функцию в одну инструкцию `BSWAPL` (Byte Swap) на процессорах x86_64!"
  },
  {
    "num": 4,
    "title": "Архитектура Plan 9 Assembly и первая функция на ассемблере Go",
    "task": "Изучите синтаксис ассемблера Plan 9, принятого в Go. Реализуйте и разберите ассемблерную функцию сложения `Add(x, y int) int`, связываемую с декларацией в Go без тела. Объясните назначение флагов NOSPLIT, директивы TEXT и спецификации фрейма `$0-24`.",
    "theory": "Ассемблер Go не использует синтаксис Intel или AT&T. Он происходит от операционной системы **Plan 9 from Bell Labs**, созданной авторами C и Unix (Кен Томпсон, Роб Пайк).\n\n**Главные отличия Plan 9 Assembly:**\n1. **Порядок операндов**: источник слева, приемник справа:\n   `ADDQ AX, BX` означает `BX = BX + AX` (как в AT&T, но без префиксов `%` и `$`).\n2. **Псевдорегистры (Pseudo-registers)**:\n   - `SB` (Static Base): глобальные переменные и функции. Имя `foo(SB)` означает символ в глобальной таблице. Средняя точка `·` (Unicode `U+00B7`) отделяет имя пакета: `·Add(SB)`.\n   - `FP` (Frame Pointer): виртуальный указатель на аргументы функции, переданные вызывающим кодом.\n   - `SP` (Stack Pointer): локальный стек функции. Если перед `SP` стоит имя переменной `x-8(SP)`, это псевдорегистр. Если без имени `-8(SP)`, это физический аппаратный стек.\n3. **Декларация функции (Директива `TEXT`)**:\n   ```asm\n   TEXT ·Add(SB), NOSPLIT, $0-24\n   ```\n   - `TEXT ·Add(SB)`: объявление символа функции.\n   - `NOSPLIT`: запрет компилятору вставлять проверку переполнения стека горутины (Stack Split Check).\n   - `$0-24`: фрейм функции. Число перед дефисом (`$0`) — размер локальных переменных на стеке. Число после дефиса (`24`) — суммарный размер входящих аргументов и возвращаемых значений (два `int` по 8 байт + один результат `int` 8 байт = 24 байта).",
    "step_by_step": "1. Создайте структуру демонстрации связывания Go и Plan 9 ассемблера.\n2. Подробно опишите файл `add_amd64.s` с инструкциями загрузки из `FP`, сложения и записи в возвращаемое значение.\n3. Объясните разницу между 32-битными (`MOVL`, `ADDL`) и 64-битными (`MOVQ`, `ADDQ`) инструкциями.\n4. Разберите механизм предотвращения сплита стека (`NOSPLIT`) и размер кванта стека горутины (2 КБ).\n5. Напишите эмулятор вызова ассемблерной функции в среде Go.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n)\n\n// В реальном проекте объявление связывается с файлом add_amd64.s:\n//\n// package main\n// func AsmAdd(x, y int64) int64\n//\n// Файл add_amd64.s:\n// #include \"textflag.h\"\n//\n// // func AsmAdd(x, y int64) int64\n// TEXT ·AsmAdd(SB), NOSPLIT, $0-24\n//     MOVQ x+0(FP), AX    // Загрузка первого аргумента x в регистр AX\n//     MOVQ y+8(FP), BX    // Загрузка второго аргумента y в регистр BX\n//     ADDQ BX, AX         // AX = AX + BX\n//     MOVQ AX, ret+16(FP) // Запись суммы в слот возвращаемого значения\n//     RET                 // Возврат из функции\n\n// EmulatedAsmAdd симулирует поведение ассемблерной инструкции Plan 9 ADDQ\nfunc EmulatedAsmAdd(x, y int64) int64 {\n\t// В регистрах x86_64:\n\t// MOVQ x, AX\n\t// ADDQ y, AX\n\t// MOVQ AX, ret\n\treturn x + y\n}\n\nfunc main() {\n\tfmt.Println(\"=== Plan 9 Go Assembly Primer ===\")\n\tfmt.Println(\"Directives:\")\n\tfmt.Println(\"  TEXT ·Func(SB): Global function symbol entry\")\n\tfmt.Println(\"  NOSPLIT:        Do not emit stack allocation preamble\")\n\tfmt.Println(\"  $FrameSize-ArgSize: $0-24 indicates 0 stack locals, 24 bytes args\")\n\tfmt.Println(\"Pseudo-registers:\")\n\tfmt.Println(\"  FP: Frame Pointer for function arguments (virtual)\")\n\tfmt.Println(\"  SB: Static Base pointing to global symbols\")\n\tfmt.Println(\"  SP: Stack Pointer pointing to local frame\")\n\n\ta, b := int64(100), int64(250)\n\tresult := EmulatedAsmAdd(a, b)\n\tfmt.Printf(\"\\nOperation: %d + %d = %d\\n\", a, b, result)\n}\n",
        "note": "Структура Plan 9 ассемблерного файла и семантика псевдорегистров Go."
      }
    ],
    "under_the_hood": "Символ точки `·` в Plan 9 ассемблере на этапе линковки заменяется именем текущего пакета (например, `main`). Если в директиве `TEXT` не указать флаг `NOSPLIT`, компилятор Go при входе в функцию сгенерирует инструкции `CMPQ SP, (R14)` (сравнение `SP` со `stackguard` текущей горутины в регистре `R14`) и вызов `runtime.morestack` при исчерпании 2 КБ стека.",
    "pitfalls": "1. Превышение лимита стека с `NOSPLIT`: функции с флагом `NOSPLIT` имеют жесткое аппаратное ограничение на размер фрейма (не более `_StackLimit` ~ 792 байт). Превышение приведет к разрушению стека соседней горутины без возможности восстановления.\n2. Неверный размер `$Locals-Args`: если указать неверный размер аргументов (например, `$0-16` вместо `$0-24`), сборщик мусора Go (GC) не сможет корректно построить карту живых указателей стека, что вызовет фатальный сбой памяти.",
    "bigtech_interview": "«Почему в Plan 9 ассемблере перед именами аргументов обязательно писать имена параметров, например `x+0(FP)`, а не просто `0(FP)`?». Ответ: компилятор Go строго сверяет имена аргументов в ассемблерном файле с декларацией в `.go` файле. Если сигнатура функции в Go изменится, а ассемблерный файл не обновят, линкер выбросит ошибку несоответствия сигнатуры, предотвращая передачу поврежденных данных."
  },
  {
    "num": 5,
    "title": "Условные переходы и Branchless CMOV в ассемблере Plan 9",
    "task": "Реализуйте функцию поиска максимума двух чисел `Max(a, b int64) int64`. Сравните классическую реализацию с условным переходом (`JGT` / `JLE`) и оптимизированную безветвящуюся версию на базе процессорной инструкции условной пересылки `CMOVQGT` (Conditional Move).",
    "theory": "В современных конвейерных процессорах (Intel Core, AMD Zen, Apple Silicon) глубина конвейера составляет от 14 до 20 стадий.\n\n**Проблема условных переходов (Branch Misprediction):**\n- При встрече инструкции условного перехода `CMPQ + JGT` процессор задействует блок предсказания переходов (Branch Predictor).\n- Если данные случайны (например, сравнение случайных чисел), предсказатель ошибается примерно в 50% случаев.\n- При ошибке предсказания (Branch Misprediction Penalty) конвейер процессора принудительно сбрасывается, все спекулятивно вычисленные инструкции уничтожаются, а процессор простаивает **15–20 тактов**!\n\n**Решение: Инструкции условной пересылки CMOV (Conditional Move)**\nИнструкция `CMOVQGT BX, AX` переносит значение регистра `BX` в `AX` только в том случае, если флаг процессора `GT` (Greater Than) выставлен после предыдущего `CMPQ`.\n- В коде **нет инструкции перехода** (`JMP/JGT`).\n- Конвейер выполняется строго линейно.\n- Время выполнения: ровно **1 такт процессора** независимо от случайности входных данных!",
    "step_by_step": "1. Напишите функцию `MaxBranching(a, b int64) int64` с обычным ветвлением.\n2. Напишите безветвящуюся функцию `MaxBranchless(a, b int64) int64` через битовую арифметику или CMOV.\n3. Сгенерируйте массив случайных чисел для максимальной нагрузки на Branch Predictor.\n4. Проведите сравнительный замер времени выполнения на 20 000 000 итераций.\n5. Продемонстрируйте превосходство branchless подхода.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"math/rand\"\n\t\"time\"\n)\n\n// MaxBranching использует условный переход:\n//\n// CMPQ a, b\n// JLE  ret_b\n// MOVQ a, ret\n// RET\n//\n//go:noinline\nfunc MaxBranching(a, b int64) int64 {\n\tif a > b {\n\t\treturn a\n\t}\n\treturn b\n}\n\n// MaxBranchless симулирует инструкцию CMOV (Conditional Move):\n//\n// MOVQ a+0(FP), AX\n// MOVQ b+8(FP), BX\n// CMPQ AX, BX\n// CMOVQLE BX, AX  // Если AX <= BX, копируем BX в AX (без прыжков!)\n// MOVQ AX, ret+16(FP)\n// RET\n//\n//go:noinline\nfunc MaxBranchless(a, b int64) int64 {\n\tdiff := a - b\n\t// На 64-битных системах знаковый сдвиг копирует старший бит знака\n\tsignMask := diff >> 63 // 0 если a >= b; -1 (все единицы) если a < b\n\treturn a - (diff & signMask)\n}\n\nfunc main() {\n\tconst n = 20000000\n\tdataA := make([]int64, n)\n\tdataB := make([]int64, n)\n\n\t// Заполняем абсолютно случайными числами для провокации Branch Misprediction\n\tr := rand.New(rand.NewSource(time.Now().UnixNano()))\n\tfor i := 0; i < n; i++ {\n\t\tdataA[i] = r.Int63n(10000)\n\t\tdataB[i] = r.Int63n(10000)\n\t}\n\n\t// 1. Тест с ветвлением\n\tstart1 := time.Now()\n\tvar sum1 int64\n\tfor i := 0; i < n; i++ {\n\t\tsum1 += MaxBranching(dataA[i], dataB[i])\n\t}\n\tdur1 := time.Since(start1)\n\n\t// 2. Тест без ветвления (Branchless)\n\tstart2 := time.Now()\n\tvar sum2 int64\n\tfor i := 0; i < n; i++ {\n\t\tsum2 += MaxBranchless(dataA[i], dataB[i])\n\t}\n\tdur2 := time.Since(start2)\n\n\tfmt.Println(\"=== Branching vs Branchless (CMOV) Benchmark ===\")\n\tfmt.Printf(\"Iterations: %d unpredictable comparisons\\n\", n)\n\tfmt.Printf(\"Branching Max:  %v (%.2f ns/op)\\n\", dur1, float64(dur1.Nanoseconds())/n)\n\tfmt.Printf(\"Branchless Max: %v (%.2f ns/op)\\n\", dur2, float64(dur2.Nanoseconds())/n)\n\tif dur1 > dur2 {\n\t\tfmt.Printf(\"Branchless Speedup: %.2fx faster due to zero branch mispredictions!\\n\", float64(dur1)/float64(dur2))\n\t}\n\n\tif sum1 != sum2 {\n\t\tpanic(\"results mismatch\")\n\t}\n}\n",
        "note": "Сравнение производительности условного перехода и branchless реализации CMOV."
      }
    ],
    "under_the_hood": "Инструкция `CMOVcc` появилась еще в архитектуре Intel Pentium Pro (1995 г.). В Plan 9 ассемблере Go поддерживаются мнемоники `CMOVQEQ`, `CMOVQNE`, `CMOVQLT`, `CMOVQGT`, `CMOVQLE`, `CMOVQGE`. При компиляции Go-кода компилятор самостоятельно пытается заменить простые тернарные операторы `if/else` на инструкции CMOV, если ветви не содержат вызовов функций и аллокаций.",
    "pitfalls": "1. Скрытые зависимости по данным: хотя CMOV устраняет предсказание переходов, он вводит зависимость по данным от обоих операндов. Если вычисление одного из операндов занимает много тактов (например, промах кэша), CMOV будет ждать завершения обоих потоков данных.\n2. Деление на ноль и разыменование null: в конструкции `val := a != nil ? *a : 0` нельзя использовать CMOV, так как оба аргумента должны быть безопасно вычислены заранее.",
    "bigtech_interview": "«Как утилита perf stat на Linux измеряет качество предсказания переходов?». Ответ: через аппаратные счетчики производительности (Performance Monitoring Counters — PMC): `branch-instructions` (общее число условных и безусловных переходов) и `branch-misses` (число промахов предсказателя). Отношение `branch-misses / branch-instructions > 5%` сигнализирует о серьезных проблемах с ветвлением в коде."
  },
  {
    "num": 6,
    "title": "Анатомия ассемблерного файла Go: фреймы стека, псевдорегистры SB/FP/SP",
    "task": "Создайте полноценную связку файла Go и ассемблерного файла Plan 9 `add.s`. Реализуйте математические операции сложения и вычитания двух 64-битных целых чисел, разберите правила выравнивания памяти фрейма стека и псевдорегистров.",
    "theory": "При написании рукописного ассемблерного кода в проекте Go файлы организуются по строгим правилам:\n1. Имя файла обязано содержать суффикс целевой архитектуры: `add_amd64.s`, `add_arm64.s`.\n2. В начале ассемблерного файла подключается заголовочный файл `#include \"textflag.h\"`.\n3. В файле Go объявляется сигнатура функции без тела:\n   `func AddSub(a, b int64) (sum int64, diff int64)`\n\n**Спецификация смещений памяти в Plan 9:**\nДля функции `AddSub(a, b int64) (sum int64, diff int64)`:\n- Аргумент `a`: `a+0(FP)` (байты 0..7)\n- Аргумент `b`: `b+8(FP)` (байты 8..15)\n- Возвращаемое значение `sum`: `sum+16(FP)` (байты 16..23)\n- Возвращаемое значение `diff`: `diff+24(FP)` (байты 24..31)\n- Итоговый размер аргументов: $8 + 8 + 8 + 8 = 32$ байта.\n- Сигнатура `TEXT`: `TEXT ·AddSub(SB), NOSPLIT, $0-32`\n\n**Различие между аппаратным и псевдорегистром SP:**\n- `symbol+offset(SP)` (с именем символа) — обращение к локальной переменной фрейма (псевдорегистр).\n- `+offset(SP)` (без имени) — прямое обращение к верхушке аппаратного стека процессора.",
    "step_by_step": "1. Создайте структуру моделирования вызовов низкоуровневого ассемблерного модуля.\n2. Продемонстрируйте синтаксис файла `add_amd64.s` с двумя возвращаемыми значениями.\n3. Опишите флаги `textflag.h`: `NOSPLIT`, `RODATA`, `NOPROF`, `DUPOK`.\n4. Напишите Go-обертку и верифицируйте расчет суммы и разности.\n5. Выведите карту раскладки памяти фрейма стека.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n)\n\n// Демонстрация файла add_amd64.s:\n//\n// #include \"textflag.h\"\n//\n// // func AddSubAsm(a, b int64) (sum int64, diff int64)\n// TEXT ·AddSubAsm(SB), NOSPLIT, $0-32\n//     // 1. Вычисление суммы\n//     MOVQ a+0(FP), AX     // AX = a\n//     MOVQ b+8(FP), BX     // BX = b\n//     MOVQ AX, CX          // Сохраняем копию a в CX для вычитания\n//     ADDQ BX, AX          // AX = a + b\n//     MOVQ AX, sum+16(FP)  // Сохраняем первый результат\n//\n//     // 2. Вычисление разности\n//     SUBQ BX, CX          // CX = a - b\n//     MOVQ CX, diff+24(FP) // Сохраняем второй результат\n//     RET\n\n// EmulatedAddSub выполняет логику инструкций Plan 9\nfunc EmulatedAddSub(a, b int64) (sum int64, diff int64) {\n\tsum = a + b\n\tdiff = a - b\n\treturn\n}\n\nfunc main() {\n\tfmt.Println(\"=== Plan 9 Stack Frame & Argument Layout ===\")\n\tfmt.Println(\"TEXT ·AddSubAsm(SB), NOSPLIT, $0-32\")\n\tfmt.Println(\"Memory Layout on Stack (offsets from FP):\")\n\tfmt.Println(\"  +0x00: a    (int64, input)\")\n\tfmt.Println(\"  +0x08: b    (int64, input)\")\n\tfmt.Println(\"  +0x10: sum  (int64, return 1)\")\n\tfmt.Println(\"  +0x18: diff (int64, return 2)\")\n\tfmt.Println(\"Total Arg Size: 32 bytes | Local Frame: 0 bytes\")\n\n\tx, y := int64(150), int64(45)\n\tsum, diff := EmulatedAddSub(x, y)\n\tfmt.Printf(\"\\nInputs: a=%d, b=%d\\n\", x, y)\n\tfmt.Printf(\"Outputs: sum=%d, diff=%d\\n\", sum, diff)\n}\n",
        "note": "Анатомия многопараметрического фрейма стека в ассемблере Plan 9."
      }
    ],
    "under_the_hood": "Заголовочный файл `textflag.h` содержит макросы препроцессора компилятора Go: `NOSPLIT = 4` (не проверять переполнение стека), `RODATA = 8` (разместить данные в секции read-only данных), `DUPOK = 2` (разрешить дублирование символов в разных объектных файлах). Препроцессор Go (`cmd/asm`) обрабатывает C-подобные директивы `#include`, `#define`, `#ifdef`.",
    "pitfalls": "1. Забытый `textflag.h`: если использовать константу `NOSPLIT` без подключения `#include \"textflag.h\"`, компилятор ассемблера завершится с ошибкой `undefined identifier: NOSPLIT`.\n2. Нарушение 8-байтного выравнивания: на архитектуре x86_64 аргументы базовых типов выравниваются по 8 байт. Если первым аргументом идет `int32`, а вторым `int64`, между ними возникнет 4-байтный padding, который обязан быть учтен в смещении `+8(FP)`.",
    "bigtech_interview": "«Чем псевдорегистр SB отличается от обычных аппаратных регистров?». Ответ: `SB` (Static Base) — это виртуальный регистр глобальной памяти всей программы. Запись `foo(SB)` указывает компоновщику связать это имя с адресом глобального символа `foo` в таблице символов бинарного файла."
  },
  {
    "num": 7,
    "title": "Высокопроизводительное копирование памяти: FastCopy на Assembly и Unsafe",
    "task": "Разработайте высокоскоростную функцию копирования байтовых срезов `FastCopy(dst, src []byte) int`. Реализуйте алгоритм, копирующий память 64-битными словами (`MOVQ`, 8 байт за шаг) с обработкой остаточных невыровненных байт (`MOVB`). Сравните производительность со стандартной функцией `copy()`.",
    "theory": "Копирование срезов памяти — одна из самых частых операций в сетевых шлюзах, сериализаторах и базах данных.\n\nПобайтное копирование в цикле `for i := range src { dst[i] = src[i] }`:\n- Выполняет $N$ итераций цикла.\n- Читает по 1 байту через инструкции `MOVB`.\n- Создает колоссальную избыточность команд конвейера процессора.\n\n**Алгоритм блочного 64-битного копирования (Word-at-a-time / Chunked Copy):**\n1. Вычисляем количество полных 8-байтных слов: `words := len / 8`.\n2. В основном цикле копируем память 8-байтными словами за одну инструкцию:\n   `MOVQ (SI), AX` $\\to$ `MOVQ AX, (DI)`. Это снижает число итераций цикла в 8 раз!\n3. Для оставшихся $0 \\dots 7$ байт (хвост): используем быстрый остаточный цикл `MOVB` или таблицу переходов (Duff's Device).\n4. Стандартная встроенная функция Go `copy()` внутри рантайма вызывает ассемблерный интринсик `runtime.memmove`, использующий векторные регистры AVX2 (32 байта за такт) или REP MOVSQ.",
    "step_by_step": "1. Реализуйте функцию `FastCopy8(dst, src []byte) int` с блочным переносом через `uint64` указатели пакета `unsafe`.\n2. Обработайте хвостовые байты среза по модулю 8.\n3. Проведите бенчмарк сравнения: наивный цикл vs `FastCopy8` vs стандартный `copy()`.\n4. Измерьте пропускную способность копирования в гигабайтах в секунду (GB/s).\n5. Проанализируйте ассемблерный вывод инструкции `REP MOVSQ`.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n\t\"unsafe\"\n)\n\n// FastCopy64 копирует память блоками по 8 байт через uint64 указатели\nfunc FastCopy64(dst, src []byte) int {\n\tn := len(src)\n\tif len(dst) < n {\n\t\tn = len(dst)\n\t}\n\tif n == 0 {\n\t\treturn 0\n\t}\n\n\twords := n / 8\n\ttail := n % 8\n\n\tsrcPtr := unsafe.Pointer(&src[0])\n\tdstPtr := unsafe.Pointer(&dst[0])\n\n\t// Основной цикл: 8 байт за одну итерацию (аналог MOVQ в asm)\n\tfor i := 0; i < words; i++ {\n\t\toffset := uintptr(i * 8)\n\t\t*(*uint64)(unsafe.Pointer(uintptr(dstPtr) + offset)) = *(*uint64)(unsafe.Pointer(uintptr(srcPtr) + offset))\n\t}\n\n\t// Хвостовые байты: 1 байт за итерацию (аналог MOVB в asm)\n\ttailStart := words * 8\n\tfor i := 0; i < tail; i++ {\n\t\toffset := uintptr(tailStart + i)\n\t\t*(*byte)(unsafe.Pointer(uintptr(dstPtr) + offset)) = *(*byte)(unsafe.Pointer(uintptr(srcPtr) + offset))\n\t}\n\n\treturn n\n}\n\nfunc main() {\n\tconst bufSize = 16 * 1024 * 1024 // 16 MB буфер\n\tsrc := make([]byte, bufSize)\n\tdst1 := make([]byte, bufSize)\n\tdst2 := make([]byte, bufSize)\n\n\tfor i := range src {\n\t\tsrc[i] = byte(i % 256)\n\t}\n\n\t// 1. FastCopy64 Benchmark\n\tstart1 := time.Now()\n\tFastCopy64(dst1, src)\n\tdur1 := time.Since(start1)\n\n\t// 2. Builtin copy() (runtime.memmove) Benchmark\n\tstart2 := time.Now()\n\tcopy(dst2, src)\n\tdur2 := time.Since(start2)\n\n\tmb := float64(bufSize) / (1024 * 1024)\n\tfmt.Println(\"=== Memory Copy Benchmark (16 MB buffer) ===\")\n\tfmt.Printf(\"FastCopy64:   %v | Speed: %.2f GB/s\\n\", dur1, (mb/1024)/dur1.Seconds())\n\tfmt.Printf(\"Builtin copy: %v | Speed: %.2f GB/s\\n\", dur2, (mb/1024)/dur2.Seconds())\n\n\t// Проверка корректности\n\tfor i := range dst1 {\n\t\tif dst1[i] != src[i] || dst2[i] != src[i] {\n\t\t\tpanic(\"copy corrupted memory\")\n\t\t}\n\t}\n\tfmt.Println(\"Verification: Memory integrity 100% verified.\")\n}\n",
        "note": "Блочное копирование памяти через 64-битные машинные слова и сравнение с runtime.memmove."
      }
    ],
    "under_the_hood": "Стандартная функция Go `copy()` компилируется не в цикл, а в интринсик `runtime.memmove`. На современных процессорах Intel/AMD `memmove` проверяет поддержку флагов процессора и использует инструкцию `REP MOVSQ` с аппаратной поддержкой Fast Short REP MOVSB (FSRM) или векторные регистры AVX-512 (64 байта за такт). Это позволяет встроенной функции `copy()` достигать физического предела пропускной способности шины памяти (25–50 ГБ/с).",
    "pitfalls": "1. Перекрытие областей памяти (Overlapping Memory): при копировании перекрывающихся срезов (например, `s[1:]` в `s[0:]`) прямой цикл вперед перезапишет невычитанные данные. Настоящий `memmove` проверяет направление перекрытия и копирует с хвоста назад при необходимости.\n2. Невыровненный доступ к памяти (Unaligned Access): на x86 невыровненное чтение `uint64` поддерживается аппаратно, но на старых архитектурах ARM вызывает аппаратное прерывание `Alignment Fault`.",
    "bigtech_interview": "«Почему самописный memcpy на Go Assembly редко обгоняет встроенный `copy()`?». Ответ: разработчики рантайма Go годами оптимизировали `runtime.memmove` под десятки микроархитектур: он учитывает размер кэшей L1/L2/L3, использует нетемпоральные инструкции прямой записи в RAM (`MOVNTQ`), минующие кэш при объемах свыше нескольких мегабайт, и оптимизирован под размер кэш-линий."
  },
  {
    "num": 8,
    "title": "Ассемблерная оптимизация вычислительного ядра хеш-функции",
    "task": "Исследуйте узкое место в алгоритме хеширования (например, FNV-1a или MurmurHash). Реализуйте вычислительное ядро хеширования с разверткой цикла (Loop Unrolling) и регистровой аккумуляцией, показав снижение времени расчета хеша на один байт.",
    "theory": "Алгоритмы хеширования лежат в основе хэш-таблиц Go (`map`), распределенных кэшей (Consistent Hashing) и контрольных сумм сетевых пакетов (CRC32, HighwayHash, xxHash).\n\n**Классический алгоритм FNV-1a (64-bit):**\n$$\\text{hash} = (\\text{hash} \\oplus \\text{byte}) \\cdot \\text{FNV\\_prime}$$\nгде $\\text{FNV\\_prime} = 1099511628211$ (`0x100000001b3`).\n\n**Оптимизация на ассемблере:**\n1. **Устранение обращений к памяти**: значение `hash` хранится строго в регистре процессора `AX`, константа `FNV_prime` — в регистре `CX`.\n2. **Развертка цикла (Loop Unrolling 4x)**: обрабатываем по 4 байта за итерацию:\n   - Читаем 4 байта одной инструкцией `MOVL`.\n   - Выполняем серии `XOR` и `IMULQ` без промежуточных проверок счетчика цикла.\n3. **Устранение накладных расходов перехода**: число инструкций перехода `JNE` сокращается в 4 раза, конвейер суперскалярного процессора насыщается независимыми операциями.",
    "step_by_step": "1. Напишите наивную функцию `HashFNV1a(data []byte) uint64`.\n2. Напишите оптимизированную функцию `HashFNV1aUnrolled(data []byte) uint64`.\n3. Проведите сравнительный бенчмарк на строках размером 1 КБ и 64 КБ.\n4. Рассчитайте пропускную способность в миллионах хешируемых байт в секунду (MB/s).\n5. Проанализируйте ассемблерные инструкции умножения `IMULQ`.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\nconst (\n\tfnvOffsetBasis = uint64(14695981039346656037)\n\tfnvPrime       = uint64(1099511628211)\n)\n\n// HashFNV1aNaive выполняет стандартный побайтовый цикл\n//\n//go:noinline\nfunc HashFNV1aNaive(data []byte) uint64 {\n\th := fnvOffsetBasis\n\tfor i := 0; i < len(data); i++ {\n\t\th ^= uint64(data[i])\n\t\th *= fnvPrime\n\t}\n\treturn h\n}\n\n// HashFNV1aUnrolled разворачивает цикл на 4 байта за такт,\n// симулируя оптимальный ассемблерный блок инструкций\n//\n//go:noinline\nfunc HashFNV1aUnrolled(data []byte) uint64 {\n\th := fnvOffsetBasis\n\tn := len(data)\n\tblocks := n / 4\n\ttail := n % 4\n\n\t// Обработка пачками по 4 байта\n\tfor i := 0; i < blocks*4; i += 4 {\n\t\t// В ассемблере это плотная последовательность XORQ + IMULQ без проверок\n\t\th = (h ^ uint64(data[i])) * fnvPrime\n\t\th = (h ^ uint64(data[i+1])) * fnvPrime\n\t\th = (h ^ uint64(data[i+2])) * fnvPrime\n\t\th = (h ^ uint64(data[i+3])) * fnvPrime\n\t}\n\n\t// Обработка хвоста\n\tfor i := n - tail; i < n; i++ {\n\t\th = (h ^ uint64(data[i])) * fnvPrime\n\t}\n\n\treturn h\n}\n\nfunc main() {\n\tconst dataSize = 64 * 1024 // 64 KB\n\tpayload := make([]byte, dataSize)\n\tfor i := range payload {\n\t\tpayload[i] = byte((i * 31) % 256)\n\t}\n\n\tconst iters = 10000\n\n\t// Benchmark Naive\n\tstart1 := time.Now()\n\tvar h1 uint64\n\tfor i := 0; i < iters; i++ {\n\t\th1 = HashFNV1aNaive(payload)\n\t}\n\tdur1 := time.Since(start1)\n\n\t// Benchmark Unrolled\n\tstart2 := time.Now()\n\tvar h2 uint64\n\tfor i := 0; i < iters; i++ {\n\t\th2 = HashFNV1aUnrolled(payload)\n\t}\n\tdur2 := time.Since(start2)\n\n\ttotalMB := float64(dataSize*iters) / (1024 * 1024)\n\tfmt.Println(\"=== FNV-1a Hash Kernel Optimization ===\")\n\tfmt.Printf(\"Naive Throughput:    %.2f MB/s (%v)\\n\", totalMB/dur1.Seconds(), dur1)\n\tfmt.Printf(\"Unrolled Throughput: %.2f MB/s (%v)\\n\", totalMB/dur2.Seconds(), dur2)\n\tif dur1 > dur2 {\n\t\tfmt.Printf(\"Speedup:             %.2fx faster\\n\", float64(dur1)/float64(dur2))\n\t}\n\n\tif h1 != h2 {\n\t\tpanic(\"hashes mismatch\")\n\t}\n\tfmt.Printf(\"Hash result: 0x%X (verified match)\\n\", h1)\n}\n",
        "note": "Развертка цикла хеширования FNV-1a с регистрацией промежуточных состояний."
      }
    ],
    "under_the_hood": "Инструкция умножения `IMULQ` на современных ядрах x86 имеет задержку (Latency) 3 такта и пропускную способность (Throughput) 1 такт. Однако операции в FNV-1a строго последовательны: результат текущего умножения нужен для следующего шага. Развертка цикла не устраняет зависимость по данным, но ликвидирует накладные расходы на инкремент счетчика `INCQ` и условный переход `JNE`, высвобождая ресурсы декодера инструкций.",
    "pitfalls": "1. Чрезмерная развертка цикла (Code Bloat): если развернуть цикл на 32 или 64 итерации, размер тела функции превысит объем кэша инструкций первого уровня (L1i Cache, обычно 32 КБ), что приведет к деградации скорости из-за промахов кэша инструкций (L1i misses).\n2. Забытый хвост: при развертке цикла на $K$ шагов всегда необходима корректная обработка остатка `len % K`.",
    "bigtech_interview": "«Почему современные хеш-функции вроде xxHash, HighwayHash или CityHash работают в 10–20 раз быстрее FNV-1a?». Ответ: они используют несколько независимых аккумуляторов параллельно (Instruction-Level Parallelism) или векторные инструкции SIMD (AVX2/AVX-512). Процессор одновременно вычисляет 4 или 8 параллельных потоков умножения, полностью загружая конвейер CPU."
  },
  {
    "num": 9,
    "title": "SIMD-векторизация через CGO и интринсики AVX2",
    "task": "Изучите использование технологии Single Instruction Multiple Data (SIMD) через CGO. Разработайте функцию сложения массивов чисел с плавающей точкой с помощью интринсиков Intel AVX2 (`_mm256_add_ps`). Проанализируйте соотношение накладных расходов вызова CGO и выигрыша от аппаратной векторизации.",
    "theory": "**SIMD (Single Instruction, Multiple Data)** — аппаратная технология процессора, позволяющая одной инструкцией выполнять одинаковую операцию сразу над несколькими элементами данных.\n\n**Векторные расширения процессоров x86:**\n- **SSE (128-bit)**: регистры `XMM0`–`XMM15`. Вмещают 4 числа `float32` или 2 числа `int64`.\n- **AVX2 (256-bit)**: регистры `YMM0`–`YMM15`. Вмещают **8 чисел `float32`** или 4 числа `int64`.\n- **AVX-512 (512-bit)**: регистры `ZMM0`–`ZMM31`. Вмещают 16 чисел `float32`.\n\n**Компромисс использования CGO для SIMD:**\n- *Плюс*: в C/C++ доступны удобные заголовочные файлы интринсиков (`<immintrin.h>`), позволяющие писать векторный код без ручного Plan 9 ассемблера.\n- *Минус (CGO Overhead)*: каждый вызов из Go в C требует переключения стека горутины на стек системного потока $M$, сохранения регистров и перевода планировщика в режим системного вызова. Задержка одного вызова CGO составляет **40–60 наносекунд**.\n- **Вывод**: SIMD через CGO эффективен только при обработке **крупных пакетов данных** (от 4 КБ и выше), где выигрыш от векторизации перекрывает фиксированную цену переключения контекста CGO.",
    "step_by_step": "1. Создайте симулятор векторных регистров AVX2 (обработка по 8 элементов `float32` за такт).\n2. Реализуйте скалярное сложение срезов `ScalarAddFloats(a, b, res []float32)`.\n3. Реализуйте векторное сложение `SIMDAddFloatsAVX2(a, b, res []float32)` с шагом в 8 элементов.\n4. Продемонстрируйте теоретический расчет оверхеда CGO против размера массива.\n5. Проведите бенчмарк на 1 000 000 элементов и зафиксируйте прирост скорости.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\n// ScalarAddFloats поэлементно складывает срезы в скалярном режиме\n//\n//go:noinline\nfunc ScalarAddFloats(a, b, res []float32) {\n\tfor i := range a {\n\t\tres[i] = a[i] + b[i]\n\t}\n}\n\n// EmulatedAVX2AddFloats симулирует работу интринсика _mm256_add_ps:\n// 1 векторная инструкция VADDPS складывает сразу 8 элементов float32!\n//\n//go:noinline\nfunc EmulatedAVX2AddFloats(a, b, res []float32) {\n\tn := len(a)\n\tsimdWidth := 8 // 256 бит / 32 бита = 8 элементов float32\n\tvecLoops := n / simdWidth\n\n\tfor i := 0; i < vecLoops*simdWidth; i += simdWidth {\n\t\t// В реальном CGO/ASM коде:\n\t\t// __m256 va = _mm256_loadu_ps(&a[i]);\n\t\t// __m256 vb = _mm256_loadu_ps(&b[i]);\n\t\t// __m256 vr = _mm256_add_ps(va, vb);\n\t\t// _mm256_storeu_ps(&res[i], vr);\n\t\tres[i+0] = a[i+0] + b[i+0]\n\t\tres[i+1] = a[i+1] + b[i+1]\n\t\tres[i+2] = a[i+2] + b[i+2]\n\t\tres[i+3] = a[i+3] + b[i+3]\n\t\tres[i+4] = a[i+4] + b[i+4]\n\t\tres[i+5] = a[i+5] + b[i+5]\n\t\tres[i+6] = a[i+6] + b[i+6]\n\t\tres[i+7] = a[i+7] + b[i+7]\n\t}\n\n\t// Хвост\n\tfor i := vecLoops * simdWidth; i < n; i++ {\n\t\tres[i] = a[i] + b[i]\n\t}\n}\n\nfunc main() {\n\tconst n = 1000000\n\ta := make([]float32, n)\n\tb := make([]float32, n)\n\tres1 := make([]float32, n)\n\tres2 := make([]float32, n)\n\n\tfor i := 0; i < n; i++ {\n\t\ta[i] = float32(i) * 0.5\n\t\tb[i] = float32(i) * 1.5\n\t}\n\n\t// Benchmark Scalar\n\tstart1 := time.Now()\n\tScalarAddFloats(a, b, res1)\n\tdur1 := time.Since(start1)\n\n\t// Benchmark Emulated SIMD AVX2\n\tstart2 := time.Now()\n\tEmulatedAVX2AddFloats(a, b, res2)\n\tdur2 := time.Since(start2)\n\n\tfmt.Println(\"=== SIMD AVX2 Vectorization Benchmark (1M float32) ===\")\n\tfmt.Printf(\"Scalar Processing: %v\\n\", dur1)\n\tfmt.Printf(\"AVX2 Vectorized:   %v\\n\", dur2)\n\tfmt.Printf(\"Speedup:           %.2fx\\n\", float64(dur1)/float64(dur2))\n\tfmt.Println(\"\\nCGO vs Pure Assembly Trade-off:\")\n\tfmt.Println(\"  CGO Call Overhead: ~50ns (good for batches > 10,000 items)\")\n\tfmt.Println(\"  Plan 9 Go Assembly: 0ns call overhead (optimal for small/medium vectors)\")\n}\n",
        "note": "Демонстрация принципов SIMD AVX2 векторизации и анализ накладных расходов CGO."
      }
    ],
    "under_the_hood": "Инструкция AVX2 `VADDPS` выполняется на портах 0 и 1 суперскалярного ядра процессора с латентностью 4 такта и пропускной способностью 0.5 такта (два 256-битных векторных сложения за один такт!). За счет этого теоретический предел вычислений с плавающей точкой возрастает в 8–16 раз по сравнению со скалярными инструкциями `ADDSS`.",
    "pitfalls": "1. Выравнивание памяти по 32 байта: инструкция `VMOVAPS` требует строгого выравнивания адреса по границе 32 байт. Если срез не выровнен, процессор выбросит аппаратное исключение General Protection Fault. Для произвольных адресов обязана использоваться инструкция невыровненной загрузки `VMOVUPS`.\n2. Частотный троттлинг AVX2/AVX-512: на старых процессорах Intel (Haswell/Skylake) выполнение тяжелых инструкций AVX приводило к автоматическому снижению тактовой частоты ядер процессора на 10–20% для сохранения термопакета.",
    "bigtech_interview": "«Почему в Go стандартный компилятор gc не поддерживает полноценную автоматическую автовекторизацию (Auto-vectorization), как GCC или Clang с ключом -O3?». Ответ: автовекторизация требует сложных эвристик анализа псевдонимов указателей (Aliasing analysis), выравнивания и раздувает время компиляции в разы. Одним из главных архитектурных приоритетов Go является молниеносная скорость компиляции, поэтому сложная автовекторизация сознательно вынесена на уровень рукописного ассемблера или CGO."
  },
  {
    "num": 10,
    "title": "Векторное сложение чисел с плавающей точкой через AVX2 (VADDPS)",
    "task": "Реализуйте ассемблерную функцию векторного сложения срезов `AddFloatsAVX2(a, b, res []float32)` на диалекте Plan 9 Assembly с использованием 256-битных инструкций Intel AVX2: `VMOVUPS` и `VADDPS`. Обеспечьте корректную обработку хвоста среза, не кратного 8 элементам.",
    "theory": "Расширение **AVX2 (Advanced Vector Extensions 2)** вводит шестнадцать 256-битных векторных регистров: от `Y0` до `Y15` (в нотации Plan 9; в синтаксисе Intel — `YMM0`–`YMM15`).\n\nОдин регистр `Y` вмещает:\n- 8 чисел `float32` (по 32 бита каждое)\n- 4 числа `float64` (по 64 бита)\n- 8 чисел `int32`\n- 4 числа `int64`\n\n**Ключевые инструкции AVX2:**\n- `VMOVUPS (SI), Y0`: невыровненная загрузка 256 бит (8 чисел `float32`) из памяти по адресу в регистре `SI` в векторный регистр `Y0`.\n- `VADDPS Y1, Y0, Y2`: трехместная векторная инструкция. Складывает попарно восемь значений `float32` из регистра `Y0` и восемь значений из `Y1`, сохраняя результат в регистр `Y2`:\n  $$Y2[k] = Y0[k] + Y1[k], \\quad k = 0 \\dots 7$$\n- `VMOVUPS Y2, (DI)`: сохранение 8 сложенных чисел `float32` из `Y2` в память по адресу в `DI` за **один такт шины кэша**!\n- `VZEROUPPER`: обязательная инструкция очистки верхних 128 бит регистров `YMM` перед возвратом из функции для исключения штрафа переключения между AVX и legacy SSE.",
    "step_by_step": "1. Создайте структуру описания ассемблерного модуля `add_floats_amd64.s`.\n2. Опишите тело цикла на Plan 9 с загрузкой указателей на базовые массивы срезов `a`, `b`, `res`.\n3. Реализуйте векторный шаг по 8 элементов `float32` (смещение на 32 байта: `ADDQ $32, SI`).\n4. Добавьте скалярный цикл для обработки хвостовых элементов.\n5. Напишите Go-тест и бенчмарк, подтверждающий 6–8-кратное аппаратное ускорение.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\n// Описание функции в файле add_floats_amd64.s:\n//\n// #include \"textflag.h\"\n//\n// // func AddFloatsAVX2Asm(a, b, res []float32)\n// TEXT ·AddFloatsAVX2Asm(SB), NOSPLIT, $0-72\n//     MOVQ a_base+0(FP), SI    // SI = &a[0]\n//     MOVQ a_len+8(FP), DX     // DX = len(a)\n//     MOVQ b_base+24(FP), BX   // BX = &b[0]\n//     MOVQ res_base+48(FP), DI // DI = &res[0]\n//\n//     SHRQ $3, DX              // DX = len / 8 (число 256-битных пакетов)\n//     TESTQ DX, DX\n//     JZ tail_loop\n//\n// loop:\n//     VMOVUPS (SI), Y0         // Загрузка 8 x float32 из a\n//     VMOVUPS (BX), Y1         // Загрузка 8 x float32 из b\n//     VADDPS Y1, Y0, Y2        // Векторное сложение 8 пар чисел\n//     VMOVUPS Y2, (DI)         // Сохранение 8 результатов в res\n//\n//     ADDQ $32, SI             // 8 элементов * 4 байта = 32 байта смещения\n//     ADDQ $32, BX\n//     ADDQ $32, DI\n//     DECQ DX\n//     JNZ loop\n//\n// tail_loop:\n//     VZEROUPPER               // Очистка AVX состояния\n//     RET\n\n// EmulatedAddFloatsAVX2 демонстрирует результат аппаратного сложения VADDPS\nfunc EmulatedAddFloatsAVX2(a, b, res []float32) {\n\tn := len(a)\n\tsimdStep := 8\n\tblocks := n / simdStep\n\n\tfor i := 0; i < blocks*simdStep; i += simdStep {\n\t\t// Векторная операция над 8 элементами\n\t\tres[i+0] = a[i+0] + b[i+0]\n\t\tres[i+1] = a[i+1] + b[i+1]\n\t\tres[i+2] = a[i+2] + b[i+2]\n\t\tres[i+3] = a[i+3] + b[i+3]\n\t\tres[i+4] = a[i+4] + b[i+4]\n\t\tres[i+5] = a[i+5] + b[i+5]\n\t\tres[i+6] = a[i+6] + b[i+6]\n\t\tres[i+7] = a[i+7] + b[i+7]\n\t}\n\n\tfor i := blocks * simdStep; i < n; i++ {\n\t\tres[i] = a[i] + b[i]\n\t}\n}\n\nfunc main() {\n\tconst count = 800000\n\ta := make([]float32, count)\n\tb := make([]float32, count)\n\tres := make([]float32, count)\n\n\tfor i := range a {\n\t\ta[i] = float32(i) * 1.1\n\t\tb[i] = float32(i) * 2.2\n\t}\n\n\tstart := time.Now()\n\tEmulatedAddFloatsAVX2(a, b, res)\n\tdur := time.Since(start)\n\n\tfmt.Println(\"=== AVX2 VADDPS Vector Processing Evaluation ===\")\n\tfmt.Printf(\"Processed %d float32 pairs in %v\\n\", count, dur)\n\tfmt.Printf(\"Sample check: res[0]=%.2f, res[7]=%.2f\\n\", res[0], res[7])\n\tfmt.Println(\"Instruction Details:\")\n\tfmt.Println(\"  VMOVUPS: Loads 256 bits (8 floats) regardless of 32-byte alignment\")\n\tfmt.Println(\"  VADDPS:  Executes 8 additions in parallel in 1 CPU cycle\")\n\tfmt.Println(\"  VZEROUPPER: Eliminates AVX-SSE transition penalty at function exit\")\n}\n",
        "note": "Пакетное векторное сложение срезов float32 с использованием инструкций AVX2."
      }
    ],
    "under_the_hood": "Инструкция `VZEROUPPER` критически важна при выходе из ассемблерных функций, использующих 256-битные регистры `YMM`. Если после AVX-кода процессор выполнит legacy SSE инструкцию (например, стандартную операцию со срезами Go), возникнет штраф перехода (AVX-to-SSE transition penalty), приводящий к заморозке ядра процессора на 70–100 тактов. Инструкция `VZEROUPPER` обнуляет верхние половины регистров, устраняя этот штраф.",
    "pitfalls": "1. Забытый `VZEROUPPER`: пропуск этой инструкции приводит к скрытой деградации производительности в последующем Go-коде, которую крайне сложно обнаружить обычным профилировщиком.\n2. Неправильный расчет смещения в срезах: срез `[]float32` в ABI0 занимает 24 байта на стеке (ptr 8 байт, len 8 байт, cap 8 байт). Второй срез `b` начинается со смещения `+24(FP)`, а третий `res` — со смещения `+48(FP)`.",
    "bigtech_interview": "«Что произойдет, если использовать инструкцию VMOVAPS вместо VMOVUPS для среза, аллоцированного стандартным make([]float32, N)?». Ответ: рантайм Go выравнивает аллокации в куче по 8 или 16 байт (в зависимости от размера span'а), но НЕ гарантирует выравнивание по границе 32 байт (256 бит). Инструкция `VMOVAPS` при невыровненном адресе мгновенно вызовет аппаратный крэш процессора `#GP` (General Protection Fault), поэтому в коде Go всегда используется `VMOVUPS`."
  },
  {
    "num": 11,
    "title": "Горизонтальная свертка векторов: SumFloat32AVX2 и VEXTRACTF128",
    "task": "Разработайте ассемблерную функцию подсчета суммы элементов среза `SumFloat32AVX2(f []float32) float32`. Реализуйте векторное накопление в регистре `Y0` и последующую горизонтальную свертку вектора (Horizontal Reduction) в скалярное число через инструкции `VEXTRACTF128`, `VADDPS` и `VHADDPS`.",
    "theory": "Суммирование среза — классическая операция редукции (Reduction). В скалярном режиме процессор выполняет сложения последовательно:\n$$\\text{sum} = (\\dots((f[0] + f[1]) + f[2]) \\dots)$$\nЗадержка инструкции сложения `ADDSS` составляет 3–4 такта, что создает строгую зависимость по данным и ограничивает IPC (Instructions Per Cycle) значением менее 0.3.\n\n**Векторная редукция на AVX2:**\n1. **Фаза параллельного накопления**:\n   - Регистр `Y0` инициализируется нулями.\n   - В цикле каждые 8 чисел `float32` прибавляются параллельно: `VADDPS (SI), Y0, Y0`.\n   - В конце регистра `Y0` находятся 8 независимых частичных сумм: $[S_0, S_1, S_2, S_3, S_4, S_5, S_6, S_7]$.\n2. **Фаза горизонтальной свертки (Horizontal Reduction)**:\n   - Векторные инструкции складывают элементы по вертикали (между регистрами), но не умеют суммировать элементы внутри одного регистра.\n   - Шаг 1: `VEXTRACTF128 $1, Y0, X1` — извлекаем старшие 128 бит $[S_4, S_5, S_6, S_7]$ в регистр `X1`.\n   - Шаг 2: `VADDPS X1, X0, X0` — складываем младшую и старшую половины: получаем 4 суммы.\n   - Шаг 3: `VHADDPS X0, X0, X0` (горизонтальное сложение пар) $\\to$ 2 суммы.\n   - Шаг 4: еще одно сложение пар дает итоговое скалярное число `float32` в младшем слоте регистра `X0`!",
    "step_by_step": "1. Создайте структуру демонстрации ассемблерной редукции.\n2. Проиллюстрируйте работу фазы векторного накопления 8 аккумуляторов.\n3. Опишите математику шагов горизонтального сложения векторов.\n4. Реализуйте Go-верификатор суммы на миллионе случайных чисел `float32`.\n5. Сравните скорость вычисления скалярного и векторного алгоритмов.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"math\"\n\t\"time\"\n)\n\n// Демонстрация файла sum_avx2_amd64.s:\n//\n// #include \"textflag.h\"\n//\n// // func SumFloat32AVX2Asm(f []float32) float32\n// TEXT ·SumFloat32AVX2Asm(SB), NOSPLIT, $0-28\n//     MOVQ f_base+0(FP), SI     // SI = &f[0]\n//     MOVQ f_len+8(FP), CX      // CX = len(f)\n//\n//     VXORPS Y0, Y0, Y0         // Y0 = [0, 0, 0, 0, 0, 0, 0, 0] (8 аккумуляторов)\n//     SHRQ $3, CX               // CX = len / 8\n//     JZ tail_check\n//\n// vector_loop:\n//     VMOVUPS (SI), Y1          // Загрузка 8 элементов\n//     VADDPS Y1, Y0, Y0         // Параллельное сложение 8 аккумуляторов\n//     ADDQ $32, SI\n//     DECQ CX\n//     JNZ vector_loop\n//\n//     // Горизонтальная редукция Y0 в скаляр X0:\n//     VEXTRACTF128 $1, Y0, X1   // X1 = старшие 4 float32 из Y0\n//     VADDPS X1, X0, X0         // X0 = X0 + X1 (4 суммы)\n//     VHADDPS X0, X0, X0        // X0 = [S0+S1, S2+S3, ...] (2 суммы)\n//     VHADDPS X0, X0, X0        // X0[0] = итоговая сумма всех 8 элементов\n//\n// tail_check:\n//     // Обработка остатка...\n//     VMOVSS X0, ret+24(FP)     // Возврат скалярного float32\n//     VZEROUPPER\n//     RET\n\n// EmulatedSumFloat32AVX2 симулирует векторное накопление и редукцию\nfunc EmulatedSumFloat32AVX2(f []float32) float32 {\n\tn := len(f)\n\tvar accum [8]float32\n\n\tblocks := n / 8\n\tfor i := 0; i < blocks*8; i += 8 {\n\t\taccum[0] += f[i+0]\n\t\taccum[1] += f[i+1]\n\t\taccum[2] += f[i+2]\n\t\taccum[3] += f[i+3]\n\t\taccum[4] += f[i+4]\n\t\taccum[5] += f[i+5]\n\t\taccum[6] += f[i+6]\n\t\taccum[7] += f[i+7]\n\t}\n\n\t// Горизонтальная свертка 8 аккумуляторов\n\ttotal := (accum[0] + accum[1] + accum[2] + accum[3]) +\n\t\t(accum[4] + accum[5] + accum[6] + accum[7])\n\n\t// Хвост\n\tfor i := blocks * 8; i < n; i++ {\n\t\ttotal += f[i]\n\t}\n\treturn total\n}\n\nfunc main() {\n\tconst size = 1000000\n\tdata := make([]float32, size)\n\tfor i := range data {\n\t\tdata[i] = 1.0 // Ожидаемая сумма = 1000000\n\t}\n\n\t// 1. Скалярный подсчет\n\tstart1 := time.Now()\n\tvar scalarSum float32\n\tfor i := 0; i < len(data); i++ {\n\t\tscalarSum += data[i]\n\t}\n\tdur1 := time.Since(start1)\n\n\t// 2. Векторный подсчет (AVX2 модель)\n\tstart2 := time.Now()\n\tavxSum := EmulatedSumFloat32AVX2(data)\n\tdur2 := time.Since(start2)\n\n\tfmt.Println(\"=== Horizontal Vector Reduction (AVX2) Evaluation ===\")\n\tfmt.Printf(\"Scalar Sum: %v in %v\\n\", scalarSum, dur1)\n\tfmt.Printf(\"AVX2 Sum:   %v in %v\\n\", avxSum, dur2)\n\tfmt.Printf(\"Reduction Speedup: %.2fx faster\\n\", float64(dur1)/float64(dur2))\n\tfmt.Printf(\"Accuracy Difference: %e\\n\", math.Abs(float64(scalarSum-avxSum)))\n}\n",
        "note": "Векторное суммирование float32 с горизонтальной редукцией через VEXTRACTF128."
      }
    ],
    "under_the_hood": "Инструкция `VEXTRACTF128` извлекает 128-битный фрагмент (половину) 256-битного регистра `YMM` в 128-битный регистр `XMM`. Инструкция `VHADDPS` (Horizontal Add) складывает соседние пары чисел `float32`. Сочетание этих двух инструкций позволяет свернуть 8-элементный вектор в скалярный результат за 3 такта процессора без выгрузки данных в оперативную память стека.",
    "pitfalls": "1. Неассоциативность сложения с плавающей точкой: порядок сложения чисел в 8 независимых аккумуляторах отличается от последовательного скалярного сложения. Из-за погрешностей округления по стандарту IEEE 754 результаты `scalarSum` и `avxSum` могут незначительно различаться в младших разрядах мантиссы.\n2. Размер возвращаемого значения: `float32` занимает 4 байта, но в фрейме стека ABI0 возвращаемое значение выравнивается до 8 байт, что необходимо учитывать в размере фрейма `$0-28` или `$0-32`.",
    "bigtech_interview": "«Почему компиляторы языка C (GCC/Clang) по умолчанию НЕ векторизуют цикл суммирования float без флага -ffast-math?». Ответ: стандарт языка C строго требует соблюдения порядка вычислений чисел с плавающей точкой. Изменение порядка сложения при векторизации нарушает битовую воспроизводимость результатов. В Go аналогично: компилятор не имеет права менять порядок сложения `float`, поэтому программист выполняет векторную редукцию вручную на ассемблере."
  },
  {
    "num": 12,
    "title": "Пакетная обработка целочисленных срезов int32 через AVX2 (VPADDD)",
    "task": "Реализуйте функцию суммирования среза 32-битных целых чисел `SumInt32AVX2(data []int32) int64`. Примените инструкцию `VPADDD` (Vector Packed Add Doubleword) для параллельной обработки восьми 32-битных целых чисел за такт с защитой от целочисленного переполнения.",
    "theory": "Обработка целочисленных массивов `[]int32` (например, идентификаторы пользователей, временные метки, индексы в базах данных) отлично подходит для векторизации AVX2.\n\n**Инструкция `VPADDD`:**\n- Обрабатывает восемь 32-битных знаковых целых чисел (`Doubleword`) одновременно в 256-битном регистре `Y0`.\n- Латентность: **1 такт процессора**.\n- Пропускная способность: **0.5 такта** (два векторных сложения за один такт ядра!).\n- За одну секунду на процессоре с частотой 3.5 ГГц ядро способно выполнить до $56 \\times 10^9$ целочисленных сложений!\n\n**Проблема целочисленного переполнения (Integer Overflow):**\nЕсли суммировать срез из 100 000 000 элементов `int32`, 32-битный аккумулятор быстро переполнится (максимум $2^{31}-1 \\approx 2.14 \\times 10^9$).\n**Архитектурное решение**:\nСуммирование ведется пачками (Chunking):\n- Внутренний цикл суммирует до 10 000 элементов в 32-битные векторные аккумуляторы.\n- Затем промежуточная сумма конвертируется в 64-битные целые числа (`VPMOVSXDQ` — Vector Pack Sign Extend Doubleword to Quadword) и аккумулируется в 64-битные регистры, гарантируя нулевой риск переполнения.",
    "step_by_step": "1. Создайте структуру демонстрации целочисленной векторизации `VPADDD`.\n2. Реализуйте скалярную функцию суммирования с приведением к `int64`.\n3. Реализуйте векторный симулятор с 8 параллельными 32-битными накопителями.\n4. Продемонстрируйте защиту от переполнения промежуточных сумм.\n5. Замерьте пропускную способность на 10 000 000 элементов `int32`.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\n// ScalarSumInt32 выполняет обычный цикл\n//\n//go:noinline\nfunc ScalarSumInt32(data []int32) int64 {\n\tvar total int64\n\tfor i := 0; i < len(data); i++ {\n\t\ttotal += int64(data[i])\n\t}\n\treturn total\n}\n\n// EmulatedAVX2SumInt32 симулирует инструкцию VPADDD (8 x int32 за такт)\n// с периодическим сбросом в 64-битные аккумуляторы во избежание переполнения\n//\n//go:noinline\nfunc EmulatedAVX2SumInt32(data []int32) int64 {\n\tn := len(data)\n\tconst chunkSize = 10000\n\tvar grandTotal int64\n\n\tfor offset := 0; offset < n; offset += chunkSize {\n\t\tend := offset + chunkSize\n\t\tif end > n {\n\t\t\tend = n\n\t\t}\n\n\t\t// Векторные аккумуляторы внутри чанка\n\t\tvar acc [8]int32\n\t\tchunkLen := end - offset\n\t\tvecLoops := chunkLen / 8\n\n\t\tfor i := 0; i < vecLoops*8; i += 8 {\n\t\t\tidx := offset + i\n\t\t\t// VPADDD Y1, Y0, Y0\n\t\t\tacc[0] += data[idx+0]\n\t\t\tacc[1] += data[idx+1]\n\t\t\tacc[2] += data[idx+2]\n\t\t\tacc[3] += data[idx+3]\n\t\t\tacc[4] += data[idx+4]\n\t\t\tacc[5] += data[idx+5]\n\t\t\tacc[6] += data[idx+6]\n\t\t\tacc[7] += data[idx+7]\n\t\t}\n\n\t\t// Сворачиваем 8 x int32 в grandTotal int64\n\t\tfor k := 0; k < 8; k++ {\n\t\t\tgrandTotal += int64(acc[k])\n\t\t}\n\n\t\t// Хвост чанка\n\t\tfor i := offset + vecLoops*8; i < end; i++ {\n\t\t\tgrandTotal += int64(data[i])\n\t\t}\n\t}\n\n\treturn grandTotal\n}\n\nfunc main() {\n\tconst n = 10000000\n\tdata := make([]int32, n)\n\tfor i := range data {\n\t\tdata[i] = int32((i % 100) - 50)\n\t}\n\n\t// 1. Скалярный тест\n\tstart1 := time.Now()\n\tres1 := ScalarSumInt32(data)\n\tdur1 := time.Since(start1)\n\n\t// 2. Векторный тест (VPADDD)\n\tstart2 := time.Now()\n\tres2 := EmulatedAVX2SumInt32(data)\n\tdur2 := time.Since(start2)\n\n\tfmt.Println(\"=== AVX2 VPADDD Integer Vectorization Benchmark ===\")\n\tfmt.Printf(\"Elements: %d int32\\n\", n)\n\tfmt.Printf(\"Scalar Time: %v | Total: %d\\n\", dur1, res1)\n\tfmt.Printf(\"AVX2 Time:   %v | Total: %d\\n\", dur2, res2)\n\tfmt.Printf(\"Throughput:  %.2f Million ints/sec\\n\", float64(n)/dur2.Seconds()/1e6)\n\tif dur1 > dur2 {\n\t\tfmt.Printf(\"Speedup:     %.2fx faster\\n\", float64(dur1)/float64(dur2))\n\t}\n\n\tif res1 != res2 {\n\t\tpanic(\"result mismatch\")\n\t}\n}\n",
        "note": "Векторизация суммирования int32 через инструкцию VPADDD с защитой от переполнения."
      }
    ],
    "under_the_hood": "Инструкция расширения знака `VPMOVSXDQ` (Sign-Extend) конвертирует четыре 32-битных числа `int32` в четыре 64-битных числа `int64` за 1 такт процессора. Это позволяет сочетать высокую плотность данных в кэше L1 (32 бита на элемент) с безопасностью 64-битной арифметики без риска арифметического переполнения.",
    "pitfalls": "1. Пренебрежение переполнением `int32`: если суммировать элементы напрямую в 32-битный регистр без чанкования, результат обнулится или станет отрицательным уже через 2 миллиарда элементов.\n2. Неверный опкод для целых чисел: попытка сложить целые числа инструкцией `VADDPS` приведет к интерпретации битов целого числа как формата IEEE 754 с искажением результата.",
    "bigtech_interview": "«Как в колоночных СУБД (ClickHouse, DuckDB) выполняется фильтрация WHERE x > 100 на миллиардах строк?». Ответ: колонка `int32` загружается в регистры AVX2, инструкция `VPCMPGTD` за 1 такт сравнивает 8 чисел с порогом, создавая битовую 8-элементную маску. Затем инструкция `VMOVMSKPS` извлекает маску в обычный 8-битный регистр, позволяя отфильтровать 8 строк за 2 процессорных такта!"
  },
  {
    "num": 13,
    "title": "Развертка цикла (Loop Unrolling) и насыщение суперскалярного конвейера",
    "task": "Изучите микроархитектурную технику развертки цикла (Loop Unrolling) на 4 независимых аккумулятора. Объясните, как разбиение единой цепочки зависимостей данных (Dependency Chain) позволяет суперскалярному процессору задействовать параллельные порты исполнения (Execution Ports).",
    "theory": "Современные процессоры x86 и ARM являются **суперскалярными с внеочередным исполнением (Out-of-Order Super-scalar Execution)**. Например, ядро Intel Golden Cove имеет 12 параллельных портов исполнения и способно выполнять до 6 инструкций за один такт!\n\n**Почему наивный цикл не загружает процессор:**\n```go\nfor i := 0; i < len(s); i++ {\n    sum += s[i] // Зависимость: sum[i] зависит от sum[i-1]\n}\n```\nХотя инструкция сложения `ADDQ` занимает 1 такт, следующая инструкция `ADDQ` **не может начаться**, пока предыдущая не завершила запись в регистр `sum`. Конвейер процессора простаивает на 75–80%, так как работает только один порт исполнения из нескольких доступных.\n\n**Паттерн нескольких аккумуляторов (Multiple Independent Accumulators):**\nРазвертываем цикл на 4 независимых потока:\n```go\nsum0 += s[i+0] // порт 0\nsum1 += s[i+1] // порт 1\nsum2 += s[i+2] // порт 5\nsum3 += s[i+3] // порт 6\n```\n1. Между инструкциями `sum0`, `sum1`, `sum2`, `sum3` **нет зависимости по данным**!\n2. Планировщик инструкций процессора (Out-of-Order Scheduler) направляет все 4 сложения на разные аппаратные АЛУ (ALU Ports) **одновременно за один такт**!\n3. В конце цикла 4 аккумулятора складываются: `total = (sum0 + sum1) + (sum2 + sum3)`.\n4. Результат: ускорение в 3–4 раза даже без использования векторных инструкций SIMD!",
    "step_by_step": "1. Напишите наивную функцию `SingleAccumulatorSum(s []int64) int64`.\n2. Напишите развернутую функцию `Unrolled4AccumulatorsSum(s []int64) int64` с 4 независимыми переменными.\n3. Добавьте корректную обработку остатка среза `len(s) % 4`.\n4. Сравните пропускную способность на срезе из 10 000 000 элементов `int64`.\n5. Продемонстрируйте метрику IPC (Instructions Per Cycle) в отчете.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\n// SingleAccumulatorSum: одна цепочка зависимости данных\n//\n//go:noinline\nfunc SingleAccumulatorSum(data []int64) int64 {\n\tvar sum int64\n\tfor i := 0; i < len(data); i++ {\n\t\tsum += data[i]\n\t}\n\treturn sum\n}\n\n// Unrolled4AccumulatorsSum: 4 параллельных независимых потока вычислений\n//\n//go:noinline\nfunc Unrolled4AccumulatorsSum(data []int64) int64 {\n\tn := len(data)\n\tblocks := n / 4\n\n\tvar sum0, sum1, sum2, sum3 int64\n\n\t// Суперскалярное ядро выполняет эти 4 инструкции параллельно на разных портах АЛУ!\n\tfor i := 0; i < blocks*4; i += 4 {\n\t\tsum0 += data[i+0]\n\t\tsum1 += data[i+1]\n\t\tsum2 += data[i+2]\n\t\tsum3 += data[i+3]\n\t}\n\n\ttotal := (sum0 + sum1) + (sum2 + sum3)\n\n\t// Хвост\n\tfor i := blocks * 4; i < n; i++ {\n\t\ttotal += data[i]\n\t}\n\treturn total\n}\n\nfunc main() {\n\tconst n = 20000000\n\tdata := make([]int64, n)\n\tfor i := range data {\n\t\tdata[i] = int64(i % 100)\n\t}\n\n\t// 1. Single Accumulator Benchmark\n\tstart1 := time.Now()\n\tres1 := SingleAccumulatorSum(data)\n\tdur1 := time.Since(start1)\n\n\t// 2. Unrolled 4 Accumulators Benchmark\n\tstart2 := time.Now()\n\tres2 := Unrolled4AccumulatorsSum(data)\n\tdur2 := time.Since(start2)\n\n\tfmt.Println(\"=== Loop Unrolling & Superscalar Pipeline Evaluation ===\")\n\tfmt.Printf(\"Single Accumulator: %v (%.2f ns/op)\\n\", dur1, float64(dur1.Nanoseconds())/n)\n\tfmt.Printf(\"4x Accumulators:    %v (%.2f ns/op)\\n\", dur2, float64(dur2.Nanoseconds())/n)\n\tif dur1 > dur2 {\n\t\tfmt.Printf(\"Speedup:            %.2fx faster purely due to Instruction-Level Parallelism (ILP)!\\n\",\n\t\t\tfloat64(dur1)/float64(dur2))\n\t}\n\n\tif res1 != res2 {\n\t\tpanic(\"results mismatch\")\n\t}\n}\n",
        "note": "Развертка цикла на 4 независимых аккумулятора для параллельного исполнения на портах АЛУ."
      }
    ],
    "under_the_hood": "В микроархитектуре процессоров Intel/AMD Reorder Buffer (ROB) отслеживает зависимости по именам регистров. Когда используются 4 разные переменные (`sum0`–`sum3`), компилятор назначает им 4 разных физических регистра (например, `AX`, `BX`, `CX`, `DX`). Модуль диспетчеризации видит отсутствие зависимостей и выдает до четырех инструкций `ADDQ` за один такт на порты 0, 1, 5, 6.",
    "pitfalls": "1. Развертка с ОДНИМ аккумулятором: если написать `sum += s[i]; sum += s[i+1]; sum += s[i+2]; sum += s[i+3]`, развертка уменьшит число переходов, но НЕ устранит зависимость по данным! Ускорения не произойдет. Обязательно использовать отдельные переменные `sum0..sum3`.\n2. Исчерпание регистров (Register Pressure): если развернуть цикл на 16 аккумуляторов на архитектуре с 16 регистрами, компилятор начнет сбрасывать переменные в стек (Stack Spilling), что резко замедлит код.",
    "bigtech_interview": "«Что такое метрика IPC (Instructions Per Cycle) и как развертка цикла влияет на нее?». Ответ: IPC показывает, сколько инструкций ядро процессора успевает завершить за один такт. В коде с сильными зависимостями данных IPC обычно составляет 0.5–1.0. Применение независимых аккумуляторов позволяет поднять IPC до 3.0–4.0, полностью утилизируя вычислительную мощность кремния."
  },
  {
    "num": 14,
    "title": "Прямая запись байт-кода машинных инструкций через директивы BYTE",
    "task": "Изучите каверзный случай: как вызывать новейшие процессорные инструкции (например, AVX-512, VAES, VPCLMULQDQ), если встроенный ассемблер Plan 9 в текущей версии Go еще не поддерживает их мнемоники. Напишите ассемблерный блок с использованием директив `BYTE`, `WORD` и `LONG`.",
    "theory": "Ассемблер Go (`cmd/asm`) обновляется синхронно с релизами языка раз в 6 месяцев. Когда Intel или ARM выпускают процессоры с новыми наборами команд (например, AVX-512 VNNI для нейросетей, инструкции прямого шифрования VAES, Key Locker), поддержка их текстовых мнемоник в Plan 9 может запаздывать на несколько лет.\n\n**Механизм Byte-code Injection в Plan 9:**\nКомпилятор ассемблера Go поддерживает директивы внедрения сырых байтов прямо в исполняемый сегмент кода:\n- `BYTE $0x66`: вставка одного байта\n- `WORD $0x0F38`: вставка 16-битного слова (Little-Endian)\n- `LONG $0x12345678`: вставка 32-битного двойного слова\n- `QUAD $0x0123456789ABCDEF`: вставка 64-битного четверного слова\n\n**Пример: вызов инструкции `RDSEED EAX` (генератор истинно случайных чисел)**\nЕсли мнемоника `RDSEED` не распознается старым ассемблером Go, инженер смотрит таблицу опкодов Intel:\nОпкод `RDSEED EAX`: `0F C7 F8`\nВ коде `.s`:\n```asm\nTEXT ·Rdseed(SB), NOSPLIT, $0-8\n    BYTE $0x0F; BYTE $0xC7; BYTE $0xF8 // RDSEED EAX\n    MOVL AX, ret+0(FP)\n    RET\n```\nЭто позволяет использовать абсолютно любые инструкции современных процессоров в день их выхода!",
    "step_by_step": "1. Создайте структуру демонстрации байт-кодового внедрения машинных инструкций.\n2. Изучите структуру опкодов x86_64: префиксы, байт операции (Opcode), байт ModR/M, байт SIB.\n3. Продемонстрируйте кодирование инструкции чтения счетчика тактов процессора `RDTSC` через `BYTE $0x0F; BYTE $0x31`.\n4. Реализуйте функцию измерения тактов процессора на Go.\n5. Запустите тест и выведите шестнадцатеричный дамп инструкций.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\n// Демонстрация файла rdtsc_amd64.s:\n//\n// #include \"textflag.h\"\n//\n// // func ReadTSCAsm() uint64\n// TEXT ·ReadTSCAsm(SB), NOSPLIT, $0-8\n//     // Инструкция RDTSC имеет машинный опкод 0x0F, 0x31\n//     // Она читает 64-битный счетчик тактов процессора в связку EDX:EAX\n//     BYTE $0x0F; BYTE $0x31    // Внедрение инструкции RDTSC\n//\n//     SHLQ $32, DX              // Сдвигаем старшие 32 бита из EDX\n//     ORQ  DX, AX               // Объединяем EDX и EAX в 64-битный результат в AX\n//     MOVQ AX, ret+0(FP)        // Возврат счетчика тактов\n//     RET\n\n// EmulatedReadTSC имитирует получение монотонно возрастающих тактов процессора\nfunc EmulatedReadTSC() uint64 {\n\t// В реальной системе это ассемблерный вызов RDTSC\n\treturn uint64(time.Now().UnixNano())\n}\n\nfunc main() {\n\tfmt.Println(\"=== Plan 9 BYTE Directives (Opcode Injection) ===\")\n\tfmt.Println(\"Use Case: Invoking cutting-edge CPU instructions not yet supported by Go assembler\")\n\tfmt.Println(\"-----------------------------------------------------------------------------------\")\n\tfmt.Println(\"Example 1: RDTSC (Read Time-Stamp Counter)\")\n\tfmt.Println(\"  Hex Opcode: 0x0F 0x31\")\n\tfmt.Println(\"  Plan 9 Syntax: BYTE $0x0F; BYTE $0x31\")\n\tfmt.Println(\"Example 2: AVX-512 VPADDD ZMM0, ZMM1, ZMM2\")\n\tfmt.Println(\"  EVEX Prefix:   BYTE $0x62; BYTE $0xF1; BYTE $0x7D; BYTE $0x48\")\n\tfmt.Println(\"  Opcode:        BYTE $0xFE; BYTE $0xD1\")\n\n\tt1 := EmulatedReadTSC()\n\t// Полезная работа\n\tvar sum int\n\tfor i := 0; i < 10000; i++ {\n\t\tsum += i\n\t}\n\tt2 := EmulatedReadTSC()\n\n\tfmt.Printf(\"\\nBenchmarked code execution: %d nanocycles (Checksum: %d)\\n\", t2-t1, sum)\n\tfmt.Println(\"BYTE directives guarantee 100% future-proof compatibility with any modern hardware.\")\n}\n",
        "note": "Внедрение сырых машинных кодов через директивы BYTE для неподдерживаемых инструкций."
      }
    ],
    "under_the_hood": "Инструмент `asm2plan9s` (разработанный инженерами MinIO) автоматически принимает на вход синтаксис NASM/YASM (например, инструкции AVX-512) и генерирует готовый файл Plan 9 Go Assembly, где неподдерживаемые инструкции автоматически заменяются директивами `BYTE / WORD / LONG`. Это позволило реализовать сверхбыстрые криптографические библиотеки (ChaCha20, AES-GCM) в экосистеме Go за годы до их официального включения в ассемблер языка.",
    "pitfalls": "1. Ошибки в таблице опкодов: ручной ввод байтов опасен — опечатка в одном бите поля ModR/M приведет к невалидной инструкции (Illegal Instruction `SIGILL`) или разрушению памяти процесса.\n2. Непереносимость: код с байтами x86_64 немедленно вызовет панику при компиляции под ARM64. Такие ассемблерные файлы обязаны иметь build tags: `//go:build amd64`.",
    "bigtech_interview": "«Как стандартная библиотека Go (пакет crypto/sha256) использует новейшие инструкции Intel SHA Extensions (SHA256RNDS2)?». Ответ: через ассемблерные файлы `sha256_amd64.s`, где при отсутствии прямой поддержки компилятором использовались байтовые директивы. Это ускорило вычисление SHA-256 в 5 раз по сравнению со стандартным кодом Go."
  },
  {
    "num": 15,
    "title": "Первый Assembly файл: правила линковки, //go:noescape и go_asm.h",
    "task": "Создайте полноценный проект из файла Go `math.go` и ассемблерного файла `math_amd64.s`. Изучите работу директив компилятора `//go:noescape`, генерацию заголовка `go_asm.h` и правила экспорта констант структур из Go в ассемблер.",
    "theory": "При интеграции ассемблерного кода с Go разработчики сталкиваются с тонкостями системы типов и escape-анализа:\n\n**1. Проблема побега в кучу (Escape Analysis) и `//go:noescape`:**\nКогда функция объявлена на ассемблере без тела в `.go` файле:\n```go\nfunc Transform(buf *byte)\n```\nКомпилятор Go не может проанализировать тело функции (оно на ассемблере). По правилам безопасности Go компилятор предполагает худшее: *«указатель может быть сохранен в глобальной переменной»* — и принудительно эвакуирует переданный объект из стека в кучу (Heap Allocation).\nДиректива `//go:noescape` сообщает компилятору: *«Эта функция не сохраняет указатель за пределами своего стека»*, предотвращая лишнюю аллокацию в куче!\n\n**2. Автоматический заголовочный файл `go_asm.h`:**\nПри сборке пакета компилятор Go автоматически генерирует временный C-подобный заголовочный файл `go_asm.h`. Он содержит `#define` константы смещений полей всех структур Go:\n```go\ntype Header struct {\n    Magic uint32\n    Size  uint32\n}\n```\nВ ассемблере можно писать не загадочные цифры `+4(SI)`, а мнемонические константы:\n`MOVL Header_Size(SI), AX`! Это исключает баги смещений при изменении структур Go.",
    "step_by_step": "1. Создайте структуру демонстрации взаимодействия `math.go` и `math_amd64.s`.\n2. Опишите синтаксис директивы `//go:noescape`.\n3. Разберите использование макросов из `go_asm.h` для доступа к полям структуры.\n4. Продемонстрируйте тест на аллокации памяти (`testing.AllocsPerRun == 0`).\n5. Зафиксируйте правила оформления production-grade ассемблерных модулей в Go.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"testing\"\n\t\"unsafe\"\n)\n\n// DataPacket иллюстрирует структуру, смещения которой\n// автоматически генерируются компилятором Go в заголовочном файле go_asm.h:\n//\n// #define DataPacket_ID 0\n// #define DataPacket_Flags 8\n// #define DataPacket_Value 16\n// #define const_DataPacketSize 24\ntype DataPacket struct {\n\tID    int64\n\tFlags int64\n\tValue int64\n}\n\n// В реальном проекте:\n//\n// //go:noescape\n// func ProcessPacketAsm(p *DataPacket)\n//\n// В файле packet_amd64.s:\n// #include \"textflag.h\"\n// #include \"go_asm.h\"\n//\n// TEXT ·ProcessPacketAsm(SB), NOSPLIT, $0-8\n//     MOVQ p+0(FP), SI\n//     MOVQ DataPacket_Value(SI), AX  // Использование макроса вместо числа 16!\n//     ADDQ $1, AX\n//     MOVQ AX, DataPacket_Value(SI)\n//     RET\n\n// EmulatedProcessPacket симулирует ассемблерную модификацию полей\nfunc EmulatedProcessPacket(p *DataPacket) {\n\tp.Value += 1\n}\n\nfunc main() {\n\tpkt := DataPacket{\n\t\tID:    101,\n\t\tFlags: 0,\n\t\tValue: 500,\n\t}\n\n\tfmt.Println(\"=== Go Assembly Project Architecture ===\")\n\tfmt.Println(\"1. Directive //go:noescape informs compiler that pointer does not escape to heap\")\n\tfmt.Println(\"2. Header go_asm.h generates portable field offsets:\")\n\tfmt.Printf(\"   Offset of ID:    %d bytes\\n\", unsafe.Offsetof(pkt.ID))\n\tfmt.Printf(\"   Offset of Flags: %d bytes\\n\", unsafe.Offsetof(pkt.Flags))\n\tfmt.Printf(\"   Offset of Value: %d bytes\\n\", unsafe.Offsetof(pkt.Value))\n\n\t// Замер аллокаций памяти\n\tallocs := testing.AllocsPerRun(1000, func() {\n\t\tlocalPkt := DataPacket{Value: 10}\n\t\tEmulatedProcessPacket(&localPkt)\n\t})\n\n\tfmt.Printf(\"\\nZero-Allocation Verification: %.0f allocs/op (Stack allocated)\\n\", allocs)\n\tEmulatedProcessPacket(&pkt)\n\tfmt.Printf(\"Packet Value updated to: %d\\n\", pkt.Value)\n}\n",
        "note": "Использование go_asm.h для безопасных смещений и директивы //go:noescape против аллокаций."
      }
    ],
    "under_the_hood": "Директива `//go:noescape` доступна только для функций без тела (внешних функций ассемблера). Без нее любой вызов `ProcessPacket(&p)` приведет к немедленной аллокации `new(DataPacket)` в куче, порождая паразитный мусор для Garbage Collector на каждом сетевом пакете. Заголовочный файл `go_asm.h` генерируется на лету утилитой `cmd/compile -asmhdr`.",
    "pitfalls": "1. Ошибочное использование `//go:noescape` при сохранении указателя: если ассемблерный код сохранит переданный указатель в глобальной памяти, а вызывающая функция выйдет, память в стеке будет перезаписана другим фреймом, вызвав катастрофический Use-After-Free баг.\n2. Имя файла без суффикса архитектуры: если назвать файл просто `math.s` вместо `math_amd64.s`, компилятор попытается скомпилировать инструкции x86 на ARM64 и сборка упадет.",
    "bigtech_interview": "«Как проверить, эвакуирует ли функция указатель в кучу?». Ответ: запустить сборку с флагом escape-анализа `go build -gcflags=\"-m\"`. Компилятор выведет отчет вида `p does not escape` или `moved to heap: p`."
  },
  {
    "num": 16,
    "title": "Branchless программирование: вычисление модуля числа без условных переходов",
    "task": "Реализуйте безветвящуюся (Branchless) функцию вычисления модуля числа `Abs(x int64) int64` с помощью битовой арифметики: `mask := x >> 63; return (x ^ mask) - mask`. Докажите с помощью `go tool objdump` полное отсутствие инструкций перехода `JMP`/`JGE`, и сравните скорость со стандартным `if x < 0 { return -x }`.",
    "theory": "Вычисление абсолютного значения числа `Abs(x)` кажется тривиальным, но в высоконагруженных алгоритмах компьютерной графики, физических симуляциях и расчетах метрик расстояний (Manhattan / Euclidean distance) оно выполняется миллиарды раз.\n\n**Анатомия наивного решения:**\n```go\nfunc AbsBranching(x int64) int64 {\n    if x < 0 { return -x }\n    return x\n}\n```\nЕсли входной поток содержит чередующиеся положительные и отрицательные числа, блок предсказания переходов процессора ошибается в 50% случаев, сбрасывая конвейер CPU и тратя 15–20 тактов на каждое число!\n\n**Математика Branchless трюка:**\n1. Арифметический сдвиг вправо на 63 бита `mask := x >> 63`:\n   - Если $x \\ge 0$, старший знаковый бит равен 0, поэтому `mask == 0x0000000000000000` (ноль).\n   - Если $x < 0$, знаковый бит равен 1. При арифметическом сдвиге знак размножается на все 64 разряда, поэтому `mask == 0xFFFFFFFFFFFFFFFF` (число $-1$ в дополнительном коде).\n2. Выражение `(x ^ mask) - mask`:\n   - При $x \\ge 0$: `(x ^ 0) - 0 = x`.\n   - При $x < 0$: `(x ^ -1) - (-1)`. Побитовое исключающее ИЛИ с всеми единицами (`x ^ -1`) — это побитовое отрицание `~x`. А `~x - (-1)` равно `~x + 1`, что в точности соответствует математическому определению операции отрицания числа в дополнительном коде (Two's Complement Negation: $-x = \\sim x + 1$)!\n3. **Результат**: ровно две процессорные инструкции `XORQ` и `SUBQ`, **ноль условных переходов**, идеальная линейность конвейера!",
    "step_by_step": "1. Напишите ветвящуюся функцию `AbsBranch(x int64) int64`.\n2. Напишите безветвящуюся функцию `AbsBranchless(x int64) int64`.\n3. Сгенерируйте массив случайных знаковых чисел от $-10000$ до $+10000$.\n4. Проведите сравнительный замер времени выполнения на 20 000 000 чисел.\n5. Продемонстрируйте эквивалентность результатов и прирост скорости.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"math/rand\"\n\t\"time\"\n)\n\n// AbsBranch использует проверку знака if x < 0\n//\n//go:noinline\nfunc AbsBranch(x int64) int64 {\n\tif x < 0 {\n\t\treturn -x\n\t}\n\treturn x\n}\n\n// AbsBranchless вычисляет модуль без условных переходов\n//\n// В ассемблере x86_64:\n//   MOVQ AX, CX\n//   SARQ $63, CX     // CX = mask (все 0 или все 1)\n//   XORQ CX, AX      // AX = x ^ mask\n//   SUBQ CX, AX      // AX = (x ^ mask) - mask\n//\n//go:noinline\nfunc AbsBranchless(x int64) int64 {\n\tmask := x >> 63\n\treturn (x ^ mask) - mask\n}\n\nfunc main() {\n\tconst count = 20000000\n\tdata := make([]int64, count)\n\tr := rand.New(rand.NewSource(time.Now().UnixNano()))\n\tfor i := range data {\n\t\tdata[i] = r.Int63n(20000) - 10000 // от -10000 до 9999\n\t}\n\n\t// 1. Benchmark Branching Abs\n\tstart1 := time.Now()\n\tvar sum1 int64\n\tfor i := 0; i < count; i++ {\n\t\tsum1 += AbsBranch(data[i])\n\t}\n\tdur1 := time.Since(start1)\n\n\t// 2. Benchmark Branchless Abs\n\tstart2 := time.Now()\n\tvar sum2 int64\n\tfor i := 0; i < count; i++ {\n\t\tsum2 += AbsBranchless(data[i])\n\t}\n\tdur2 := time.Since(start2)\n\n\tfmt.Println(\"=== Branchless vs Branching Abs Benchmark (20M numbers) ===\")\n\tfmt.Printf(\"Branching Abs:  %v (%.2f ns/op)\\n\", dur1, float64(dur1.Nanoseconds())/count)\n\tfmt.Printf(\"Branchless Abs: %v (%.2f ns/op)\\n\", dur2, float64(dur2.Nanoseconds())/count)\n\tif dur1 > dur2 {\n\t\tfmt.Printf(\"Speedup:        %.2fx faster (Zero branch predictor misses)\\n\", float64(dur1)/float64(dur2))\n\t}\n\n\tif sum1 != sum2 {\n\t\tpanic(\"results mismatch\")\n\t}\n\tfmt.Println(\"Verification: 100% mathematical match.\")\n}\n",
        "note": "Вычисление абсолютного значения числа без ветвлений через арифметический сдвиг и XOR."
      }
    ],
    "under_the_hood": "Инструкция `SARQ $63, CX` (Shift Arithmetic Right) сохраняет знаковый бит. Если число отрицательное, бит 1 копируется во все 64 разряда. Следующие инструкции `XORQ` и `SUBQ` имеют латентность 1 такт и выполняются на любых портах АЛУ. Процессор не выполняет спекулятивных предсказаний, а счетчик `branch-misses` остается равным нулю.",
    "pitfalls": "1. Граничный случай `math.MinInt64`: для числа $-2^{63}$ положительного аналога в знаковой 64-битной сетке не существует (максимум $+2^{63}-1$). Как ветвящаяся, так и branchless версия при `math.MinInt64` вернут исходное отрицательное число из-за переполнения `int64`.\n2. Логический сдвиг вместо арифметического: если случайно использовать беззнаковый тип `uint64(x) >> 63`, сдвиг заполнит старшие разряды нулями, а не единицами, и формула сломается.",
    "bigtech_interview": "«Как устроен алгоритм binary search (двоичный поиск) без ветвлений?». Ответ: традиционный `if target > arr[mid] { low = mid + 1 }` заменяется на безусловное вычисление смещения через CMOV или арифметику: `low += (target > arr[mid]) * step`. Это ускоряет поиск в больших кэш-несвязанных массивах в 2–3 раза."
  },
  {
    "num": 17,
    "title": "Динамический опрос флагов процессора (CPUID) и Runtime Dispatch",
    "task": "Реализуйте механизм динамического выбора алгоритма (Runtime Dispatching) в зависимости от аппаратных возможностей процессора хоста (AVX2, SSE4.2, ARM NEON). Обеспечьте быстрый вызов оптимизированной векторной функции при наличии флагов и безопасный скалярный Fallback на устаревших серверах.",
    "theory": "При дистрибуции скомпилированных бинарных файлов Go (например, через Docker-образы или пакетные менеджеры) сервис должен надежно запускаться на любом оборудовании — от старых облачных виртуальных машин 2012 года (где нет AVX2) до новейших серверов AMD EPYC / Intel Xeon.\n\nЕсли скомпилировать бинарник с безусловными инструкциями AVX2, на старом процессоре программа немедленно упадет с фатальной ошибкой ядра ОС `SIGILL: illegal instruction`.\n\n**Паттерн Runtime Feature Dispatching (CPU Detection):**\n1. **Инициализация при старте (`init()`)**:\n   - Программа опрашивает аппаратные регистры процессора через инструкцию `CPUID` (в Go доступно через пакет `internal/cpu` или `golang.org/x/sys/cpu`).\n   - Проверяется флаг `cpu.X86.HasAVX2` или `cpu.ARM64.HasASIMD`.\n2. **Указатель на функцию (Function Pointer Dispatch)**:\n   - Объявляется глобальная переменная функции: `var vectorAddFn func(a, b, res []float32)`.\n   - Если AVX2 поддерживается процессором, переменная инициализируется ассемблерной функцией `AddFloatsAVX2`.\n   - Если AVX2 отсутствует, выставляется скалярный безопасный fallback `AddFloatsScalar`.\n3. При каждом вызове в рантайме нет никаких `if`: вызов идет прямо по указателю на функцию!",
    "step_by_step": "1. Создайте структуру детектора возможностей процессора (симуляция `CPUID`).\n2. Объявите сигнатуру функции и глобальную переменную диспетчера.\n3. Реализуйте скалярную реализацию (Fallback).\n4. Реализуйте оптимизированную реализацию (AVX2).\n5. Напишите функцию `initDispatcher()`, выбирающую алгоритм, и протестируйте оба сценария.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"runtime\"\n)\n\n// CPUFeatures симулирует флаги, определяемые через инструкцию CPUID\ntype CPUFeatures struct {\n\tHasAVX2 bool\n\tHasSSE42 bool\n\tHasAVX512 bool\n}\n\n// Диспетчеризуемая функция\nvar processBatchFn func(dst, src []float32)\n\n// Скалярный fallback для любых CPU\nfunc processBatchScalar(dst, src []float32) {\n\tfor i := range src {\n\t\tdst[i] = src[i] * 2.0\n\t}\n}\n\n// Оптимизированный AVX2 обработчик\nfunc processBatchAVX2(dst, src []float32) {\n\tn := len(src)\n\t// Векторная обработка по 8 элементов\n\tfor i := 0; i < (n/8)*8; i += 8 {\n\t\tdst[i+0] = src[i+0] * 2.0\n\t\tdst[i+1] = src[i+1] * 2.0\n\t\tdst[i+2] = src[i+2] * 2.0\n\t\tdst[i+3] = src[i+3] * 2.0\n\t\tdst[i+4] = src[i+4] * 2.0\n\t\tdst[i+5] = src[i+5] * 2.0\n\t\tdst[i+6] = src[i+6] * 2.0\n\t\tdst[i+7] = src[i+7] * 2.0\n\t}\n\tfor i := (n / 8) * 8; i < n; i++ {\n\t\tdst[i] = src[i] * 2.0\n\t}\n}\n\n// initDispatch настраивает глобальный указатель при старте\nfunc initDispatch(features CPUFeatures) {\n\tif features.HasAVX2 && runtime.GOARCH == \"amd64\" {\n\t\tprocessBatchFn = processBatchAVX2\n\t\tfmt.Println(\"[Dispatcher] Hardware AVX2 detected: Activated 256-bit SIMD fast path.\")\n\t} else {\n\t\tprocessBatchFn = processBatchScalar\n\t\tfmt.Println(\"[Dispatcher] Fallback mode: Activated generic scalar path.\")\n\t}\n}\n\nfunc main() {\n\tfmt.Println(\"=== Runtime CPU Feature Detection & Dispatching ===\")\n\tfmt.Printf(\"OS: %s | Architecture: %s\\n\\n\", runtime.GOOS, runtime.GOARCH)\n\n\t// Сценарий 1: Современный хост с AVX2\n\tinitDispatch(CPUFeatures{HasAVX2: true, HasSSE42: true})\n\tsrc := []float32{1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5}\n\tdst := make([]float32, len(src))\n\tprocessBatchFn(dst, src)\n\tfmt.Printf(\"AVX2 Result: %v\\n\\n\", dst)\n\n\t// Сценарий 2: Устаревший хост без AVX2 (симуляция)\n\tinitDispatch(CPUFeatures{HasAVX2: false, HasSSE42: true})\n\tprocessBatchFn(dst, src)\n\tfmt.Printf(\"Scalar Result: %v\\n\", dst)\n}\n",
        "note": "Динамический выбор аппаратного пути (Runtime Dispatching) по флагам CPUID."
      }
    ],
    "under_the_hood": "В стандартной библиотеке Go (например, `crypto/aes`, `math/big`, `bytes.IndexByte`) используется точно такой же паттерн: в файле `cpu_x86.go` при инициализации вызывается ассемблерная функция `runtime.cpuid`, а глобальные функциональные указатели выставляются один раз при загрузке программы. Это исключает накладные расходы на проверку флагов `if hasAVX2` внутри каждого вызова.",
    "pitfalls": "1. Проверка `runtime.GOARCH`: флаг `HasAVX2` имеет смысл проверять только на `amd64`. Если забыть проверку архитектуры, компиляция под `arm64` или `riscv64` сломается.\n2. Косвенный вызов функции (Indirect Call): вызов через указатель `processBatchFn()` не может быть инлайнен компилятором. Для ультра-коротких функций (менее 5 нс) накладные расходы на косвенный вызов могут нивелировать выигрыш от SIMD.",
    "bigtech_interview": "«Как в Go работает переменная окружения GODEBUG=cpu.all=off?». Ответ: флаги `GODEBUG` позволяют принудительно отключить использование расширений процессора (AVX, SSE, AES) рантаймом Go. Это используется в тестировании и CI/CD пайплайнах для проверки работоспособности Fallback-веток кода на современном оборудовании."
  },
  {
    "num": 18,
    "title": "Профилирование аппаратными счетчиками: perf stat и анализ IPC хот-спота",
    "task": "Изучите профилирование критических секций Go-кода с помощью низкоуровневых счетчиков производительности ядра Linux (`perf stat` / `perf record`). Проанализируйте метрики тактов процессора (`cycles`), инструкций (`instructions`), коэффициента IPC и промахов кэшей L1-D/L1-I.",
    "theory": "Стандартный профайлер Go `pprof` сэмплирует стек вызовов каждые 10 мс через сигналы операционной системы (`SIGPROF`). Он отлично находит функции, где программа проводит время, но **не способен объяснить причину задержки**: почему идентичные по коду циклы работают с разницей в 5 раз?\n\n**Низкоуровневый профайлер Linux `perf`:**\nИспользует аппаратные счетчики Performance Monitoring Unit (PMU), встроенные в кристалл процессора:\n- `cycles`: общее количество тактов, затраченных процессором.\n- `instructions`: количество реально выполненных инструкций.\n- **IPC (Instructions Per Cycle) = `instructions / cycles`**:\n  - $\\text{IPC} > 2.0$: отличный результат (Compute-Bound, процессор работает на полную мощность).\n  - $\\text{IPC} < 0.8$: плохой результат (Memory-Bound, процессор 70% времени простаивает в ожидании данных из оперативной памяти или из-за промахов кэша).\n- `branch-misses`: процент ошибок предсказателя переходов.\n- `L1-dcache-load-misses`: промахи кэша данных первого уровня.\n- `cache-misses`: промахи кэша последнего уровня (LLC / L3), приводящие к медленным обращениям в DRAM.",
    "step_by_step": "1. Создайте программу для исследования двух различных профилей нагрузки: Memory-Bound (случайный доступ) и Compute-Bound (последовательный доступ).\n2. Реализуйте алгоритм расчета метрик циклов и задержек.\n3. Опишите команды консоли Linux: `perf stat -e cycles,instructions,cache-misses,branch-misses ./main`.\n4. Запустите тесты и сравните расчетный IPC для обоих сценариев.\n5. Сформулируйте инженерный чеклист аппаратного профилирования хот-спотов.",
    "code_blocks": [
      {
        "filename": "main.go",
        "lang": "go",
        "code": "package main\n\nimport (\n\t\"fmt\"\n\t\"math/rand\"\n\t\"time\"\n)\n\n// ComputeBoundTask: высокая плотность вычислений, идеальная локальность кэша (высокий IPC)\n//\n//go:noinline\nfunc ComputeBoundTask(n int) int64 {\n\tvar sum0, sum1, sum2, sum3 int64\n\tfor i := 0; i < n; i++ {\n\t\tv := int64(i)\n\t\tsum0 += v * 3\n\t\tsum1 += v * 5\n\t\tsum2 += v * 7\n\t\tsum3 += v * 11\n\t}\n\treturn sum0 + sum1 + sum2 + sum3\n}\n\n// MemoryBoundTask: случайный доступ к памяти (Pointer Chasing), промахи кэша (низкий IPC)\n//\n//go:noinline\nfunc MemoryBoundTask(arr []int, indices []int) int64 {\n\tvar sum int64\n\tfor i := 0; i < len(indices); i++ {\n\t\tidx := indices[i]\n\t\tsum += int64(arr[idx]) // Случайное чтение памяти: L1/L2/L3 cache misses!\n\t}\n\treturn sum\n}\n\nfunc main() {\n\tconst iters = 10000000\n\n\t// 1. Тест Compute-Bound\n\tstart1 := time.Now()\n\tres1 := ComputeBoundTask(iters)\n\tdur1 := time.Since(start1)\n\n\t// 2. Тест Memory-Bound\n\tconst memSize = 16 * 1024 * 1024 // 16M целых чисел (64 MB > L3 кэша)\n\tarr := make([]int, memSize)\n\tindices := make([]int, iters)\n\tr := rand.New(rand.NewSource(42))\n\tfor i := 0; i < iters; i++ {\n\t\tindices[i] = r.Intn(memSize)\n\t}\n\n\tstart2 := time.Now()\n\tres2 := MemoryBoundTask(arr, indices)\n\tdur2 := time.Since(start2)\n\n\tfmt.Println(\"=== Linux Perf & Hardware Counters Analysis ===\")\n\tfmt.Printf(\"Compute-Bound: %v (%.2f ns/op) | Checksum: %d\\n\", dur1, float64(dur1.Nanoseconds())/iters, res1)\n\tfmt.Printf(\"Memory-Bound:  %v (%.2f ns/op) | Checksum: %d\\n\", dur2, float64(dur2.Nanoseconds())/iters, res2)\n\tfmt.Printf(\"Memory Access Overhead: %.2fx slower due to cache misses and CPU pipeline stalls!\\n\\n\",\n\t\tfloat64(dur2)/float64(dur1))\n\n\tfmt.Println(\"Linux perf stat command for this binary:\")\n\tfmt.Println(\"  perf stat -e cycles,instructions,cache-misses,branch-misses ./main\")\n\tfmt.Println(\"Expected Metric Signatures:\")\n\tfmt.Println(\"  Compute-Bound: IPC ~ 2.5 - 3.5 | cache-misses < 0.1%\")\n\tfmt.Println(\"  Memory-Bound:  IPC ~ 0.3 - 0.6 | cache-misses > 20%\")\n}\n",
        "note": "Сравнение Compute-Bound и Memory-Bound нагрузок с анализом метрик IPC и промахов кэша."
      }
    ],
    "under_the_hood": "Когда ядро процессора сталкивается с промахом кэша L3 (LLC Miss), процессор отправляет запрос в контроллер памяти (DRAM). Время ожидания ответа составляет 50–100 наносекунд (200–300 тактов процессора). В это время конвейер ядра полностью блокируется (CPU Stall). Инструмент `perf` регистрирует эти события через счетчик `cycle_activity.stalls_l3_miss`.",
    "pitfalls": "1. Запуск perf в виртуальной машине без vPMC: по умолчанию многие гипервизоры (VirtualBox, AWS EC2 стандартные инстансы) отключают виртуализацию аппаратных счетчиков PMU. Для работы `perf` требуется поддержка профилей bare-metal или флаг `vPMC: on`.\n2. Права доступа в Linux: для сбора системных метрик perf требуются права root или настройка `sysctl -w kernel.perf_event_paranoid=0`.",
    "bigtech_interview": "«Что вы предпримете, если perf stat показывает для критической функции IPC = 0.4 и L1-dcache-load-misses = 35%?». Ответ: это классический признак Memory-Bound bottleneck (разрушение кэш-локальности). Оптимизация заключается не в переписывании на ассемблер, а в реорганизации структур данных (Data-Oriented Design): переход от связанных списков/указателей к плоским массивам (AoS $\\to$ SoA), блочная обработка (Tiling) под размер кэша L1 (32 КБ) и использование аппаратного префетчинга."
  }
]
